//tealium universal tag - utag.50 ut4.0.201410292233, Copyright 2014 Tealium.com Inc. All Rights Reserved.
var _umbel=_umbel||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState==='complete'||this.readyState==='loaded')&&!b.hFlag){b.hFlag=1;o.cb();}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb();}};}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"product_unit_price":"price","product_quantity":"quantity"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"","apikey":"qwygixvuthpcimgr","birth_year":"","gender":"","email":"","facebook_access_token":"","twitter_user_id":"","test_mode":"","order_id":"","customer_id":"","customer_city":"","customer_state":"","customer_zip":"","customer_country":"","product_sku":[],"product_category":[],"product_subcategory":[],"product_name":[],"price":[]};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_id=u.data.order_id||b._corder;u.data.customer_id=u.data.customer_id||b._ccustid;u.data.customer_city=u.data.customer_city||b._ccity;u.data.customer_state=u.data.customer_state||b._cstate;u.data.customer_zip=u.data.customer_zip||b._czip;u.data.customer_country=u.data.customer_country||b._ccountry;if(u.data.product_sku.length===0&&b._csku!==undefined){u.data.product_sku=b._csku.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_subcategory.length===0&&b._ccat2!==undefined){u.data.product_subcategory=b._ccat2.slice(0);}
if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
u.loader_cb=function(){u.initialized=true;if(u.data.customer_id){_umbel.push({"type":"set","name":"profile.unique_id","value":u.data.customer_id});}
if(u.data.customer_zip){_umbel.push({"type":"set","name":"profile.zip","value":u.data.customer_zip});}
if(u.data.customer_city){_umbel.push({"type":"set","name":"profile.city","value":u.data.customer_city});}
if(u.data.customer_country){_umbel.push({"type":"set","name":"profile.country","value":u.data.customer_country});}
if(u.data.customer_state){_umbel.push({"type":"set","name":"profile.state","value":u.data.customer_state});}
if(u.data.birth_year){_umbel.push({"type":"set","name":"profile.birth_year","value":u.data.birth_year});}
if(u.data.gender){_umbel.push({"type":"set","name":"profile.gender","value":u.data.gender});}
if(u.data.email){_umbel.push({"type":"set","name":"profile.email","value":u.data.email});}
if(u.data.facebook_access_token){_umbel.push({"type":"set","name":"profile.facebook_access_token","value":u.data.facebook_access_token});}
if(u.data.twitter_user_id){_umbel.push({"type":"set","name":"profile.twitter_user_id","value":u.data.twitter_user_id});}
if(u.data.product_sku&&b.page_type==="Product"){_umbel.push({"type":"send","name":"sku.tag","value":{"sku":u.data.product_sku[0],"name":u.data.product_name[0],"category":u.data.product_category[0],"price":u.data.price[0]}});}
if(u.data.order_id){var o=[];for(i=0;i<u.data.product_sku.length;i++){o.push({"sku":u.data.product_sku[i],"quantity":u.data.quantity[i],"unit_price":u.data.price[i]})}
_umbel.push({"type":"send","name":"order.tag","value":{"order_id":u.data.order_id,"currency":b._ccurrency,"items":o}});}};if(u.data.test_mode)window._umbel_test_mode=u.data.test_mode;if(!u.initialized){if(!u.data.base_url){u.data.base_url="//tags.api.umbel.com/"+u.data.apikey+"/w.js";}
u.loader({"type":"script","src":u.data.base_url+"?d="+new Date().getMonth()+"-"+new Date().getDate(),"cb":u.loader_cb,"loc":"script","id":'utag_50'});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);}('50','calendars.com.main'));}catch(error){utag.DB(error);}
