{

var google_ads = new Array();
var google_ad;
var google_radlinks = new Array();
var google_radlink;
var google_info = new Object();
google_ad = {}; 
google_ad.n = 1; 
google_ad.type = "text"; 
google_ad.bidtype = "CPC"; 
google_ad.targeting_type = "contextual"; 
google_ad.url = "http://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=CrxGFG4p-VNTcMsnVfJacgOgBi5Wm8QXD_p6ewAHAjbcBEAEgyO_9FSgGYMkGoAH1wpTQA8gBAagDAaoEvAFP0MKXwX9Z2SfzUyvSPjCTFp1bNx1MmMw0sy_upM-FLoSzhQkwN4QAudoZOdC6rbd-WxERrlsM5cepD2KqjC-9ln1dnSApKYsTnOXwnQidYWQsP9PiNVmIgYbjwtosueZPHdMPrFPoX5PcFfWky7yapBPGBej-WcFVljZieYGYhsFZtpIIprEY-DA1pzwM9M-PtFW1BBLBAvNlqKiWw_sbIO0qC0O0N65SXL14zP56wH09xDPK-nfvBQt7M4gGAYAH87zrLw&amp;num=1&amp;cid=5Gi1s3toe9u7GP3DKFQRi2tx&amp;sig=AOD64_1_IlfpyqGK3B8nsXqco_j5RmU6Ng&amp;client=ca-macys_js&amp;adurl=http://cuff.io/%3Futm_source%3DAdWords%26utm_medium%3DCPC%26utm_campaign%3DA01SDtext"; 
google_ad.visible_url = "cuff.io"; 
google_ad.log_info = "BUqUFG4p-VNTcMsnVfJacgOgBAMP-np7AAQAAEAE4AcgBAagTgAE";
google_ad.activeview_js_immediate_enabled = "true";
google_ad.line1 = "Bluetooth Jewelry by CUFF"; 
google_ad.line2 = "Stay healthy, stay connected and"; 
google_ad.line3 = "stay safe with Smart Jewelry"; 
google_ad.regionname = ""; 
google_ads[0] = google_ad; 
google_ad = {}; 
google_ad.n = 2; 
google_ad.type = "text"; 
google_ad.bidtype = "CPC"; 
google_ad.targeting_type = "contextual"; 
google_ad.url = "http://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=CXlZsG4p-VNTcMsnVfJacgOgBkNyk-gLY5MbCJcCNtwEQAiDI7_0VKAZgyQagAYjfpvgDyAEBqAMBqgS8AU_Q4oHlf1rZJ_NTK9I-MJMWnVs3HUyYzDSzL-6kz4UuhLOFCTA3hAC52hk50Lqtt35bERGuWwzlx6kPYqqML72WfV2dICkpixOc5fCdCJ1hZCw_0-I1WYiBhuPC2iy55k8d0w-sU-hfk9wV9aTLvJqkE8YF6P5ZwVWWNmJ5gZiGwVm2kgimsRj4MDWkYVXUz4-0VbUEEsEC82WoqJbD-xsg7SoLQ7Q3rlJcvXjM_nrAfT3EM8r6d-8mBHQLiAYBgAfgoNkHohM-CjdABVIICgYSBAgBEAJor9uErUZyIxIhEICz-aULIAIoAjgCQMj2_yJYAmj-__________8BgAEBGgMKATA&amp;num=2&amp;cid=5Gi1s3toe9u7GP3DKFQRi2tx&amp;sig=AOD64_3qdBNwwgGCQzuf-GA9lXMMnWaq1g&amp;client=ca-macys_js&amp;adurl=http://tracking.voltagesearch.com/172-2972682-1-t14455438-10921-13289-3354957/"; 
google_ad.visible_url = "www.gourmetgiftbaskets.com"; 
google_ad.log_info = "BUqUFG4p-VNTcMsnVfJacgOgBAMP-np7AAQAAEAE4AcgBAagTgAE";
google_ad.activeview_js_immediate_enabled = "true";
google_ad.line1 = "Gourmet Gift Baskets"; 
google_ad.line2 = "Unique Gift Baskets from $24.99."; 
google_ad.line3 = "Satisfaction Guaranteed. Buy Today!"; 
google_ad.regionname = ""; 
google_ads[1] = google_ad; 
google_ad = {}; 
google_ad.n = 3; 
google_ad.type = "text"; 
google_ad.bidtype = "CPC"; 
google_ad.targeting_type = "contextual"; 
google_ad.url = "http://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=CQ7KSG4p-VNTcMsnVfJacgOgBmJO5mAOo_YCxJcCNtwEQAyDI7_0VKAZgyQagAcaiwP8DyAEBqAMBqgS7AU_QgpL_f1vZJ_NTK9I-MJMWnVs3HUyYzDSzL-6kz4UuhLOFCTA3hAC52hk50Lqtt35bERGuWwzlx6kPYqqML72WfV2dICkpixOc5fCdCJ1hZCw_0-I1WYiBhuPC2iy55k8d0w-sU-hfk9wV9aTLvJqkE8YF6P5ZwVWWNmJ5gZiGwVm2kgimsRj4MDX8GGLhz4-0VbUEEsEC82WoqJbD-xsg7SoLQ7Q3rlJcvXjM_nrAfT3EM8r6d-8cMaiIBgGAB6LdPw&amp;num=3&amp;cid=5Gi1s3toe9u7GP3DKFQRi2tx&amp;sig=AOD64_3UyqpYApzpSUUEOyHk-CmblxkZAw&amp;client=ca-macys_js&amp;adurl=http://www.PersonalizationMall.com/Store.aspx%3Fstoreid%3D9%26did%3D23826%26wordID%3D9939198920"; 
google_ad.visible_url = "www.personalizationmall.com"; 
google_ad.log_info = "BUqUFG4p-VNTcMsnVfJacgOgBAMP-np7AAQAAEAE4AcgBAagTgAE";
google_ad.activeview_js_immediate_enabled = "true";
google_ad.line1 = "Unique Christmas Gifts"; 
google_ad.line2 = "Personalized Gifts For The Holidays"; 
google_ad.line3 = "With Free Engraving \x26amp; Fast Delivery"; 
google_ad.regionname = ""; 
google_ads[2] = google_ad; 
google_ad = {}; 
google_ad.n = 4; 
google_ad.type = "text"; 
google_ad.bidtype = "CPC"; 
google_ad.targeting_type = "contextual"; 
google_ad.url = "http://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=Cesa2G4p-VNTcMsnVfJacgOgBvZXB6gedmrKyqwHAjbcBEAQgyO_9FSgGYMkGoAHTufnEA8gBAagDAaoEvAFP0KL2_X9c2SfzUyvSPjCTFp1bNx1MmMw0sy_upM-FLoSzhQkwN4QAudoZOdC6rbd-WxERrlsM5cepD2KqjC-9ln1dnSApKYsTnOXwnQidYWQsP9PiNVmIgYbjwtosueZPHdMPrFPoX5PcFfWky7yapBPGBej-WcFVljZieYGYhsFZtpIIprEY-DA1yVto8M-PtFW1BBLBAvNlqKiWw_sbIO0qC0O0N65SXL14zP56wH09xDPK-nfvK01dOogGAYAHlcaGOw&amp;num=4&amp;cid=5Gi1s3toe9u7GP3DKFQRi2tx&amp;sig=AOD64_3Fu-_ptHDhBQopIPS7ZP1hrAilQA&amp;client=ca-macys_js&amp;adurl=http://www.wayfair.com/gateway.php%3Frefid%3DGX45991827933.Macys~%26image%3D10628675%26position%3Dnone%26network%3Dd%26pcrid%3D45991827933%26device%3Dc%26aceid%3D%26placement%3Dwww1.macys.com%26gateway%3D1"; 
google_ad.visible_url = "www.wayfair.com"; 
google_ad.log_info = "BUqUFG4p-VNTcMsnVfJacgOgBAMP-np7AAQAAEAE4AcgBAagTgAE";
google_ad.activeview_js_immediate_enabled = "true";
google_ad.line1 = "Wayfair: Official Site"; 
google_ad.line2 = "A Zillion things Home. 7 Million"; 
google_ad.line3 = "Satisfied Customers and Counting!"; 
google_ad.regionname = ""; 
google_ads[3] = google_ad; 
google_ad = {}; 
google_ad.n = 5; 
google_ad.type = "text"; 
google_ad.bidtype = "CPC"; 
google_ad.targeting_type = "contextual"; 
google_ad.url = "http://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=CiByvG4p-VNTcMsnVfJacgOgBipmdygfSl7qLnAHAjbcBEAUgyO_9FSgGYMkGoAH44JnlA8gBAagDAaoEuQFP0OKO_n9d2SfzUyvSPjCTFp1bNx1MmMw0sy_upM-FLoSzhQkwN4QAudoZOdC6rbd-WxERrlsM5cepD2KqjC-9ln1dnSApKYsTnOXwnQidYWQsP9PiNVmIgYbjwtosueZPHdMPrFPoX5PcFfWky7yapBPGBej-WcFVljZieYGYhsFZtpIIpvkYC3Pfdm2Zj8-PjFW1ag_BEAZmrF2VRw4YoBgpC7anMVtB2kodTAkf04g-19PMIBlK3ogGAYAH4ozLHw&amp;num=5&amp;cid=5Gi1s3toe9u7GP3DKFQRi2tx&amp;sig=AOD64_0nY31y69KyVKE5ZCOIEXcpa4UK6Q&amp;client=ca-macys_js&amp;adurl=http://501.xg4ken.com/media/redir.php%3Fprof%3D23%26camp%3D39782%26affcode%3Dcr2544803%26k_inner_url_encoded%3D1%26cid%3D41822620306%7C4026358%7Cwomens%2520coat%26mType%3D%26networkType%3Dcontent%26kdv%3Dc%26url%5B%5D%3Dhttp%253A%252F%252Fwww.sears.com%252Ffashion%252Fdap-120000000220771%253Fsid%253DISx20140327xNonBrand%2526psid%253D23x2530593%2526knshCrid%253D4026358%2526k_clickID%253D_kenshoo_clickid_"; 
google_ad.visible_url = "www.sears.com/Free-Shipping"; 
google_ad.log_info = "BUqUFG4p-VNTcMsnVfJacgOgBAMP-np7AAQAAEAE4AcgBAagTgAE";
google_ad.activeview_js_immediate_enabled = "true";
google_ad.line1 = "Women\x26#39;s Coats at Sears\x26#174;"; 
google_ad.line2 = "Enjoy Free Shipping at Sears\x26#174; on"; 
google_ad.line3 = "Orders Over $59. Buy Now to Save!"; 
google_ad.regionname = ""; 
google_ads[4] = google_ad; 
google_ad = {}; 
google_ad.n = 6; 
google_ad.type = "text"; 
google_ad.bidtype = "CPC"; 
google_ad.targeting_type = "contextual"; 
google_ad.url = "http://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=CaWHRG4p-VNTcMsnVfJacgOgB6Y3GswTBkbyEkgHAjbcBEAYgyO_9FSgGYMkGoAHpn8n-A8gBAagDAaoEvgFP0NL00X9e2SfzUyvSPjCTFp1bNx1MmMw0sy_upM-FLoSzhQkwN4QAudoZOdC6rbd-WxERrlsM5cepD2KqjC-9ln1dnSApKYsTnOXwnQidYWQsP9PiNVmIgYbjwtosueZPHdMPrFPoX5PcFfWky7yapBPGBej-WcFVljZieYGYhsFZtpIIpskb-Hg1PU2YOuFw21W1PBLBbO5lul2Vxw4YpBgpi7a3N1tBWkhrSgkfQIpY18bJ6Zfp_gmssgsTiAYBgAf_37YB&amp;num=6&amp;cid=5Gi1s3toe9u7GP3DKFQRi2tx&amp;sig=AOD64_2pjrCvzNK1IIYYo_6JhIHolu6rQQ&amp;client=ca-macys_js&amp;adurl=http://www.donateforacause.org/index.php%3Ftcode%3DSCM-0005"; 
google_ad.visible_url = "www.donateforacause.org"; 
google_ad.log_info = "BUqUFG4p-VNTcMsnVfJacgOgBAMP-np7AAQAAEAE4AcgBAagTgAE";
google_ad.activeview_js_immediate_enabled = "true";
google_ad.line1 = "Donate Your Timeshare Now"; 
google_ad.line2 = "A credible and cost effective way"; 
google_ad.line3 = "out of your unwanted timeshare."; 
google_ad.regionname = ""; 
google_ads[5] = google_ad; 
google_info.feedback_url = "https://www.google.com/url?ct\x3dabg\x26q\x3dhttps://www.google.com/adsense/support/bin/request.py%3Ftrunc%3D1%26contact%3Dabg_afc%26url%3Dhttp://www.macys.com/shop/product/motherhood-maternity-long-sleeve-v-neck-top%253FID%253D1651335%2526CategoryID%253D66718%26gl%3DUS%26hl%3Den%26client%3Dca-macys_js%26ai0%3DCrxGFG4p-VNTcMsnVfJacgOgBi5Wm8QXD_p6ewAHAjbcBEAEgyO_9FSgGYMkGoAH1wpTQA8gBAagDAaoEvAFP0MKXwX9Z2SfzUyvSPjCTFp1bNx1MmMw0sy_upM-FLoSzhQkwN4QAudoZOdC6rbd-WxERrlsM5cepD2KqjC-9ln1dnSApKYsTnOXwnQidYWQsP9PiNVmIgYbjwtosueZPHdMPrFPoX5PcFfWky7yapBPGBej-WcFVljZieYGYhsFZtpIIprEY-DA1pzwM9M-PtFW1BBLBAvNlqKiWw_sbIO0qC0O0N65SXL14zP56wH09xDPK-nfvBQt7M4gGAYAH87zrLw%26ai1%3DCXlZsG4p-VNTcMsnVfJacgOgBkNyk-gLY5MbCJcCNtwEQAiDI7_0VKAZgyQagAYjfpvgDyAEBqAMBqgS8AU_Q4oHlf1rZJ_NTK9I-MJMWnVs3HUyYzDSzL-6kz4UuhLOFCTA3hAC52hk50Lqtt35bERGuWwzlx6kPYqqML72WfV2dICkpixOc5fCdCJ1hZCw_0-I1WYiBhuPC2iy55k8d0w-sU-hfk9wV9aTLvJqkE8YF6P5ZwVWWNmJ5gZiGwVm2kgimsRj4MDWkYVXUz4-0VbUEEsEC82WoqJbD-xsg7SoLQ7Q3rlJcvXjM_nrAfT3EM8r6d-8mBHQLiAYBgAfgoNkHohM-CjdABVIICgYSBAgBEAJor9uErUZyIxIhEICz-aULIAIoAjgCQMj2_yJYAmj-__________8BgAEBGgMKATA%26ai2%3DCQ7KSG4p-VNTcMsnVfJacgOgBmJO5mAOo_YCxJcCNtwEQAyDI7_0VKAZgyQagAcaiwP8DyAEBqAMBqgS7AU_QgpL_f1vZJ_NTK9I-MJMWnVs3HUyYzDSzL-6kz4UuhLOFCTA3hAC52hk50Lqtt35bERGuWwzlx6kPYqqML72WfV2dICkpixOc5fCdCJ1hZCw_0-I1WYiBhuPC2iy55k8d0w-sU-hfk9wV9aTLvJqkE8YF6P5ZwVWWNmJ5gZiGwVm2kgimsRj4MDX8GGLhz4-0VbUEEsEC82WoqJbD-xsg7SoLQ7Q3rlJcvXjM_nrAfT3EM8r6d-8cMaiIBgGAB6LdPw%26ai3%3DCesa2G4p-VNTcMsnVfJacgOgBvZXB6gedmrKyqwHAjbcBEAQgyO_9FSgGYMkGoAHTufnEA8gBAagDAaoEvAFP0KL2_X9c2SfzUyvSPjCTFp1bNx1MmMw0sy_upM-FLoSzhQkwN4QAudoZOdC6rbd-WxERrlsM5cepD2KqjC-9ln1dnSApKYsTnOXwnQidYWQsP9PiNVmIgYbjwtosueZPHdMPrFPoX5PcFfWky7yapBPGBej-WcFVljZieYGYhsFZtpIIprEY-DA1yVto8M-PtFW1BBLBAvNlqKiWw_sbIO0qC0O0N65SXL14zP56wH09xDPK-nfvK01dOogGAYAHlcaGOw\x26usg\x3dAFQjCNHSzwpiKQxtqNkw4n9AKQCPlxzNCg";
var google_attribution_text = "AdChoices";
var google_is_rtl = false;
if (window.google_ad_request_done) {
google_ad_request_done(google_ads);
}
if (window.google_radlink_request_done) {
google_radlink_request_done(google_radlinks);
}
}