
(window.callback15828=window.callback15828||Bootstrapper.new_fArray()).add(function(){Bootstrapper.setCurrentRuleId(15828);Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(81342);if(typeof console!='undefined'&&console.log){console.log('Ensighten rule 81342: [prod]dotcom global scode Runa Offer Tracking v2.');}
var s_runaTrackingGlobal=function(){function omniRunaPromoOfferTracking(){if((typeof $('.eddie-bubble')!='undefined'&&$('.eddie-bubble').length>0&&$('.eddie-bubble').is(':visible'))||($('#eddieQSText').length>0&&$('#eddieQSText').is(':visible'))){var offerValue="";var productString="";var perfectshipping="";if($('#eddieQSText').length>0&&$('#eddieQSText').is(':visible')){perfectshipping=$('#eddieQSText').text().trim();perfectshipping=perfectshipping.match(/[A-Za-z]{3},[A-Za-z0-9\s]+/g)[0];if($('.eddieQS').is(':visible')){perfectshipping="Quick Ship "+perfectshipping;}
perfectshipping=perfectshipping.replace(/,/,'');addEvents("event50");s.linkTrackEvents="event50";productString=";"+productSku+";;;";}
s.linkTrackVars="products,eVar72,events";if(typeof $('#eddie_discount')!='undefined'&&$('#eddie_discount').text().length>0){if(typeof console!='undefined'&&console.log){console.log('Runa Offer Tracking Rule Execution Started.');}
var productPrice=$('.finalPrice').text();productPrice=productPrice.match(/[0-9|.]+/);productPrice=productPrice[0];productPrice=parseFloat(productPrice);var finaldiscountedPrice=$('#eddie_price').text();finaldiscountedPrice=finaldiscountedPrice.match(/[0-9|.]+/);finaldiscountedPrice=finaldiscountedPrice[0];finaldiscountedPrice=parseFloat(finaldiscountedPrice);var savings=parseFloat(productPrice-finaldiscountedPrice).toFixed(2);var offer=$('.eddie-bubble').find('#header-text').text().trim();if(savings>0){addEvents("event99,event100");if(s.linkTrackEvents){s.linkTrackEvents=s.linkTrackEvents+",event99,event100";}else{s.linkTrackEvents="event99,event100";}
offerValue="Save "+offer.match(/[0-9|%]+/)[0];productString=";"+productSku+";;;event100="+savings;}}
s.products=productString+";eVar72="+s.prop3+"-"+offerValue+"-"+perfectshipping;s.tl(true,'o','Runa Offer Displayed');if(typeof console!='undefined'&&console.log){console.log('Runa Offer Tracking Information Sent.');}}}
try{var startTime=new Date().getTime();var iterations=1;var interval=setInterval(function(){if(typeof s!='undefined'&&($('.eddie-bubble').length>0||$('#eddieQSText').length>0)){if(typeof console!='undefined'&&console.log){console.log('[AFTER DOM COMPLETE]runa loaded after ['+(new Date().getTime()-startTime)+'ms] over ['+iterations+']intervals');}
clearInterval(interval);omniRunaPromoOfferTracking();s.events="";}else if(iterations<100){iterations++;}else{clearInterval(interval);if(typeof console!='undefined'&&console.log){console.log('runa failed to load after ['+(new Date().getTime()-startTime)+'ms] over ['+iterations+']intervals');}}},10);}catch(e){console.log(e);}};window.s_runaTrackingGlobal=s_runaTrackingGlobal;s_runaTrackingGlobal();}catch(e){Bootstrapper.reportException(e);}});});(window.callback15828=window.callback15828||Bootstrapper.new_fArray()).add(function(){Bootstrapper.setCurrentRuleId(15828);Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(81371);if(typeof console!='undefined'&&console.log){console.log('Ensighten rule 81371: Runa Offer Tracking.');}
function omniRunaPromoOfferTracking(){if($('#runa-bubble-0').length>0){if(typeof console!='undefined'&&console.log){console.log('Runa Offer Tracking Rule Execution Started.');}
var savings=runa_client.promo().savings["pre-abandonment"]["total-savings"];var offer=$('#runa-bubble-0').find('#header-text').text();var productString=";"+skuId+";;;event100="+savings;if(parseInt(savings,10)>0){s.linkTrackVars="eVar72,events,products";s.linkTrackEvents="event99,event100";s.eVar72=offer;s.events="event99,event100";s.products=productString;s.tl(true,'o','Runa Offer Displayed');if(typeof console!='undefined'&&console.log){console.log('Runa Offer Tracking Information Sent.');}}}}
try{var startTime=new Date().getTime();var iterations=1;var interval=setInterval(function(){if($('#runa-bubble-0').length>0){if(typeof console!='undefined'&&console.log){console.log('[AFTER DOM COMPLETE]s loaded after ['+(new Date().getTime()-startTime)+'ms] over ['+iterations+']intervals');}
clearInterval(interval);omniRunaPromoOfferTracking();}else if(iterations<100){iterations++;}else{clearInterval(interval);if(typeof console!='undefined'&&console.log){console.log('s failed to load after ['+(new Date().getTime()-startTime)+'ms] over ['+iterations+']intervals');}}},10);}catch(e){logMediativeConsoleMessage(e);}}catch(e){Bootstrapper.reportException(e);}});});try{Bootstrapper.setCurrentRuleId(76620);Bootstrapper.RMF=(function(){var _private={tests:[['C',98],['D',2]],getProfile:function(x){if(typeof x=='undefined'){var c=document.cookie.split('; '),i;for(i=0,l=c.length;i<l;i++){c[i]=c[i].split('=');if(c[i][0]=='_ens_R'){return c[i][1];}}}else if(typeof x=='object'&&x['_ens_R']){return x['_ens_R'];}
return false;},callProfile:function(p){var temp=window.ensightenOptions;window.ensightenOptions={client:"uber",clientId:123,ns:"Bootstrapper",nexus:"nexus.ensighten.com"};var data={profile:p};var rand=Math.random()*("1E"+(10*Math.random()).toFixed(0)),u=window.location.href;if(typeof data==='object'){var i;for(i in data){var c=~u.indexOf("#")?u.slice(u.indexOf("#"),u.length):"",u=u.slice(0,c.length?u.length-c.length:u.length),u=u+(~u.indexOf("?")?"&":"?");for(k in data)u+=k+"="+data[k]+"&";u=u.slice(0,-1)+c;break;}}
u=escape(u);Bootstrapper.insertScript('//nexus.ensighten.com/staplesu/serverComponent.php?ClientID=479&PageID='+u);},storeProfile:function(p){try{var host=window.location.hostname.match(/[-\w]+\.(?:[-\w]+\.xn--[-\w]+|[-\w]{3,}|[-\w]+\.[-\w]{2})$/i)[0];}catch(e){var host=window.location.hostname;}
document.cookie='_ens_R'+"="+escape(p)+';path=/;domain='+host;var i=document.createElement('iframe');i.style.display='none';Bootstrapper.scrfSrc='//scarf.ensighten.com/x?key=_ens_R&value='+p;Bootstrapper.bindDOMParsed(function(){return function(){Bootstrapper.insertScript(Bootstrapper.scrfSrc);};});},genProfile:function(){var r=Math.round(Math.random()*100),t={},l=0,k;for(k in _private.tests){_private.tests[k][1]+=l;l=_private.tests[k][1];}
var tests=_private.tests,i;tests.unshift(['-',0]);for(i=1;i<tests.length;i++){if(i==tests.length-1||(r>=tests[i-1][1]&&r<tests[i][1])){var p=tests[i][0];break;}}
console.log('gen '+p);_private.storeProfile(p);return p;}},_public={init:function(p){if(typeof p=='undefined'){var p=_private.getProfile();if(!p){return Bootstrapper.insertScript('//scarf.ensighten.com/o?callback=Bootstrapper.RMF.init&rand='+Math.random());}}else{var p=_private.getProfile(p);if(!p){var p=_private.genProfile();}}
var fg=Bootstrapper.getQueryParam('ens_Force');if(fg&&/a|b/.test(fg)){p=fg;}
console.log(p);_private.callProfile(p);}};return _public;})();if(typeof console!='undefined'&&console.log){console.log('Ensighten rule 51038: Uber Test Retargeting Framework');}
Bootstrapper.RMF.init();;}catch(e){Bootstrapper.reportException(e);};