(function(window,document){'use strict';function q(e,g){var c,f,h,l,m="navigationStart unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" ");this.window=e;this.document=g;this.D=[];this.h=4E3;this.H=1E4;this.V=function(){return c};this.W=function(){return g};this.za=
function(a,b){for(var d=[],c=0;100>c&&(0<a.length||0<b.length);)0<a.length&&d.push(a.shift()),0<b.length&&d.push(b.shift()),c+=1;return d};this.w=function(){return(new Date).getTime()};this.q=function(a,b){return setTimeout(a,b)};this.g=function(a){clearTimeout(a)};this.Da=function(){return function(a){var b="",d,c,f,e,g,h,n=0;a=a.replace(/\r\n/g,"\n");c="";for(f=0;f<a.length;f+=1)e=a.charCodeAt(f),128>e?c+=String.fromCharCode(e):(127<e&&2048>e?c+=String.fromCharCode(e>>6|192):(c+=String.fromCharCode(e>>
12|224),c+=String.fromCharCode(e>>6&63|128)),c+=String.fromCharCode(e&63|128));for(a=c;n<a.length;)d=a.charCodeAt(n),n+=1,c=a.charCodeAt(n),n+=1,f=a.charCodeAt(n),n+=1,e=d>>2,d=(d&3)<<4|c>>4,g=(c&15)<<2|f>>6,h=f&63,isNaN(c)?g=h=64:isNaN(f)&&(h=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(h);
return b}}();this.L=function(a){var b=/radar_(tags|impact)_(\w{3,})/i,d;if(("radar_tags_"===a.slice(0,11)||"radar_impact_"===a.slice(0,13))&&(b=b.exec(a))&&3===b.length){try{d=JSON.stringify(e[a])}catch(c){return null}return b[2]+":"+this.Da(d)}return null};this.n=function(){var a,b,d=[];if(!e.JSON||!e.JSON.stringify)return"1";for(a in e)b=null,void 0!==e.hasOwnProperty?e.hasOwnProperty(a)&&(b=this.L(a)):void 0!==e[a]&&(b=this.L(a)),b&&d.push(b);return 1>d.length?"0":d.join("@")};this.l=function(a){var b=
g.getElementById("cdx");b||(b=g.createElement("div"),b.id="cdx",g.body.appendChild(b));b.appendChild(a)};this.M=function(){return Math.random()};this.Y=function(a){return Math.floor(this.M()*(a-0+1))+0};this.O=function(a){var b,d,c=[];b=b||"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(d=0;d<a;d+=1)c.push(b.charAt(this.Y(b.length-1)));return c.join("")};this.ua=function(a){return/http:/i.test(a)?"http":/https:/i.test(a)?"https":/\/\//.test(a)?e.location.protocol.replace(":",
""):null};this.sa=function(){var a=[],b=c.p.p,d;b.a&&b.a.a?a.push({a:"cold",b:1,f:!!b.d,t:b.a.a.t,u:b.a.a.u}):b.b&&b.b.a&&a.push({a:"cold",b:1,f:!!b.d,t:b.b.a.t,u:b.b.a.u});b.d&&a.push({a:"uni",t:b.d.t,u:b.d.u});b.a?(b.a.b&&a.push({a:"rtt",b:0,f:!!b.d,t:b.a.b.t,u:b.a.b.u}),b.a.c&&a.push({a:"kbps",b:14,f:!!b.d,t:b.a.c.t,u:b.a.c.u})):b.b&&(b.b.b&&a.push({a:"rtt",b:0,f:!!b.d,t:b.b.b.t,u:b.b.b.u}),b.b.c&&a.push({a:"kbps",b:14,f:!!b.d,t:b.b.c.t,u:b.b.c.u}));b.c&&(d=this.ua(b.c.u))&&("http:"!==this.window.location.protocol&&
"https"!==d||a.push({a:"custom",b:2,f:!!b.d,t:b.c.t,u:b.c.u}));c.C=a};this.ta=function(a){var b=[];a.connect&&b.push({a:"cold",b:1,f:!1,t:1,u:a.connect});a.response_time&&b.push({a:"rtt",b:0,f:!1,t:1,u:a.response_time});a.kbps&&b.push({a:"kbps",b:14,f:!1,t:1,u:a.kbps});c.C=b};this.ka=function(a){return"uni"===a?[c.requestor.zoneId,c.requestor.customerId,c.p.z,c.p.c,c.p.i,this.O(8),c.requestor.requestSignature].join("-"):[a,c.requestor.zoneId,c.requestor.customerId,c.p.z,c.p.c,c.p.i,c.requestor.transactionId,
c.requestor.requestSignature].join("-")};this.k=function(){var a="",b;!1!==c.a&&(a="?rnd=",-1<f.u.indexOf("?",0)&&(a="&rnd="),b="uni"===f.a?"uni":f.b,a+=this.ka(b));return f.u+a};this.J=function(a,b){var d=/(\d+)kb\./i.exec(b);return!d||2>d.length?0:Math.floor(8E3*parseInt(d[1],10)/a)};this.I=function(a){var b,d,e;c.c?(b=c.c.a,d=c.c.b,e=c.c.c):(b=c.p.z,d=c.p.c,e=c.p.i);r(this,"sendSuccessReport",{providerOwnerZoneId:b,providerOwnerCustomerId:d,providerId:e,probeId:f.b,resultCode:0,value:a});a=[c.requestor.domains.report,
"f1",c.requestor.requestSignature,b,d,e,f.b,0,a,h||"0",this.n()];s(this,"//"+a.join("/"),this.F())};this.F=function(){var a=this;return function(){a.o()}};this.ea=function(){var a=this;return function(){a.A()}};this.j=function(a){var b,d,e;c&&f&&(c.c?(b=c.c.a,d=c.c.b,e=c.c.c):(b=c.p.z,d=c.p.c,e=c.p.i),r(this,"sendErrorReport",{providerOwnerZoneId:b,providerOwnerCustomerId:d,providerId:e,probeId:f.b,resultCode:a,value:0}),a=[c.requestor.domains.report,"f1",c.requestor.requestSignature,b,d,e,f.b,a,
0,h||"0",this.n()],s(this,"//"+a.join("/"),this.ea()))};this.ya=function(a){return!0===a.f&&null===h};this.K=function(a,b,d){a===f&&(b=d.call(null,b),0<b&&b<=this.h?(d=b,14===a.b&&(d=this.J(b,a.u)),this.ya(a)?(l={probe:a,measurement:d},this.o()):this.I(d)):this.j(1))};this.ma=function(a,b,d){var c=this;return function(){a.c||(c.g(a.e),c.K(a,b,d))}};this.G=function(a){var b,d;b=g.createElement("script");b.async=!0;b.src=this.k();f.c=!1;f.d="loading";d=this.w();void 0!==b.onreadystatechange?b.onreadystatechange=
function(b,c){var e=!1;return function(){e||"loaded"!==this.readyState&&"complete"!==this.readyState||(e=!0,c!==f||c.c||(b.g(c.e),b.K(c,d,a)))}}(this,f):b.onload=this.ma(f,d,a);b.onerror=function(a,b){return function(){b===f&&(a.g(b.e),b.c=!0,b.d="error",a.j(4))}}(this,f);f.e=this.q(this.v(),this.h);e.radar.stoppedAt=e.cedexis.radar.stopped_at=null;this.l(b)};this.N=function(){var a=this;return function(b){return a.w()-b}};this.v=function(a){var b=this,d=f;return function(){var c=1;d.c||(a&&a.call(null),
d===f&&("loaded"===d.d&&(c=4),d.c=!0,d.d="timeout",b.j(c)))}};this.aa=function(){var a=this;return function(){h="2";a.B()}};this.ca=function(){var a=this,b=f,d;return d=function(){a.g(b.e);this.removeEventListener("load",d,!1);b.c||(b.d="loaded")}};this.da=function(a,b){return function(){a.removeEventListener("load",b,!1)}};this.ba=function(){var a=this,b=f,d;return d=function(g){var k,p;if(b===f){try{k=JSON.parse(g.data)}catch(l){}if(k&&k.source&&"dsa"===k.source&&"l"!==k.s&&"s"===k.s){if(!b.c){p=
k.m.responseEnd-k.m.domainLookupStart;g=[c.requestor.domains.report,"f1",c.requestor.requestSignature,k.p.z,k.p.c,k.p.i,k.m.probe_id];var m=0;a.h<p&&(m=1,p=0);g.push(m);g.push(p);r(a,"sendDsaReport",{providerOwnerZoneId:k.p.z,providerOwnerCustomerId:k.p.c,providerId:k.p.i,probeId:k.m.probe_id,resultCode:m,value:p});g.push(h||"0");g.push(a.n());g.push(k.m.ciphertext);s(a,"//"+g.join("/"),a.F())}e.removeEventListener("message",d,!1)}}}};this.Q=function(){var a=g.createElement("iframe"),b=this.k(),d=
this.ca();e.addEventListener("message",this.ba(),!1);a.addEventListener("load",d,!1);a.src=b;a.style.display="none";f.c=!1;f.d="loading";f.e=this.q(this.v(this.da(a,d)),this.h);this.l(a)};this.S=function(){this.G(function(a){return e.radar.stoppedAt?e.radar.stoppedAt.getTime()-a:e.cedexis.radar.stopped_at?e.cedexis.radar.stopped_at.getTime()-a:null})};this.fa=function(a,b){var d=this;return function(){d.g(a.e);d.I(d.w()-b)}};this.P=function(){var a=this.W().createElement("iframe"),b=this.w();a.src=
this.k();a.style.display="none";f.c=!1;f.d="loading";a.onload=this.fa(f,b);f.e=this.q(this.v(),this.h);this.l(a)};this.ha=function(a){var b=this;return function(){var d,c,f,g,h;b.g(a.e);if(!0!==a.c)for(h=14===a.b,d=e.performance.getEntriesByType("resource"),g=0;g<d.length;g+=1)c=d[g],c.name===this.src&&(c=0<c.requestStart?h?Math.round(c.responseEnd-c.requestStart):Math.round(c.responseStart-c.requestStart):Math.round(c.duration),0<c&&c<=b.h?(f=c,h&&(f=b.J(c,a.u)),b.I(f)):b.j(1))}};this.ga=function(a){var b=
this;return function(){b.g(a.e);a.c=!0;a.d="error";b.j(4)}};this.R=function(){var a;a=new Image;a.onload=this.ha(f);a.onerror=this.ga(f);f.c=!1;f.d="loading";f.e=this.q(this.v(),this.h);a.src=this.k()};this.B=function(){var a;l?(a=[c.requestor.domains.report,"f1",c.requestor.requestSignature,c.p.z,c.p.c,c.p.i,l.probe.b,0,l.measurement,h||"0",this.n()],s(this,"//"+a.join("/"),this.F())):this.o()};this.oa=function(a){var b=this;return function(d){f!==a||c.p.i!==d.id||a.c||(a.d="loaded",h=d.node,b.B())}};
this.qa=function(){return function(){}};this.pa=function(){return function(){}};this.Ca=function(){var a,b;a=g.createElement("script");b=this.k();e.cdx=e.cdx||{};e.cdx.s=e.cdx.s||{};e.cdx.s.b=this.oa(f);a.onload=this.qa();a.onerror=this.pa();f.c=!1;f.d="loading";a.type="text/javascript";a.async=!0;a.src=b;this.l(a)};this.na=function(){var a=this;return function(b){var d,e,g;if(c&&f){try{d=JSON.parse(b.data)}catch(l){}d&&"uni"===d.source&&(b=parseInt(d.p.z,10),e=parseInt(d.p.c,10),g=parseInt(d.p.i,
10),g===c.p.i&&e===c.p.c&&b===c.p.z&&d.r.z===c.r.z&&d.r.c===c.r.c&&(a.g(f.e),"l"===d.s?f.d="loaded":-1<"es".indexOf(d.s)&&("e"===d.s?(f.d="error",h="2"):"s"===d.s&&(h=d.node_id),a.B())))}}};this.U=function(){return"function"===typeof e.postMessage&&"function"===typeof e.addEventListener};this.Ba=function(){var a;this.U()?(f.c=!1,f.d="loading",a=g.createElement("iframe"),a.style.display="none",a.src=this.k(),f.e=this.q(this.aa(),this.h),this.l(a)):(h="1",this.B())};this.X=function(a){a=a.slice(a.lastIndexOf("/")+
1);var b=[/cdx10b/,/rdr12/,/radar\.js/,/r\d+(-\d+kb)?\.js/i,/r\d+\w+(-\d+kb)?\.js/i],c;if("d17.html"===a)return 4;for(c=0;c<b.length;c+=1)if(b[c].test(a))return 1;return/\.js(\?)?/i.test(a)?5:/\.(ico|png|bmp|gif|jpg|jpeg)(\?)?/i.test(a)?2:/\.(htm(l)?)(\?)?/i.test(a)?3:null};this.Aa=function(){var a;if(f)switch(f.t){case 1:this.S();break;case 2:this.R();break;case 3:this.P();break;case 4:this.Q();break;case 5:this.G(this.N());break;case 6:a=this.X(f.u);switch(a){case 1:this.S();break;case 2:this.R();
break;case 3:this.P();break;case 4:this.Q();break;case 5:this.G(this.N());break;default:this.j(5)}break;case 7:this.Ba();break;case 8:this.Ca();break;default:this.j(6)}};this.o=function(){c&&(0<c.C.length?(f=c.C.shift(),this.Aa()):(c=null,this.A()))};this.A=function(){c=f=null;0<this.D.length?(l=h=null,c=this.D.shift(),r(this,"measureProvider",{providerOwnerZoneId:c.p.z,providerOwnerCustomerId:c.p.c,providerId:c.p.i}),c.p.source_url?this.va():(this.sa(),this.o())):r(this,"radarSessionFinished")};
this.va=function(){var a,b,d;e.XMLHttpRequest&&(b=new e.XMLHttpRequest)&&(a=c.p.source_url,d=Math.ceil(99999999*this.M()),a=0>a.indexOf("?",0)?a+("?rnd="+d):a+("&rnd="+d),b.open("GET",a,!0),b.onreadystatechange=this.la(),b.send())};this.la=function(){var a=this,b=c;return function(){var d;200===this.status&&4===this.readyState&&(d=JSON.parse(this.responseText),b===c&&(a.ta(d),0<c.C.length?a.o():a.A()))}};this.xa=function(a){var b,c,e;if(b=(this.window.performance||{}).timing){c=[a.domains.report,
"n1",0];for(e=0;e<m.length;e+=1){var f=b[m[e]];c.push(void 0===f?0:f)}c.push(a.requestSignature);c.push(this.n());c.push(this.Z());b.connectEnd<b.connectStart||b.domainLookupEnd<b.domainLookupStart||b.domComplete<b.domLoading||b.fetchStart<b.navigationStart||b.loadEventEnd<b.loadEventStart||b.loadEventEnd<b.navigationStart||b.responseEnd<b.responseStart||b.responseStart<b.requestStart||s(this,"//"+c.join("/"),this.ja(a))}else t(this,a)};this.ja=function(a){var b=this;return function(){t(b,a)}};this.Z=
function(){var a=0;e.chrome&&e.chrome.loadTimes?(a=e.chrome.loadTimes(),a=Math.round(1E3*a.firstPaintTime)):e.performance&&e.performance.timing&&e.performance.timing.ra&&(a=Math.round(e.performance.timing.ra));return a};this.ia=function(a){var b=[],c=[],e;if(this.window.location&&this.window.location.protocol)return e="https:"===this.window.location.protocol?"s":"i",b.push("i1"),b.push(this.T),b.push(18),b.push(2),b.push(a.zoneId),b.push(a.customerId),b.push(a.transactionId.toString(10)),b.push(e),
b=b.join("-"),c.push(b+".init."+a.domains.init),c.push("i1"),c.push(Math.floor((new Date).getTime()/1E3).toString(10)),c.push(a.transactionId.toString(10)),c.push("xml"),c="//"+c.join("/"),c+("?seed="+b)};this.$=function(a,b){var c;for(c=0;c<a.length;c+=1)a[c].requestor=b;this.D=this.za(this.D,a);this.V()||this.A()};this.wa=function(){var a=u;a.runCalledAt=(new Date).getTime();v({a:this.ia(a),b:w(this,a),d:this.H})};"function"===typeof e.addEventListener&&e.addEventListener("message",this.na(),!1)}
window.cedexis.callbacks=window.cedexis.callbacks||[];q.prototype.T="j0";function r(e,g,c){for(var f=e.window.cedexis.callbacks,h=f.length;h--;)"function"===typeof f[h]&&f[h].call(e.window,g,c)};q.prototype.T="j1";function v(e){var g=new XMLHttpRequest;e.c=e.c||{};if(g)try{g.open("GET",e.a,!0),g.onreadystatechange=function(){return function(){200===this.status&&4===this.readyState&&e.b.call(this)}}(),g.ontimeout=function(){return function(){}}(),g.timeout=e.d,g.send()}catch(c){}}function w(e,g){return function(){var c;this.responseText&&(c=/<requestSignature>([\w@]+)</.exec(this.responseText))&&2===c.length&&(g.requestSignature=c[1],g.sendPLT?e.xa(g):t(e,g))}}
function s(e,g,c){v({a:g,b:c,d:e.H})}
function t(e,g){var c,f;c=[];var h="";f=g.deviceCaps.call(g);for(var l=Object.keys(f),m=l.length;m--;)c.push(l[m]+"="+f[l[m]]);window.location&&window.location.search&&(f=/radar-location=\w+-\w+-\w+/.exec(window.location.search))&&c.push(f[0]);0<c.length&&(h="?"+c.join("&"));c=[g.domains.code,g.zoneId,g.customerId,"radar",g.buildTimestamp,e.O(20),"providers.json"];c="//"+c.join("/")+h;v({a:c,b:function(a){return function(){var b;try{b=JSON.parse(this.responseText)}catch(c){return}a.$(b,g)}}(e),c:e.H})}
;window.cedexis.main=window.cedexis.main||new q(window,document);var x,y,u;if(window.cedexis.requestors)for(x=Object.keys(window.cedexis.requestors),y=x.length;y--;)u=window.cedexis.requestors[x[y]],u.runCalledAt||window.cedexis.main.wa();}(window,document));
