
/*script:utils_mag.js*/
var startTScript=new Date().getTime ();
var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.Mag=DELL.com.Mag||{};DELL.com.Mag.Utils=DELL.com.Mag.Utils||{};(function($,window,document){(function(){this.GetOverrides=function(){var hash=window.location.hash,overrides="";$.each(hash.split("&"),function(index,data){if(!(data.indexOf("overrides=")<0)){overrides=data.split("=")[1];return false;}});return decodeURI(overrides);};this.GetOrderCodeOverrides=function(orderCode,modId){var overrides=DELL.com.Mag.Utils.GetOverrides(),ocOverride=null;$.each(overrides.split("|"),function(index,data){var parts=data.split(":"),orderCodeFormat=orderCode;if(parts[0].toLowerCase()===orderCodeFormat.toLowerCase()){ocOverride=parts[1];}});return ocOverride;};this.UpdateHashValue=function(overrides){var newHash="",initialHash=window.location.hash,hashParams=initialHash.split("&");$.each(hashParams,function(hashIndex,hashData){if(hashData.indexOf("overrides=")<0){if(newHash!=="")newHash+="&";newHash+=hashData;}});if(newHash!=="")newHash+="&";newHash+=(overrides!=="")?"overrides="+overrides:"overrides=";window.location.hash=newHash;if(DELL.com.Mediaplex&&newHash!==""){DELL.com.Mediaplex.ajaxUpdate();}};this.MaxHeight=function(domObject){var item=domObject;var h=0;item.each(function(){if($(this).height()!=0){h=Math.max(h,$(this).height());}else{h="";}}).height(h);};this.OldAdjustHeight=function(el,ignore){if(!ignore){ignore=['img','span','a','hr','ul','li','.ignored'];}
var heightFix=0,ignoreSelector=ignore.join(', ');el.not(ignoreSelector).height("");el.not(ignoreSelector).each(function(){heightFix=Math.max(heightFix,$(this).height());}).height(heightFix);el.eq(0).children().each(function(){var current=$(this),elements=$();el.each(function(){elements=elements.add($(this).children().eq(current.index()));});DELL.com.Mag.Utils.AdjustHeight(elements,ignore);});};this.InArray=function(arr,elt){var len=arr.length>>>0,from=Number(arguments[1])||0;from=(from<0)?Math.ceil(from):Math.floor(from);if(from<0)
from+=len;for(;from<len;from++){if(from in arr&&arr[from]===elt)
return from;}
return-1;};this.GetElementBy=function(type,id,context){'use strict';if(!context)
context=document;var results;switch(type){case'id':results=context.getElementById(id);break;case'tag':results=context.getElementsByTagName(id);break;case'class':if(document.getElementsByClassName){results=context.getElementsByClassName(id);}else{results=[];var regex=new RegExp('(^| )'+id+'($| )'),elements=context.getElementsByTagName('*');for(var i=0,elCt=elements.length;i<elCt;i++){if(regex.test(elements[i].className)){results.push(elements[i]);}}}
break;}
return results;};this.IsHidden=function(el){return!DELL.com.Mag.Utils.isVisible(el);};this.IsVisible=function(el){return el.offsetWidth>0||el.offsetHeight>0;};this.GetHeight=function(el){var ua=window.navigator.userAgent;var msie=ua.indexOf("MSIE");var cHeight;if(msie>0){var height=el.offsetHeight;var paddingTop=el.currentStyle.paddingTop?parseInt(el.currentStyle.paddingTop):0;var paddingBottom=el.currentStyle.paddingBottom?parseInt(el.currentStyle.paddingBottom):0;var borderTop=el.currentStyle.borderTop?parseInt(el.currentStyle.borderTop):0;var borderBottom=el.currentStyle.borderBottom?parseInt(el.currentStyle.borderBottom):0;cHeight=height-paddingTop-paddingBottom-borderTop-borderBottom;}else{cHeight=document.defaultView.getComputedStyle(el,'').getPropertyValue('height');cHeight=(cHeight.split('px'))[0];}
return cHeight;};this.AdjustHeight=function(el,cNodes,args){args=args||{};var validTags=args.vTags||['div'],classesToAdjust=args.vClasses||[],ignoredClasses=args.iClasses||['tsStack'];if(!el.length)
return;if(!el[0].tagName)
return;if(DELL.com.Mag.Utils.InArray(validTags,el[0].tagName.toLowerCase())===-1)
return;if(!el[0].className)
return;var validClass=false,elClasses=el[0].className.split(' ');for(var i=elClasses.length;i--;){if(DELL.com.Mag.Utils.InArray(classesToAdjust,elClasses[i])>-1){validClass=true;cNodes=cNodes&&((DELL.com.Mag.Utils.InArray(ignoredClasses,elClasses[i])>-1)?false:true);break;}}
if(!validClass)
return;var children=el[0].children;for(i=children.length;i--;){var current=[];var valid=true;for(var j=el.length;j--;){if(el[j].children.length<=i){valid=false;break;}
current.push(el[j].children[i]);}
if(valid){DELL.com.Mag.Utils.AdjustHeight(current,true,args);}}
if(cNodes){var itemHeights=[0];for(i=el.length;i--;){el[i].style.height='auto';itemHeights.push(DELL.com.Mag.Utils.GetHeight(el[i]));}
var maxHeight=Math.max.apply(null,itemHeights);for(i=el.length;i--;){el[i].style.height=maxHeight+'px';}}};this.ImagesLoaded=function(el,newEl,fn,args){var imgs=DELL.com.Mag.Utils.GetElementBy('tag','img',el[0]);var loadedImgs=0;for(var i=imgs.length;i--;){var tmpSrc=imgs[i].src;imgs[i].src='';imgs[i].onload=function(){loadedImgs++;if(loadedImgs===imgs.length){fn(el,newEl,args);}};imgs[i].src=tmpSrc;}};}).call(DELL.com.Mag.Utils);})(jQuery,window,document);
if (window.console){console.log('ex time: utils_mag.js', new Date().getTime() - startTScript);}



/*script:sliding_anchors_mag.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.SlidingAnchors=DELL.com.SlidingAnchors||{};DELL.com.Utils=DELL.com.Utils||{};(function($,win){(function(){var $tabCtr=$("#notification-anchor");var $slideTabs=$tabCtr.find("#sliding_tabs");var $anchrTab=$slideTabs.find(".anchorTab");var $prcBar=$("#prcBar");var $rTop=$tabCtr.find('.sliding_returntotop');var $wrapper=$tabCtr.find(".sliding_wrapper");var $zones=$(".anchorZone");var plris=$('div.mag').hasClass('plris');var lgcIE=($.browser.msie&&parseInt($.browser.version)<=7);var scrolled=false;var onload={initialize:function(){if(($('.heroDescriptionContainer').height()+40)>$('#heroContent').height())
$('#heroContent').height($('.heroDescriptionContainer').height()+40);$anchrTab.each(function(index){var $this=$(this);var tabName=$this.attr("name");var tabContent=$("#"+tabName+" .anchorZoneContent div:first-child").html();if(tabContent!=null)tabContent=$.trim(tabContent);if(tabContent==null||tabContent==""){$this.remove();$zones.find('#'+tabName).remove();}
else{$("#"+tabName+" .anchorZoneHeader").show();}});if($anchrTab.length<=0)$tabCtr.remove();$rTop.css({visibility:"hidden"});$rTop.click(function(e){e.preventDefault();var speedTarget=500;$('html, body').animate({scrollTop:0},speedTarget);return false;});$('#iconographyParentContainer .iconographyContainer a').unbind('click').bind('click',function(e){e.preventDefault();var href=$(this).attr("href");if(href!=null){var $tab=$slideTabs.find('li[name="'+href.replace('#','')+'"]');if($tab.length>0)
$tab.trigger('click');}});$slideTabs.find('li').unbind('click').bind('click',function(){var $this=$(this);var tabName=$this.attr("name");var tabId=$this.attr("id");var $zone=$("#"+tabName);var tabHeight=$slideTabs.height();$slideTabs.css({position:"fixed",top:"0"});var pos=!plris?$zone.offset().top:($zone.offset().top-tabHeight);$anchrTab.removeClass("selected");$this.addClass("selected");$(win).unbind('scroll',slidingAnchorTabs);if(plris&&($zones.first().offset().top+$zones.first().height()))
$prcBar.css({position:"static",top:""});$('html, body').animate({scrollTop:pos},400,function(){slidingAnchorTabs();$(win).bind('scroll',slidingAnchorTabs);var posCheck=(!plris?$zone.offset().top:($zone.offset().top-tabHeight));if(plris){if(pos>=posCheck)
$('html, body').scrollTop(posCheck);}else{if(pos!=posCheck)
$('html, body').scrollTop(posCheck);}});return false;});if($slideTabs.length>0){$(win).scroll(slidingAnchorTabs);if(lgcIE)
setMaxHeight();}
var hash=win.location.hash.toLowerCase();if($('.mag').length>0&&((hash=="#ratingsandreviews")||(hash=="#reviews"))){setTimeout(function(){$(win).scrollTop($('#BVReviewsContainer').offset().top-30);},1000);}
if($anchrTab.filter('selected').length==0)
$anchrTab.first().addClass('selected');}};var setMaxHeight=function(){var max=0,h=0;$anchrTab.each(function(index){h=$anchrTab.eq(index).height()
if(max<h)
max=h;})
$anchrTab.find("a").css('height',((max-36)+'px'));};var slidingAnchorTabs=function(){if(!scrolled){scrolled=true;if(!lgcIE)
slideTabs();else
setTimeout(slideTabs,4);setTimeout(function(){scrolled=false;},50);}};var slideTabs=function(pos){var wrap=$wrapper.height();var scrollPos=pos||$(win).scrollTop();var totalTabsHeight=$slideTabs.height()+wrap;var rtt=$rTop;var lastPos=$zones.last().offset().top+$zones.last().height();var firstTitle=$zones.first().offset().top;if(scrollPos>=firstTitle)
closestAnchorZone(scrollPos);if((scrollPos>=firstTitle)&&(lastPos-totalTabsHeight>=scrollPos)){$slideTabs.css({position:"fixed",top:"0"});$wrapper.css({position:"fixed",top:$slideTabs.height()});rtt.css({visibility:"visible",position:"",top:""});}else if((scrollPos>lastPos-totalTabsHeight)&&(scrollPos<lastPos)){$slideTabs.css({position:"fixed",top:lastPos-totalTabsHeight-scrollPos});$wrapper.css({position:"fixed",top:lastPos-wrap-scrollPos});rtt.css({position:"",top:""});}else{$slideTabs.css({position:"static",top:""});$wrapper.css({position:"static",top:""});rtt.css({visibility:"hidden"});}
if($prcBar.length>0)
slidePrcBar(scrollPos,firstTitle,(firstTitle+$zones.first().outerHeight()),$slideTabs.height());};var slidePrcBar=function(pos,start,end,tabH){var winWidth=$(win).width();var ht=$prcBar.height();var tbWidth=$slideTabs.width();var max=end-tabH-ht-20;var width=(winWidth>tbWidth)?(((winWidth-tbWidth)/2)):((tbWidth-winWidth)*-1);if((pos>=start)&&(pos<=max))
$prcBar.css({position:"fixed",top:(tabH+20),right:width});else if(pos>max&&ht>(pos-max))
$prcBar.css({position:"fixed",top:((end-20-ht)-pos),right:width});else
$prcBar.css({position:"static",top:""});};var closestAnchorZone=function(scrollPos){var winTop=!plris?$(win).scrollTop():($(win).scrollTop()+($slideTabs.height()));if($zones.first().offset().top){$zones.each(function(index){if(($zones.eq(index).offset().top+$zones.eq(index).outerHeight())>winTop){if(!$anchrTab.eq(index).hasClass("selected")){$anchrTab.removeClass("selected");$anchrTab.eq(index).addClass("selected");}
return false;}});}};if($.browser.msie&&parseInt($.browser.version)<=8)
DELL.com.Utils.Initialize(onload.initialize);else
onload.initialize();}).call(DELL.com.anchoredContent);})(jQuery,window);
if (window.console){console.log('ex time: sliding_anchors_mag.js', new Date().getTime() - startTScript);}



/*script:expand_collapse_mag.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.Mag=DELL.com.Mag||{};DELL.com.Mag.ExpandCollapse=DELL.com.Mag.ExpandCollapse||{};DELL.com.Utils=DELL.com.Utils||{};DELL.com.Utils.Metrics=DELL.com.Utils.Metrics||{};(function($){(function(){this.CreateButtons=function(el){$('.expandable',el).each(function(){var maxHeight=DELL.com.Mag.ExpandCollapse.GetMaxHeight($(this)),button='<div class="expandCollapse expand expandFog" style="display: block">';button+='<a class="magExpandButton" href="#"><h6 class="arrow-expand">'+($(this).parent().attr('id').toLowerCase()==='anchorzone1'?expandCollapseVars.ConfigExpand:expandCollapseVars.CommonExpand)+'</h6></a>';button+='<a class="magExpandButton hidden" href="#"><h6 class="arrow-collapse">'+($(this).parent().attr('id').toLowerCase()==='anchorzone1'?expandCollapseVars.ConfigCollapse:expandCollapseVars.CommonCollapse)+'</h6></a>';button+='</div>';if($(this).height()>maxHeight){$(this).attr('data-fullHeight',$(this).height());$(this).height(maxHeight).after(button);}
DELL.com.Mag.ExpandCollapse.BindEvents(el);});};this.GetMaxHeight=function(el){if(el){var zone=el.parent();if(zone&&zone.attr('id')){return(zone.attr('id').toLowerCase()==='anchorzone1'?(zone.find('.pStack:visible').height()+parseInt(expandCollapseVars.ConfigHeight)):expandCollapseVars.CommonHeight);}else{return null;}}
return null;};this.BindEvents=function(el){$('.magExpandButton',el).unbind('click').click(function(e){e.preventDefault();var buttonDiv=$(this).parent();var specDiv=buttonDiv.parent().find('.anchorZoneContent');var newHeight,newBtClass,oldBtClass;if(buttonDiv.hasClass('expand')){newHeight=specDiv.attr('data-fullHeight');newBtClass='collapse';oldBtClass='expand expandFog';DELL.com.Utils.Metrics.logExpandCollapseSections($(this));}else{var maxHeight=DELL.com.Mag.ExpandCollapse.GetMaxHeight($(this).parent());newHeight=maxHeight+'px';newBtClass='expand';oldBtClass='collapse';}
buttonDiv.addClass('expandFog');specDiv.animate({height:newHeight},{duration:1500,step:function(){if(buttonDiv.hasClass('collapse')){posX=specDiv.position().left;posY=specDiv.position().top+specDiv.height();$(window).scrollLeft(posX-$(window).width()/2).scrollTop(posY-$(window).height()/2);}},complete:function(){buttonDiv.removeClass(oldBtClass).addClass(newBtClass);$('.magExpandButton',el).toggleClass('hidden');}});});};onload={initialize:function(){DELL.com.Mag.ExpandCollapse.CreateButtons();}};$('document').ready(function(){DELL.com.Utils.Initialize(onload);});}).call(DELL.com.Mag.ExpandCollapse);})(jQuery);
if (window.console){console.log('ex time: expand_collapse_mag.js', new Date().getTime() - startTScript);}



/*script:config_tab_mag.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.Mag=DELL.com.Mag||{};DELL.com.Mag.ConfigTab=DELL.com.Mag.ConfigTab||{};DELL.com.Mag.Utils=DELL.com.Mag.Utils||{};DELL.com.Mag.ExpandCollapse=DELL.com.Mag.ExpandCollapse||{};DELL.com.Utils=DELL.com.Utils||{};DELL.com.Utils.Metrics=DELL.com.Utils.Metrics||{};(function($){(function(){var configTab=$('.configTab');var $prcBr=$('#prcBar');this.GetOrderCodeOverrides=function(orderCode,modId){var overrides=DELL.com.Mag.Utils.GetOverrides(),ocOverride=null;$.each(overrides.split("|"),function(index,data){var parts=data.split(":"),orderCodeFormat=orderCode;if(parts[0].toLowerCase()===orderCodeFormat.toLowerCase()){ocOverride=parts[1];}});return ocOverride;};this.UpdateOverrides=function(ocId,modId,optId,multiSelect,checked,addingDefaults){ocId=ocId.toLowerCase();var sysOC=$("#currentOC").attr("value");sysOC=(sysOC!=null&&sysOC!="")?sysOC.toLowerCase():ocId;var sysUid=DELL.com.Utils.getUidFromOC(sysOC),ccOC=(ocId!=sysOC)?ocId:"",ccOptionId=$("#"+ccOC+"OptionId").attr("value"),sysOCWithSlot=sysOC;if($(".compareContainer").length>0)
sysOCWithSlot=sysOC+"_"+configCompareSlot;var overrides=DELL.com.Mag.Utils.GetOverrides();if(overrides.indexOf(sysOCWithSlot+":")<0&&!addingDefaults){DELL.com.ProductHubModuleUpsell.AddDefaultSelections(sysOC,ccOC);overrides=DELL.com.Mag.Utils.GetOverrides();}
var isDefault=false,defaultOptions=$("#"+sysUid+"DefaultOptions").attr("value");if(defaultOptions!=null&&defaultOptions!="")
isDefault=defaultOptions.indexOf("|"+modId+"~"+optId+"|")>=0;var newOverrides="";if(overrides.indexOf(sysOCWithSlot+":")<0&&!isDefault){newOverrides=overrides+((overrides!="")?"|":"");newOverrides+=sysOCWithSlot+":"+modId+"~"+optId;DELL.com.Mag.Utils.UpdateHashValue(newOverrides);return;}
$.each(overrides.split("|"),function(ocIndex,ocData){var ocDataSet=ocData.split(":");if(ocDataSet[0]!=sysOCWithSlot){newOverrides+=((newOverrides!="")?"|":"")+ocData;return true;}
var modulesData=ocDataSet[1];var exists=modulesData.indexOf(modId+"~")==0||modulesData.indexOf(";"+modId+"~")>=0;if(ccOC==""&&!exists&&!isDefault){newOverrides+=((newOverrides!="")?"|":"")+ocData+";"+modId+"~"+optId;return true;}
var newModData="";$.each(modulesData.split(";"),function(modIndex,modData){var modDataSet=modData.split("~"),dataModId=modDataSet[0],optData=modDataSet[1];if((ccOC===""&&dataModId!==modId)||(ccOC!==""&&optData.indexOf(ccOptionId)<0)){newModData+=((newModData!="")?";":"")+modData;return true;}
if(ccOC==""){if(multiSelect){var newOptData="";$.each(optData.split("+"),function(index,data){if(data.indexOf(optId)<0)
newOptData+=((newOptData!="")?"+":"")+data;});if(checked)
newOptData+=((newOptData!="")?"+":"")+optId;if(newOptData!="")
newModData+=((newModData!="")?";":"")+dataModId+"~"+newOptData;}else{if(optId!=""&&!isDefault)
newModData+=((newModData!="")?";":"")+modId+"~"+optId;}}else{var newOptData="";$.each(optData.split("+"),function(index,data){if(data.indexOf(ccOptionId)<0){newOptData+=((newOptData!="")?"+":"")+data;return true;}
var ccData=DELL.com.ProductHubModuleUpsell.UpdateCompositeConfigOverrides(ccOC,ccOptionId,modId,optId,data,multiSelect,checked);newOptData+=((newOptData!="")?"+":"")+ccData;});if(newOptData!="")
newModData+=((newModData!="")?";":"")+dataModId+"~"+newOptData;}});if(newModData!="")
newOverrides+=((newOverrides!="")?"|":"")+sysOCWithSlot+":"+newModData;});DELL.com.Mag.Utils.UpdateHashValue(newOverrides);};this.MagModPopUpError=function(instruction,ocId,modId,obj){var ocUid=DELL.com.Utils.getUidFromOC(ocId);if(instruction!=null&&instruction!=""){$(".modPopUp .mod-upsell-compat-instr").remove();$(".modPopUp").prepend(instruction);$(".modPopUp .mod-upsell-compat-instr").html($(".modPopUp .mod-upsell-compat-instr").html().replace(/modlink/gi,"span class=\"modlink\" "));var modLinks=$(".modPopUp .mod-upsell-compat-instr").find(".modlink");if(modLinks!=null&&modLinks.length>0){modLinks.each(function(index,data){var linkId=$(data).attr("id");var linkText=$(data).html();$(data).attr("id",ocUid+"Mod"+linkId);});}
setTimeout(function(){var $mo=$("#"+ocUid+"Mod"+modId+"Container");var $modErr=$(".mod-upsell-compat-instr");var $modErrCtr=$modErr.find('.yellowContainer .il');var oh=294;var errPos=$mo.offset();if(modId==0){if(obj){errPos=$(obj).offset();}else if($('div.modErrBlock[rel="modErrBlock_'+ocUid+'"]').length>0){errPos=$('div.modErrBlock[rel="modErrBlock_'+ocUid+'"]').offset();}else if($(".modPopUp .warrantyModal").length<=0){errPos=$(".modPopUp .inlineContent").first().offset();}else{errPos=$(".modPopUp .warrantyModal").first().offset();}}
var errPosition={top:errPos.top+20,left:errPos.left};$modErr.offset(errPosition);oh=$modErrCtr.height();$modErrCtr.height('auto');if($modErrCtr.height()>294)
$mo.find('.leftCol').height($modErr.height());else
$modErrCtr.height(oh);},500);DELL.com.ProductHub.ModErrorAlert(ocId);$(".mod-upsell-compat-instr .modlink").unbind("click").bind("click",function(){ActivateModule($(this).attr("id"));});$(".primaryBtn .btn, .defaultPrimaryBtn .btn, .pStack .purchase, .pStack .secondaryNav").unbind("click").bind("click",function(){if($(this).hasClass("disabled"))return false;});if($("#magCompareTray, .plris #compareGrid").length>0)
{$(".compareCTA, .pStack .purchase").click(function(){configCompareSlot=$(this).closest('th').index();});$(".zombiePage .btn").click(function(){configCompareSlot=$(this).closest('td').index()+1;});}
$(".modErrBlock, .defaultModErrBlock").unbind("click").bind("click",function(){var object=$(this);$(".modPopUpClose").click();if($("#magCompareTray, .plris #compareGrid").length>0){configCompareSlot=$(this).closest('th').index();}
$('html, body').animate({scrollTop:object.offset().top-80},1000);DELL.com.Mag.ConfigTab.magShowInvalidModules(this);});}
else{if($("#mainModuleId").length<0||$("#mainModuleId").attr("value")<=0){$(".modPopUpClose").click();}}};ActivateModule=function(modLinkId){var mod=$("#"+modLinkId+"Container");if(mod.length>0){var errPos=$(mod).offset();var errPosition={top:errPos.top+20,left:errPos.left};$(".mod-upsell-compat-instr").offset(errPosition);}};this.ConfigSelector=function(object){if($(object).hasClass("expanded")){DELL.com.Mag.ConfigTab.TogglePopup();return false;}
DELL.com.Mag.ConfigTab.LoadStatus(object,true);var ps=DELL.com.Delphi.PageSettings,productCode=($("#magCompareTray, .plris #compareGrid").length>0)?$(object).parent().find(".productCode").attr("value"):$("#productCode").attr("value"),id=$(object).parent().children("span:not(.hide):first").attr("class"),idparts=id.split("~"),ocId=DELL.com.Utils.getOCFromUid(idparts[1]),ocUid=idparts[1],modId=idparts[2],params="c="+ps.lwp.Country;params+="&l="+ps.lwp.Language;params+="&s="+ps.lwp.Segment;params+="&cs="+ps.lwp.CustomerSet;params+="&oc="+ocId;params+="&modId="+modId;params+="&productCode="+productCode;params+="&moduleTemplate=products/ProductDetails/mag/config_popup_mag";params+="&modErrorTemplate=products/module_option_validation";params+="&resultType=SingleModule";params+="&uiParameters="+escape("mainModuleId="+modId+"&uniqueId="+ocUid);var overrides=DELL.com.Mag.Utils.GetOrderCodeOverrides(ocId,modId);if($("#magCompareTray, .plris #compareGrid").length>0){var colIndex=$(object).parent().index()+1;configCompareSlot=colIndex-1;overrides=$("#compareGrid th:nth-child("+colIndex+")").find(".overrides").val();}
if(overrides!=null&&overrides!="")params+="&overrides="+encodeURIComponent(overrides);var url=ps.APIRoot+"configService.svc/postmoduleoverrides/json";$.ajax({type:'POST',dataType:"json",url:url,data:params,error:function(req){DELL.com.Mag.ConfigTab.LoadStatus(object,false);},success:function(req){var scrollHeight=$('.plris').length?($('#sliding_tabs').height()+10):10;if($(".configRemoteCarousel").length>0||$("#remoteCarousel").length>0)scrollHeight=190;$('html, body').animate({scrollTop:object.offset().top-scrollHeight},1000);DELL.com.Mag.ConfigTab.LoadStatus(object,false);if(req.ModulesHtml!=null&&req.ModulesHtml!=""){DELL.com.Mag.ConfigTab.TogglePopup(req.ModulesHtml,object);}
DELL.com.Mag.ConfigTab.MagModPopUpError(req.ModOptionErrorHtml,ocId,modId);}});};this.magShowInvalidModules=function(obj){if($(obj).hasClass("expanded"))return;$(obj).addClass("expanded");$('#processingCaptionID').text("");var ocUid=$(obj).attr("rel").split("_")[1];var ocId=DELL.com.Utils.getOCFromUid(ocUid);$j(document).bind('mousemove',followmouse);var ps=DELL.com.Delphi.PageSettings;var url=ps.APIRoot+"configService.svc/postmoduleoverrides/json";var lwpc=ps.lwp.Country;var lwpl=ps.lwp.Language;var lwps=ps.lwp.Segment;var lwpcs=ps.lwp.CustomerSet;var productCode=$("#productCode").attr("value");var params="c="+lwpc;params+="&l="+lwpl;params+="&s="+lwps;params+="&cs="+lwpcs;params+="&oc="+ocId;params+="&productCode="+productCode;params+="&moduleTemplate=products/ProductDetails/mag/config_popup_mag";params+="&modErrorTemplate=products/module_option_validation";params+="&resultType=InvalidModules";params+="&uiParameters="+escape("mainModuleId="+"0"+"&uniqueId="+ocUid);var overrides=DELL.com.Mag.Utils.GetOrderCodeOverrides(ocId);if($("#magCompareTray, .plris #compareGrid").length>0){configCompareSlot=$(obj).closest('th').index();var colIndex=configCompareSlot+1;overrides=$("#compareGrid th:nth-child("+colIndex+")").find(".overrides").val();}
if(overrides!=null&&overrides!="")params+="&overrides="+encodeURIComponent(overrides);$.ajax({type:'POST',dataType:"json",url:url,data:params,error:function(req){$j(document).unbind('mousemove',followmouse);hidetrail();},success:function(req){$j(document).unbind('mousemove',followmouse);hidetrail();if(req.ModulesHtml!=null&&req.ModulesHtml!=""){DELL.com.Mag.ConfigTab.TogglePopup(req.ModulesHtml,obj);}
DELL.com.Mag.ConfigTab.MagModPopUpError(req.ModOptionErrorHtml,ocId,0,($('.plris').length?obj:null));}});};this.TogglePopup=function(data,obj){var popup=$(".modPopUp");$(".expanded").removeClass("expanded");if(data){popup.before("<div class=\"moduleOverlay\"></div>");$(".moduleOverlay").css({"height":($(document).height()+"px")});if(obj!=null&&obj.length>0){var parentOff=$("#secondaryContent").offset();$(popup).html(data);var off=$(obj).offset();var popupPosition={top:off.top+31,left:parentOff.left-10};popup.find(".inlineContent").offset(popupPosition);$(obj).addClass("expanded");DELL.com.ProductHubModuleUpsell.BindOptionHover();}
DELL.com.Mag.ConfigTab.BindPopupEvents(obj);}else{popup.html("");$(".moduleOverlay").remove();}};this.BindPopupEvents=function(dropdown){$(".modPopUpClose, .moduleOverlay").click(function(){DELL.com.Mag.ConfigTab.TogglePopup();$(".moduleOverlay").remove();});$(".modOption").click(function(){$(".modPopUp input").attr("disabled","disabled");var obj=$(this).parents(".modPopUp");var ocId=$(obj).find("#currentOC").attr("value");var ocUid=DELL.com.Utils.getUidFromOC(ocId);obj=$(this).parents(".warrantyModal");var modId=$(obj).attr("id").replace(ocUid+"_mod_","");obj=$(this).parents(".catContent");var option=$(obj).find(".content").attr("id");var checked=$(this).attr("checked")=="checked";var inputType=$(this).attr("type");var multiSelect=false;if(inputType&&inputType!="radio")multiSelect=true;if($("#magCompareTray, .plris #compareGrid").length>0){DELL.com.Mag.ConfigTab.UpdateCompareOverrides(ocId,modId,option,dropdown,multiSelect);}
DELL.com.Mag.ConfigTab.UpdateOverrides(ocId,modId,option,multiSelect,checked);DELL.com.Mag.ConfigTab.UpdateSpecs(this,true,dropdown);var isDefault=false;var sysOC=ocId.toLowerCase();var sysUid=DELL.com.Utils.getUidFromOC(sysOC);var defaultOptions=$("#"+sysUid+"DefaultOptions").attr("value");if(defaultOptions!=null&&defaultOptions!="")
isDefault=defaultOptions.indexOf("|"+modId+"~"+option+"|")>=0;if(multiSelect){var multiVal=[];$(".modOption[name='"+sysUid+"_mod_"+modId+"_options']").each(function(){if($(this).is(":checked")){multiVal.push($(this).attr('id').substr(6));}});option=multiVal.join('+');;}
DELL.com.Utils.Metrics.logModUps(ocId,modId,option,isDefault,true);});$(".modPopUp .ccLink").unbind("click").bind("click",function(){var obj=$(this).parents(".modPopUp");var ocId=$(obj).find("#currentOC").attr("value");var ocOverrides=DELL.com.ProductHubModuleUpsell.GetOrderCodeOverrides(ocId);var hrefWithOverrides=$(this).attr("href");var newHref="";$.each(hrefWithOverrides.split("&"),function(hrefIndex,hrefData){var overrrideIndex=hrefData.indexOf("overrides");if(overrrideIndex<0){newHref+=hrefData;newHref+="&";}});newHref+="overrides="+encodeURIComponent(ocOverrides);$(this).attr("href",newHref);});};this.UpdateCompareOverrides=function(ocId,modId,option,dropdown,multiSelect){var colIndex=$(dropdown).parent().index()+1;if($(dropdown).hasClass("modErrBlock"))
{configCompareSlot=$(dropdown).closest('th').index();colIndex=configCompareSlot+1;}
var stack=$("#compareGrid th:nth-child("+colIndex+")");if(stack.find(".overrides").length>0){var finalOverride="";var updated=false;var overridesArray=stack.find(".overrides").val().split(";");$.each(overridesArray,function(index,value){if(value.length>0){var overrideItemArray=value.split("~");var override=overrideItemArray[0];var overrideValue=overrideItemArray[1];if(override==modId){if(multiSelect){var multiOverrideArray=overrideValue.split("+");if($.inArray(option,multiOverrideArray)>-1)
multiOverrideArray=$.grep(multiOverrideArray,function(val){return val!=option&&val!="";});else
multiOverrideArray.push(option);overrideValue=multiOverrideArray.join("+");}else
overrideValue=option;updated=true;}
finalOverride=finalOverride+override+"~"+overrideValue+";";}});if(updated==false){finalOverride=finalOverride+modId+"~"+option+";";}
stack.find(".overrides").val(finalOverride);}else stack.append("<input type='hidden' value='"+modId+"~"+option+"' class='overrides'>");};this.LoadStatus=function(obj,loading){if(loading){$(obj).addClass('loading');}else{$(obj).removeClass('loading');}};this.UpdateSpecs=function(obj,option,selectedDropdown){selectedDropdown=$(selectedDropdown);var ocUid=DELL.com.Utils.getUidFromOC($("#currentOC").attr("value"));var selectedIndex=$('#configOc_'+ocUid).find('.dropdown').index(selectedDropdown);DELL.com.Mag.ConfigTab.LoadStatus(selectedDropdown,true);var ocId=$("#currentOC").attr("value"),groupId=$("#groupId").attr("value"),productCode=($("#magCompareTray, .plris #compareGrid").length>0)?selectedDropdown.parent().find(".productCode").attr("value"):$("#productCode").attr("value"),obj1=$(obj).parents(".warrantyModal"),modId=$(obj1).attr("id").replace(ocUid+"_mod_","");var mainModuleId=$("#mainModuleId").attr("value");var ps=DELL.com.Delphi.PageSettings;var params="c="+ps.lwp.Country;params+="&l="+ps.lwp.Language;params+="&s="+ps.lwp.Segment;params+="&cs="+ps.lwp.CustomerSet;params+="&oc="+ocId;params+="&modId="+modId;params+="&groupid="+groupId;params+="&productCode="+productCode;params+="&stackPriceTemplate=products/productStack/"+(($("div.plris").length&&!$("#magCompareTray").length)?"stack_pol":"stack_mag");params+="&moduleTemplate=products/ProductDetails/mag/config_popup_mag";params+="&modErrorTemplate=products/module_option_validation";params+="&resultType=SingleModuleAndSpecs";if($("#magCompareTray, .plris #compareGrid").length>0){if($(".plris #compareGrid").length>0){params+="&priceTemplate=products/compare/comparison_table_item_pol";params+="&uiParameters="+escape("mainModuleId="+mainModuleId);}
else{params+="&zombiePriceTemplate=products/productdetails/mag/compare_zombie_bar_item_mag";params+="&priceTemplate=products/compare/comparison_table_item_mag";params+="&uiParameters="+escape("mainModuleId="+mainModuleId);}}else{if($("div.plris").length&&!$('.singleConfig').length)params+="&priceTemplate=products/productStack/stack_pol_simple";params+=($prcBr.length==0)?"&zombiePriceTemplate=products/productdetails/mag/pd_zombie_bar_item_mag":"&zombiePriceTemplate=products/productdetails/mag/price_bar";params+="&uiParameters="+escape("mainModuleId="+mainModuleId+"&_showAddToCartPrimary=true&_switchCTA=true&uniqueId="+ocUid);}
var overrides=DELL.com.Mag.Utils.GetOrderCodeOverrides(ocId,modId);if($("#magCompareTray, .plris #compareGrid").length>0){var colIndex=selectedDropdown.parent().index()+1;if(selectedDropdown.hasClass("modErrBlock"))
{configCompareSlot=selectedDropdown.closest('th').index();colIndex=configCompareSlot+1;}
overrides=$("#compareGrid th:nth-child("+colIndex+")").find(".overrides").val();}
if(overrides!=null&&overrides!="")params+="&overrides="+encodeURIComponent(overrides);var url=ps.APIRoot+"configService.svc/postmoduleoverrides/json";$.ajax({type:'POST',dataType:"json",url:url,data:params,error:function(req){$(".modPopUp input").removeAttr("disabled");},success:function(req){if($("#magCompareTray, .plris #compareGrid").length>0){var colIndex=selectedDropdown.parent().index()+1;if(selectedDropdown.hasClass("modErrBlock"))
{configCompareSlot=selectedDropdown.closest('th').index();colIndex=configCompareSlot+1;}
var zombieRow=colIndex-2;var col=$("#compareGrid td:nth-child("+colIndex+")");$.each(req.ProductHubSpecs,function(index,data){var dataUid=DELL.com.Utils.getUidFromOC(data.OrderCode);if(col.find(".spec\\~"+dataUid+"\\~"+data.ModuleId).length>0){var td=col.find(".spec\\~"+dataUid+"\\~"+data.ModuleId).parent();if(td.find(".defaultSpec").length==0)
td.prepend(col.find(".spec\\~"+dataUid+"\\~"+data.ModuleId).clone().addClass("defaultSpec hide"));td.find(".spec\\~"+dataUid+"\\~"+data.ModuleId).not(".defaultSpec").text(data.LongSpec||data.ShortSpec);DELL.com.Mag.ConfigTab.FindDifferentCompareSpecs(td.parent().attr('id'));}});col=$("#compareGrid th:nth-child("+colIndex+")");if(col.find(".defaultStack").length==0){ocUid=DELL.com.Utils.getUidFromOC(req.OrderCodeId);col.find(".pStack").parent().prepend(col.find(".configOc_"+ocUid+" .pStack").clone().addClass("defaultStack hide"));}
col.find(".pStack").not(".defaultStack").html(req.PriceHtml);$(".pStack .compareBtn").addClass("hide");if($(".compareZombieBar td:eq("+zombieRow+")").find(".defaultZombie").length==0){$(".compareZombieBar td:eq("+zombieRow+")").prepend($(".compareZombieBar td:eq("+zombieRow+")").find(".colContent").clone().addClass("defaultZombie hide"));}
$(".compareZombieBar td:eq("+zombieRow+")").find(".colContent").not(".defaultZombie").html(req.ZombiePriceHtml);$(".compareZombieBar td:eq("+zombieRow+"), .compareZombieBar td:eq("+zombieRow+") .priceBlock").addClass("hover").delay(1500).queue(function(next){$(this).removeClass("hover");next();});DELL.com.Mag.ConfigTab.TogglePopup(req.ModulesHtml,selectedDropdown);$(".modPopUp input").removeAttr("disabled");$(".primaryBtn .btn, .defaultPrimaryBtn .btn, .pStack .purchase, .pStack .secondaryNav").unbind("click").bind("click",function(){if($(this).hasClass("disabled"))return false;});$(".compareCTA, .pStack .purchase").click(function(){configCompareSlot=$(this).closest('th').index();});$(".zombiePage .btn").click(function(){configCompareSlot=$(this).closest('td').index()+1;});if($('.plris #compareGrid').length>0){$('.pStack:visible').height('');DELL.com.Plris.Compare.fixHeight();}}else{var ocUid=DELL.com.Utils.getUidFromOC(req.OrderCodeId);var configColumn=$('#configOc_'+ocUid);var isPlris=($('.plris').length>0);if(req.ProductHubSpecs!=null){$.each(req.ProductHubSpecs,function(index,data){var cSpec=configColumn.find(".spec\\~"+DELL.com.Utils.getUidFromOC(data.OrderCode)+"\\~"+data.ModuleId);cSpec.text(data.LongSpec||data.ShortSpec);var cSpecIndex=cSpec.parent().attr('data-specindex');$('.specContent[data-specindex="'+cSpecIndex+'"]:visible').height('');if(isPlris&&!$('.singleConfig').length){var cId=configColumn.attr('id'),specDivs=$('.'+cId).not(configColumn).find(".spec\\~"+DELL.com.Utils.getUidFromOC(data.OrderCode)+"\\~"+data.ModuleId);specDivs.text(data.LongSpec||data.ShortSpec);$('.configStackPage').each(function(){DELL.com.Mag.ConfigTab.FindDifferentSpecs(cSpecIndex,$(this));});}else{DELL.com.Mag.ConfigTab.FindDifferentSpecs(cSpecIndex);}});}
var productDiv=configColumn.find('.pStack:not(#prcBar,.simpleStack)');productDiv.html(req.StackPriceHtml);if(isPlris&&!$('.singleConfig').length){var columnId=configColumn.attr('id'),productDivs=$('.'+columnId).not(configColumn).find('.pStack:not(#prcBar,.simpleStack)'),priceDivs=$('.'+columnId).find('.simpleStack');productDivs.html(req.StackPriceHtml);priceDivs.html(req.PriceHtml);}else if(isPlris){var $err=$(req.StackPriceHtml).find('.modErrBlock');if($err.length>0&&$('.modErrBlock').length==0)
$('.errBlock').append($err);else if($err.length==0)
$('.errBlock').html('');}
$('.pStack:visible').height('');if(!isPlris){productDiv.find('.pStackHeader a').contents().unwrap();productDiv.find('.configImg a').contents().unwrap();}
productDiv.find('.secondaryNav').remove();productDiv.find('.qvLnk').remove();DELL.com.Mag.ConfigTab.FixSpecHeight(true);if(selectedIndex>=0)
selectedDropdown=$('#configOc_'+ocUid).find('.dropdown').eq(selectedIndex);DELL.com.Mag.ConfigTab.TogglePopup(req.ModulesHtml,selectedDropdown);$(".modPopUp input").removeAttr("disabled");$(".primaryBtn .btn, .defaultPrimaryBtn .btn, .pStack .purchase, .pStack .secondaryNav").unbind("click").bind("click",function(){if($(this).hasClass("disabled"))return false;});if($prcBr.length==0){DELL.com.Mag.ZombiePd.updateStack($('.configOc_'+ocUid,'.configRemoteCarousel'),req.ZombiePriceHtml);}else{updatePrcBar($prcBr,req.ZombiePriceHtml);DELL.com.Init.InitLinks($prcBr);}
DELL.com.Init.InitLinks(configColumn);DELL.com.Mag.ConfigTab.BindMetrics();}
DELL.com.Mag.ConfigTab.MagModPopUpError(req.ModOptionErrorHtml,ocId,modId);DELL.com.Mag.ConfigTab.LoadStatus(selectedDropdown,false);}});};var updatePrcBar=function(prcBr,r){if(prcBr!=null&&prcBr.length>0){var $r=$(r);prcBr.find('a.purchase').replaceWith($r.find('a.purchase').first());prcBr.find('.switchCTA').replaceWith($r.find('.switchCTA'));prcBr.css('height','auto');}};this.FindDifferentSpecs=function(index,container){var ocDivs=container?$('.configStackItem[id^="configOc_"]',container):$('.configStackItem[id^="configOc_"]:visible');var specFields=container?$('.specContent[data-specindex="'+index+'"]',container):$('.specContent[data-specindex="'+index+'"]:visible');specFields.removeClass('highlightedSpec');specFields=$.grep(specFields,function(spec){return $(spec).find('span').length>0;});if(ocDivs.length>1){for(var i=specFields.length;i--;){var specText=$(specFields[i]).find('span').html().toLowerCase();var found=false;var otherSpecs=specFields.slice(0);otherSpecs.splice(i,1);for(var j=otherSpecs.length;j--;){var otherText=$(otherSpecs[j]).find('span').html().toLowerCase();if(specText===otherText){found=true;break;}}
if(!found){$(specFields[i]).addClass('highlightedSpec');}}}};this.FindDifferentCompareSpecs=function(index){var ocRows=(index!=null)?$('#'+index):$('.specRow');for(var k=ocRows.length;k--;){var specFields=$(ocRows[k]).find('td:not(.specTitle):visible');specFields.removeClass('highlightedSpec');specFields=$.grep(specFields,function(spec){return $(spec).find('span').length>0;});if(specFields.length>1){for(var i=specFields.length;i--;){var specText=$(specFields[i]).find('span').not(".hidden, .hide").html().toLowerCase();var found=false;var otherSpecs=specFields.slice(0);otherSpecs.splice(i,1);for(var j=otherSpecs.length;j--;){var otherText=$(otherSpecs[j]).find('span').not(".hidden, .hide").html().toLowerCase();if(specText===otherText){found=true;break;}}
if(!found){$(specFields[i]).addClass('highlightedSpec');}}}}};this.BindEvents=function(){configTab.find(".magPage").unbind("click").click(function(e){e.preventDefault();if($(this).hasClass("disabled"))
return false;var id=$(this).attr("id").substr(2),isPlris=$('.plris').length>0;$(".configStackPage").hide();$("#configStackPage_"+id).show(0,'',function(){DELL.com.Mag.ConfigTab.FixSpecHeight(isPlris);if(!$("div.plris").length>0)
DELL.com.Mag.ZombiePd.showPage(id);});});$("a.helpMeChoose").unbind("click").click(function(e){e.preventDefault();var url=$(this).attr('href');var popup=window.open(url,'','width=850,height=500,scrollbars=yes');popup.focus();DELL.com.Utils.Metrics.logPagename('modal-hmc',true);});$(".dropdown").unbind("click").bind("click",function(e){var $this=$(e.target);DELL.com.Mag.ConfigTab.ConfigSelector($this.hasClass("dropdown")?$this:$this.parent());});$(".primaryBtn .btn, .defaultPrimaryBtn .btn, .pStack .purchase, .pStack .secondaryNav").bind("click",function(){if($(this).hasClass("disabled"))return false;});DELL.com.Mag.ConfigTab.BindMetrics();$(".modErrBlock, .defaultModErrBlock").unbind("click").bind("click",function(){var object=$(this);$(".modPopUpClose").click();if($("#magCompareTray").length>0){configCompareSlot=$(this).closest('th').index();}
$('html, body').animate({scrollTop:object.offset().top-80},1000);DELL.com.Mag.ConfigTab.magShowInvalidModules(this);});$(".configHighlightToggle").unbind("click").bind("click",function(e){$('.configStackBody, .compareGridContainer').toggleClass('highlightSpecs');var isChecked=$(this).is(':checked');$(".configHighlightToggle").attr('checked',isChecked);});};this.BindMetrics=function(){configTab.find(".atcPd").click(function(){var orderCode=$(this).parents('.configStackItem').attr('id').substring(9);var atc=($(this).attr('id'))?($(this).attr('id').indexOf("ssb:")==-1):true;DELL.com.Utils.Metrics.logPdCtaClick(orderCode,atc);});$(".configRemoteCarousel .atcPd").click(function(){var orderCode=$(this).closest('.remoteCarouselItem').attr('id').substring(9);var atc=($(this).attr('id'))?($(this).attr('id').indexOf("ssb:")==-1):true;DELL.com.Utils.Metrics.logPdCtaClick(orderCode,atc);});};this.LoadSelectedOptions=function(){if($("#magCompareTray, .plris #compareGrid").length>0)return;if($('#sliding_tabs').length>0)
DELL.com.Utils.Metrics.clearExpandCollapseInfo();var overrides=DELL.com.Mag.Utils.GetOverrides();if(overrides==null||overrides==""){return;}
var sdOverrides=overrides.split('|');$(sdOverrides).each(function(){sdOverride=this.split(';');sdOc=(sdOverride[0].split(':'))[0];$(sdOverride).each(function(i,mod){if(i==0)mod=mod.split(':')[1];mod=mod.split('~');DELL.com.Utils.Metrics.logModUps(sdOc,mod[0],mod[1]);});});configTab.find('.dropdown').each(function(){DELL.com.Mag.ConfigTab.LoadStatus(this,true);});if(typeof DELL.com.Delphi!=='undefined')
getConfigOptions(overrides);else
DELL.com.Utils.Initialize(function(){getConfigOptions(overrides);});};var getConfigOptions=function(overrides){var isPlris=($('.plris').length>0);var ps=DELL.com.Delphi.PageSettings;var productCode=$("#productCode").attr("value"),params="c="+ps.lwp.Country;params+="&l="+ps.lwp.Language;params+="&s="+ps.lwp.Segment;params+="&cs="+ps.lwp.CustomerSet;params+="&productCode="+productCode;if($(".mag #notification-anchor").length>0&&!isPlris)
params+="&stackPriceTemplate=products/productStack/stack_mag_pd";else params+="&stackPriceTemplate=products/productStack/"+((isPlris&&!$("#magCompareTray").length)?"stack_pol":"stack_mag");if($("div.plris").length&&!$('.singleConfig').length)params+="&priceTemplate=products/productStack/stack_pol_simple";params+="&moduleTemplate=products/ProductDetails/mag/config_popup_mag";params+="&modErrorTemplate=products/module_option_validation";params+="&resultType=SpecsOnly";params+="&overrides="+encodeURIComponent(overrides);params+=($prcBr.length==0)?"&zombiePriceTemplate=products/productdetails/mag/pd_zombie_bar_item_mag":"&zombiePriceTemplate=products/productdetails/mag/price_bar";var url=ps.APIRoot+"configService.svc/postconfigurations/json";$.ajax({type:'POST',dataType:"json",url:url,data:params,error:function(req){configTab.find('.dropdown').each(function(){DELL.com.Mag.ConfigTab.LoadStatus(this,false);});},success:function(configsData){configTab.find('.dropdown').each(function(){DELL.com.Mag.ConfigTab.LoadStatus(this,false);});$.each(configsData,function(index,req){if(req.ProductHubSpecs!=null){$.each(req.ProductHubSpecs,function(index,data){var cSpec=$(".spec\\~"+DELL.com.Utils.getUidFromOC(data.OrderCode)+"\\~"+data.ModuleId);cSpec.text(data.LongSpec);var cSpecIndex=cSpec.parent().attr('data-specindex');$('.specContent[data-specindex="'+cSpecIndex+'"]:visible').height('');if(isPlris&&!$('.singleConfig').length){$('.configStackPage').each(function(){DELL.com.Mag.ConfigTab.FindDifferentSpecs(cSpecIndex,$(this));});}else{DELL.com.Mag.ConfigTab.FindDifferentSpecs(cSpecIndex);}});}
var reqUid=DELL.com.Utils.getUidFromOC(req.OrderCodeId);var configColumn=$('#configOc_'+reqUid);var productDiv=configColumn.find('.pStack:not(#prcBar)');productDiv.html(req.StackPriceHtml);if(isPlris&&!$('.singleConfig').length){var columnId=configColumn.attr('id'),productDivs=$('.'+columnId).not(configColumn).find('.pStack:not(#prcBar,.simpleStack)'),priceDivs=$('.'+columnId).find('.simpleStack');productDivs.html(req.StackPriceHtml);priceDivs.html(req.PriceHtml);}else if(isPlris){var $err=$(req.StackPriceHtml).find('.modErrBlock');if($err.length>0&&$('.modErrBlock').length==0)
$('.errBlock').append($err);else if($err.length==0)
$('.errBlock').html('');}
$('.pStack:visible').height('');if($("#magCompareTray").length<=0){productDiv.find('.secondaryNav').remove();productDiv.find('.pStackHeader a').contents().unwrap();productDiv.find('.qvLnk').remove();productDiv.find('.configImg a').contents().unwrap();DELL.com.Mag.ConfigTab.FixSpecHeight(true);}
if($prcBr.length==0){DELL.com.Mag.ZombiePd.updateStack($('.configOc_'+reqUid,'.configRemoteCarousel'),req.ZombiePriceHtml);}else{updatePrcBar($prcBr,req.ZombiePriceHtml);DELL.com.Init.InitLinks($prcBr);}
DELL.com.Init.InitLinks(configColumn);});$(".primaryBtn .btn, .defaultPrimaryBtn .btn, .pStack .purchase, .pStack .secondaryNav").unbind("click").bind("click",function(){if($(this).hasClass("disabled"))return false;});DELL.com.Mag.ConfigTab.BindMetrics();$(".modErrBlock, .defaultModErrBlock").unbind("click").bind("click",function(){var object=$(this);$(".modPopUpClose").click();if($("#magCompareTray, .plris #compareGrid").length>0){configCompareSlot=$(this).closest('th').index();}
$('html, body').animate({scrollTop:object.offset().top-80},1000);DELL.com.Mag.ConfigTab.magShowInvalidModules(this);});}});};this.ShowConfigTab=function(){if(configTab.length==0)
configTab=$('.configTab');configTab.find('.loadingIcon').hide();configTab.find('#magTechSpecsActions').show();DELL.com.Utils.Initialize(DELL.com.Mag.ConfigTab.FixSpecHeight,true);};this.FixSpecHeight=function(force){var cTab=configTab[0];var csPages=DELL.com.Mag.Utils.GetElementBy('class','configStackPage',cTab);var csVisiblePage;for(var i=0;i<csPages.length;i++){if(DELL.com.Mag.Utils.IsVisible(csPages[i])){csVisiblePage=csPages[i];break;}}
if(!csVisiblePage)return;var $csVisiblePage=$(csVisiblePage);if($csVisiblePage.hasClass('hFixed')&&!force)return;var cBody=DELL.com.Mag.Utils.GetElementBy('class','configStackBody',csVisiblePage)[0];var items=DELL.com.Mag.Utils.GetElementBy('class','configStackItem',cBody);var vTags=['div','h2'];var vClasses=['configStackItem','pStack','pStackHeader','tsStack','specTitle','specContent','iconography','psDesc','discDets','priceBlock','switchCTA','errBlock'];if($('.plris').length)vClasses.push('recContainer','ignored','additionalFields');DELL.com.Mag.Utils.AdjustHeight(items,false,{vClasses:vClasses,vTags:vTags});$(csVisiblePage).addClass('hFixed');var anchorZone=$('#AnchorZone1');var expandDiv=anchorZone.find('.expandable');var maxHeight=DELL.com.Mag.ExpandCollapse.GetMaxHeight(expandDiv);if(anchorZone.find('.expandCollapse').length>0){var newHeight=anchorZone.find('.configTab').height();expandDiv.attr('data-fullheight',newHeight);expandDiv.height(anchorZone.find('.expandCollapse').hasClass('collapse')?newHeight:maxHeight);}
DELL.com.Mag.ConfigTab.BindEvents();DELL.com.Init.InitLinks($csVisiblePage);cBody=null;items=null;anchorZone=null;expandDiv=null;csPages=null;};var onload={initialize:function(){DELL.com.Mag.ConfigTab.LoadSelectedOptions();DELL.com.Mag.ConfigTab.ShowConfigTab();DELL.com.Mag.ConfigTab.BindEvents();DELL.com.Init.InitLinks(configTab);if($("#sliding_tabs").length>0){DELL.com.Mag.ExpandCollapse.CreateButtons('#AnchorZone1');}}};onload.initialize();}).call(DELL.com.Mag.ConfigTab);})(jQuery);
if (window.console){console.log('ex time: config_tab_mag.js', new Date().getTime() - startTScript);}



/*script:similar_models_mag.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.Mag=DELL.com.Mag||{};DELL.com.Mag.Utils=DELL.com.Mag.Utils||{};DELL.com.Mag.SimilarModels=DELL.com.Mag.SimilarModels||{};(function($){(function(){LoadSimilarModelEvents=function(){var items=Array(".pStackThumb",".pStackHeader",".pStackDesc",".pStack");var similarModels=$('.similarModels');similarModels.find('.similarModelsBody').show();for(var i=0;i<items.length;i++)DELL.com.Mag.Utils.MaxHeight($(items[i],similarModels));similarModels.find('.loadingIcon').hide();similarModels.find(".similarModelsPage").hide();similarModels.find("#similarModelsPage_1").show();similarModels.find('.magPagination').show();similarModels.find(".similarModelsItem.c3").last().addClass("lastOne");$(".similarModels .similarModelsPage .magPage").click(function(){var id=$(this).attr("id").substr(2);$(".similarModelsPage").hide();$("#similarModelsPage_"+id).show();for(var i=0;i<items.length;i++)DELL.com.Mag.Utils.MaxHeight($(items[i],similarModels));});}
onload={initialize:function(){LoadSimilarModelEvents();}};$(window).load(function(){LoadSimilarModelEvents();});$('document').ready(function(){DELL.com.Utils.Initialize(onload);});}).call(DELL.com.Mag.SimilarModels);})(jQuery);
if (window.console){console.log('ex time: similar_models_mag.js', new Date().getTime() - startTScript);}



/*script:product_family_mag.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.Mag=DELL.com.Mag||{};DELL.com.Mag.Utils=DELL.com.Mag.Utils||{};DELL.com.Mag.ProductFamily=DELL.com.Mag.ProductFamily||{};(function($){(function(){this.FixStacksHeight=function(){$('.mag #productFamily .productFamilyStack').each(function(){var $this=$(this),OCs=$this.find('.orderCodeCard'),modelCard=$this.find('.modelCard'),purchase=modelCard.find('.purchase'),color=$this.attr('class').split(" ")[1],image=modelCard.find('.configImgPF'),modelCardPurchaseBtnW=purchase.find('strong').width();purchase.addClass('centered').width(modelCardPurchaseBtnW+2);OCs.addClass(color);$(image).ready(function(){OCs.each(function(){$(this).find('.additionalFields').wrapAll('<div class="additionalBlock" />');});DELL.com.Mag.Utils.MaxHeight(OCs.find('.pStackHeader'));DELL.com.Mag.Utils.MaxHeight(OCs.find('.iconography'));DELL.com.Mag.Utils.MaxHeight(OCs.find('.discDets'));DELL.com.Mag.Utils.MaxHeight(OCs.find('.priceBlock'));DELL.com.Mag.Utils.MaxHeight(OCs.find('.additionalBlock'));DELL.com.Mag.Utils.MaxHeight(OCs);var modelCardH=modelCard.height();var OCsH=OCs.height();if(modelCardH>OCsH){OCs.height(modelCardH);}
else if(OCsH>modelCardH){modelCard.height(OCsH);}});});};onload={initialize:function(){DELL.com.Mag.ProductFamily.FixStacksHeight();if($(".bigHeroImg").length>0)
{$("#productScene7").hide();$(".bigHeroImg").show();$(".magBannerGalleryLink").click(function(){$(".bigHeroImg").hide();$("#productScene7").show();DELL.com.Scene7.init();$(this).hide();});}
else
{$("#productScene7").show();}}};DELL.com.Utils.Initialize(onload);}).call(DELL.com.Mag.ProductFamily);})(jQuery);
if (window.console){console.log('ex time: product_family_mag.js', new Date().getTime() - startTScript);}



/*script:zombie_mag.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.Mag.ZombiePd=DELL.com.Mag.ZombiePd||{};(function($){(function(){var zombieStart="";var zombieStop="";var $az1=null;var $sCta=null;var $cTab=null;var $expnd=null;this.calculateZombiePosition=function(){$sCta=$(".switchCTA");$expnd=$(".expandable");zombieStart=$(".tsStack").offset().top;if($az1.find(".singleConfig").length>0){var $stack=$az1.find(".pStack");zombieStart=parseInt($stack.offset().top)+parseInt($stack.height());}
if($sCta.length>0){var $switchCTA=$sCta.filter(":visible");if($switchCTA.length>0)
zombieStart=parseInt($switchCTA.offset().top)+parseInt($switchCTA.height());}
if(($az1.find(".expandable").length>0)&&($expnd.attr("data-fullheight")!==undefined))
zombieStop=parseInt($cTab.offset().top)+parseInt($expnd.attr("data-fullheight"));else
zombieStop=parseInt($cTab.offset().top)+parseInt($cTab.height());};this.showPage=function(pageNumber){$(".remoteCarouselPage").addClass("hide");$("#remoteCarouselPage_"+pageNumber).removeClass("hide");DELL.com.Mag.ZombiePd.calculateZombiePosition();};this.updateStack=function($target,content){$target.html(content);};this.renderZombie=function(){$az1=$("#AnchorZone1");$sCta=$(".switchCTA");$expnd=$(".expandable");var isZombieEnable=false;var isExapandable=$az1.find(".expandable").length;var expanded=true;var hideZombie=false;DELL.com.Mag.ZombiePd.calculateZombiePosition();var windowPosition="";if($cTab.length>0){var $window=$(window);$("#remoteCarouselPage_1").removeClass("hide");$window.scroll(function(){if(isZombieEnable){windowPosition=$(window).scrollTop();if(isExapandable>0){if($az1.find(".expand").length>0)
hideZombie=true;}
if((windowPosition<zombieStart)||(windowPosition>zombieStop)||hideZombie){isZombieEnable=false;hideZombie=false;$(".configRemoteCarousel").addClass("hide");}}else{windowPosition=$(window).scrollTop();if(isExapandable>0){if($az1.find(".collapse").length>0)
expanded=true;else expanded=false;}
if((windowPosition>zombieStart)&&(windowPosition<zombieStop)&&expanded){isZombieEnable=true;$(".configRemoteCarousel").removeClass("hide");}}});}};var onload={initialize:function(){var $plris=$("div.plris");$cTab=$(".configTab");if($cTab.length>0&&$plris.length==0)
DELL.com.Mag.ZombiePd.renderZombie();}};DELL.com.Utils.Initialize(onload);}).call(DELL.com.Mag.ZombiePd);})(jQuery);
if (window.console){console.log('ex time: zombie_mag.js', new Date().getTime() - startTScript);}



/*script:anchoredContent.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.anchoredContent=DELL.com.anchoredContent||{};(function($){(function(){var $this=this;var $anchors=$('.anchoredContentContainer');var currentID=0;var tabInit=false;var isPlris=($('.plris').length>0);this.init=function(){var findAlienware=$("body.alienwareFranchise");var isAlienware=false;if(findAlienware.html()!=null&&findAlienware.html().length>0){isAlienware=true;}
anchoredTabs={activateTabs:function(_id){DELL.com.RUM.startTimer("activateTabs");var anchors=$anchors.filter(":gt(0)");var tabbedTabs=$(".tabbed_nonFeaturedAnchor");var activeTab=$(".tabbed_active");var activeArrow=$(".tabbed_active div.tabbed_arrow");var activeHeadline=$(".tabbed_active a div");var nonActiveHeadlines=$("tabbed_nonFeaturedHeadline");var tabDivider=$(".tabbed_divider");var lastTabDivider=tabDivider.last();tabDivider.eq(0).show();for(i=0;i<5;i++){tabDivider.eq(i).css("border-left","1px solid #0085c2");}
if(isAlienware){tabDivider.eq(_id).css("border-left","1px solid #000");tabDivider.eq(_id-1).css("border-left","1px solid #000");}else{tabDivider.eq(_id).css("border-left","1px solid #FFF");tabDivider.eq(_id-1).css("border-left","1px solid #FFF");}
lastTabDivider.hide();anchors.hide();activeArrow.remove();activeHeadline.removeClass("tabbed_headline_active");activeTab.removeClass('tabbed_active');tabbedTabs.eq(_id).addClass('tabbed_active');tabbedTabs.eq(_id).append("<div class='tabbed_arrow'></div>");var newActiveHeadline=$(".tabbed_active a div");newActiveHeadline.addClass('tabbed_headline_active');DELL.com.RUM.endTimer("activateTabs");},displayTabs:function(){DELL.com.RUM.startTimer("displayTabs");var anchors=$anchors.filter(":gt(0)");var dividers=$(".anchored_clearFloats");var lastDivider=$(".anchored_clearFloats:last");var dividerBG=$anchors;var firstTab=$(".tabbed_nonFeaturedAnchor:lt(1)");var anchorDividers=$(".anchored_returntotop");var anchoredCarouselContainer=$(".anchorCarouselContainer");var tabContainers=$(".tabbed_nonFeaturedHeadline:lt(1)");var tabs=$(".tabbed_nonFeaturedAnchor");var tabDivider=$(".tabbed_divider");var menuTitle=$(".tabbed_title");var billboardThumbs=$(".billboardThumbs");var myTitlePosition=((anchors.width()/2)-(menuTitle.width()/2))-30;if(myTitlePosition>0){menuTitle.css("left",myTitlePosition+"px");}
var tabbedWidth=0;if(tabs.length>6){tabbedWidth=(6)*150;}else{tabbedWidth=(tabs.length)*150;}
var myMenuPosition=0;if(menuTitle.width()===null){myMenuPosition=((anchors.width()/2)-(tabbedWidth/2))-10;}else{myMenuPosition=((anchors.width()/2)-(billboardThumbs.width()/2))-10;}
billboardThumbs.css("margin-top","15px");billboardThumbs.css("position","relative");billboardThumbs.css("float","left");if(myMenuPosition>0){billboardThumbs.css("left",myMenuPosition+"px");}
anchorDividers.hide();tabDivider.eq(0).hide();tabDivider.eq(5).hide();dividerBG.css("clear","both");anchors.css("min-height","270px");dividers.hide();lastDivider.show();var myHeight=0;$('.tabbed_nonFeaturedAnchor').each(function(index){$(this).removeClass("round").addClass("roundNoBorder");var newHeight=$(this).height();if(newHeight>myHeight){myHeight=newHeight;}});$(tabDivider).css("min-height",(myHeight-18)+"px");$('.tabbed_nonFeaturedAnchor').css("min-height",myHeight+"px");if(isAlienware){$('.tabbed_anchorGradientBG').addClass("tabbed_anchorGradientBG_alienware");}
tabbedContent.show();DELL.com.RUM.endTimer("displayTabs");}}
var tabbedContent=$(".anchorTabbedMenu");$('[class*=linkAnchor_]').each(function(index){$(this).click(function(){var myClass=$(this).attr('class');var myTargetClass=myClass.split("_");if(tabbedContent.length>0){anchoredTabs.activateTabs(index);var targetTop=$('.anchor_'+myTargetClass[1]);var target=$('.'+myTargetClass[1]);var anchors=$(".anchoredContentContainer:gt(0)");var dividers=$(".anchored_clearFloats");var lastDivider=$(".anchored_clearFloats:last");anchors.hide();dividers.hide();lastDivider.show();targetTop.eq(0).parent().show('fast',function(){$("img.lazy").show().lazyload();$('img.lazy').lazyload();$('img.lazy').each(function(index){var tmp_attr=$(this).attr('data-original');$(this).attr('src',tmp_attr);});});}else{var container=$('html');var targetTop=$('.anchor_'+myTargetClass[1]).offset().top;var speedTarget=500;$('html, body').animate({scrollTop:targetTop},speedTarget);}
return false;});});$('.anchored_returntotop a').each(function(index){$(this).click(function(e){e.preventDefault();var myClass=$(this).attr('class');var myTargetClass=myClass.split("_");var container=$('html');var targetTop=$('.topAnchored').offset().top-235;var speedTarget=500;$('html, body').animate({scrollTop:targetTop},speedTarget);return false;});});$('.threeImageLearnMore .btn').each(function(index){$(this).click(function(){var myTargetA=$(this).attr('href');var myWindowA=$(this).attr('target');if(myWindowA!==null&&myWindowA!=="_self"){var myNewWindowA=window.open(myTargetA,'LearnMore','width=600,height=600,toolbar=0,menubar=0,location=0');return false;}else{return true;}});});$('.leftRight_MainCopy .btn').each(function(index){$(this).click(function(){var myTarget=$(this).attr('href');var myWindow=$(this).attr('target');if(myWindow!==null&&myWindow!=="_self"){var myNewWindow=window.open(myTarget,'LearnMore','width=600,height=600,toolbar=0,menubar=0,location=0');return false;}else{return true;}});});if(tabbedContent.length>0){var nonFeatured=$(".tabbed_nonFeaturedAnchor");var billboardTabs=$(".billboardThumbs:lt(1)");var firstTab=$(".tabbed_nonFeaturedAnchor a");$(".tabbed_topAnchored").append(billboardTabs);nonFeatured.css("visibility","visible").fadeIn(1000);anchoredTabs.displayTabs();$(firstTab).eq(0).click();}else{var content=$(".featuredAnchor");$(".topAnchored").append(content);content.css("visibility","visible").fadeIn(1000);var nonFeatured=$(".nonFeaturedAnchor");$(".topAnchored").append(nonFeatured);nonFeatured.css("visibility","visible").fadeIn(1000);var anchors=$(".anchoredContentContainer");anchors.show();$('img.lazy').lazyload({effect:"fadeIn"});}
$('.anchorCarousel').each(function(index){var myClass=$(this).attr('class');$(this).attr('class',myClass+' anchorCarousel_'+index);DELL.com.RUM.startTimer("anchorCarousel.initCarousel");initCarousel($(this));DELL.com.RUM.startTimer("anchorCarousel.initCarousel");});function initCarousel(carouselID){var mainAnchoredCarousel=carouselID;var anchoredCarouselContainer=$(mainAnchoredCarousel).find(".anchorCarouselContainer");var carousel=anchoredCarouselContainer;var carouselImages=$(anchoredCarouselContainer).find('.mainAnchorCarouselImage');var imgCarouselTitle=$(anchoredCarouselContainer).find('.imgCarouselTitle');var imgCarouselDesc=$(anchoredCarouselContainer).find('.imgCarouselDesc');var carouselItems=carouselImages.length;var carouselImageLast=carouselImages.last();var carouselImageFirst=carouselImages.first();var carouselImageWidth=!isPlris?648:902;var carouselMaxScroll=(carouselItems-2)*carouselImageWidth;var carouselWidth=(carouselItems*carouselImageWidth);carousel.prepend(carouselImageLast);carouselImages.fadeTo('slow',0.3,function(){});imgCarouselTitle.fadeTo('fast',0,function(){});imgCarouselDesc.fadeTo('fast',0,function(){});carouselImageFirst.fadeTo('slow',1,function(){});$(anchoredCarouselContainer).find('.mainAnchorCarouselImage:nth-child(2) .imgCarouselTitle').fadeTo('slow',1,function(){$(anchoredCarouselContainer).find('.mainAnchorCarouselImage:nth-child(2) .imgCarouselDesc').fadeTo('slow',1,function(){});});$(mainAnchoredCarousel).find(".carouselScrollLeft, .carouselScrollRight").hover(function(){$(this).stop().animate({"opacity":".3"},"fast");},function(){$(this).stop().animate({"opacity":"1"},"fast");});carousel.css("width",carouselWidth);var carouselMargin=($('.mag').length>0)?'356':'506';if(isPlris)
carouselMargin=606;carousel.animate({marginLeft:'-'+carouselMargin+'px'},'slow');$(mainAnchoredCarousel).find('.carouselScrollLeft').click(function(){if(!carousel.is(":animated")){checkRightPOS();}});$(mainAnchoredCarousel).find('.carouselScrollRight').click(function(){if(!carousel.is(":animated")){checkLeftPOS();}});function checkLeftPOS(){var currPOS=checkAnchoredCarouselLocation();if(!isPlris&&(parseInt(currPOS)<-600)||(isPlris&&parseInt(currPOS)<-700)){carousel.animate({marginLeft:'+=648px'},'slow',function(){});}else{addLeft();}}
function addLeft(){if(!carousel.is(":animated")){carouselImages.fadeTo('fast',.3,function(){})
imgCarouselTitle.fadeTo('fast',0,function(){})
imgCarouselDesc.fadeTo('fast',0,function(){})
carousel.animate({marginLeft:'-1012px'},0);carousel=$(mainAnchoredCarousel).find(".anchorCarouselContainer");carouselImages=$(mainAnchoredCarousel).find('.mainAnchorCarouselImage');carouselImageLast=carouselImages.last();carouselImageFirst=carouselImages.first();carousel.prepend(carouselImageLast);carouselImageFirst.fadeTo('slow',1,function(){});$(mainAnchoredCarousel).find('.mainAnchorCarouselImage:nth-child(2) .imgCarouselTitle').fadeTo('slow',1,function(){$(mainAnchoredCarousel).find('.mainAnchorCarouselImage:nth-child(2) .imgCarouselDesc').fadeTo('slow',1,function(){});});carousel.animate({marginLeft:'-'+carouselMargin+'px'},'slow',function(){});}}
function checkRightPOS(){var currPOS=checkAnchoredCarouselLocation();addRight();}
function addRight(){carouselImages.fadeTo('fast',.3,function(){})
imgCarouselTitle.fadeTo('fast',0,function(){})
imgCarouselDesc.fadeTo('fast',0,function(){})
carousel.animate({marginLeft:'+=648px'},0);carousel=$(mainAnchoredCarousel).find(".anchorCarouselContainer");carouselImages=$(mainAnchoredCarousel).find('.mainAnchorCarouselImage');carouselImageLast=carouselImages.last();carouselImageFirst=carouselImages.first();carousel.append(carouselImageFirst);$(mainAnchoredCarousel).find('.mainAnchorCarouselImage:nth-child(2)').fadeTo('slow',1,function(){});$(mainAnchoredCarousel).find('.mainAnchorCarouselImage:nth-child(2) .imgCarouselTitle').fadeTo('slow',1,function(){$(mainAnchoredCarousel).find('.mainAnchorCarouselImage:nth-child(2) .imgCarouselDesc').fadeTo('slow',1,function(){});});carousel.animate({marginLeft:'-=648'},'slow',function(){});}
function checkAnchoredCarouselLocation(){var myPOS=carousel.css("margin-left");return myPOS;}}};if($anchors.length>0){DELL.com.RUM.startTimer("DELL.com.anchoredContent");$this.init();DELL.com.RUM.endTimer("DELL.com.anchoredContent");}}).call(DELL.com.anchoredContent);})(jQuery);
if (window.console){console.log('ex time: anchoredContent.js', new Date().getTime() - startTScript);}



/*script:module_upsell.js*/
var startTScript=new Date().getTime ();

var DELL=window.DELL||{};DELL.com=DELL.com||{};DELL.com.ModuleUpsell=DELL.com.ModuleUpsell||{};(function($){(function(){var $prcBr=$('#prcBar');DELL.com.ModuleUpsell.LoadSpeedBumpEvents=function()
{var moduleUpsellContactText=$(".moduleUpsellChatText");if(moduleUpsellContactText!=null)
$(".moduleUpsellChatText").html($(".help").html());DELL.com.ProductHubModuleUpsell.BindOptionHover(null);BindModuleUpsellInputs(null);BindConfigTabs();if($("#magCompareTray, .plris #compareGrid").length>0)
{$(".primaryBtn .btn, .defaultPrimaryBtn .btn, .pStack .purchase, .pStack .secondaryNav").unbind("click").bind("click",function(){if($(this).hasClass("disabled"))return false;});$(".compareCTA, .pStack .purchase").click(function(){configCompareSlot=$(this).closest('th').index();});$(".zombiePage .btn").click(function(){configCompareSlot=$(this).closest('td').index()+1;});}
var modErr=$(".modErrors .mod-upsell-compat-instr");if(modErr.length>0)
{$(".moduleUpsellContainer .mod-upsell-compat-instr").html($(".moduleUpsellContainer .mod-upsell-compat-instr").html().replace(/modlink/gi,"span class=\"modlink\" "));var modLinks=$(".moduleUpsellContainer .mod-upsell-compat-instr").find(".modlink");var ocId=$("#currentOC").attr("value");if(modLinks!=null&&modLinks.length>0)
{modLinks.each(function(index,data){var linkId=$(data).attr("id");var linkText=$(data).html();$(data).attr("id",ocId+"Mod"+linkId);});}
$.each(modLinks,function(index,data){var compatInstrDiv=$("#"+$(data).attr("id")+"Container");if(compatInstrDiv.length>0)
{var compatInstrDivHtml=$(".moduleUpsellContainer .mod-upsell-compat-instr").html();$(".moduleUpsellContainer .mod-upsell-compat-instr").remove();$(compatInstrDiv).prepend("<div class=\"mod-upsell-compat-instr\" >"+compatInstrDivHtml+"</div>");$(".moduleUpsellContainer .mod-upsell-compat-instr .modlink").unbind("click").bind("click",function(){scrollToModule($(this));});scrollToModule(data);return false;}});$(".modelUpsellPrice .candyAisleLink").addClass("disabled");}}
BindConfigTabs=function()
{$(".configurationTab").click(function(e){if($(this).hasClass("selected"))
{e.preventDefault();return false;}
else
{var tab=$(this).attr("id");var moduleContainer="#"+tab.replace("configurationTab_","moduleContainer_");$(".configurationTab").removeClass("selected");$(this).addClass("selected");$(".moduleContainer").addClass("hidden");$(moduleContainer).removeClass("hidden");return true;}});},BindModuleUpsellCTA=function()
{$(".modelUpsellPrice .candyAisleLink").click(function(e){if($(this).hasClass("disabled"))
{return false;}
else
{changeModuleUpsellModalState(false);return true;}});},BindModuleUpsellInputs=function(ocId){$(".moduleUpsellContinueBtn").click(function(){if($(this).hasClass("disabled"))
{return false;}
$(".closeWindow").click();});BindModuleUpsellCTA();var modOptionsObj=null;if(ocId==null)
{modOptionsObj=$(".moduleContainer .catContent .content .modOption");}
else
{modOptionsObj=$("#moduleContainer_"+ocId+" .catContent .content .modOption");}
$(modOptionsObj).bind("click",function(e){var obj=$(this).parents(".moduleContainer");var ocId=$(obj).find("#currentOC").attr("value");var ocUid=DELL.com.Utils.getUidFromOC(ocId)||DELL.com.Utils.getUidFromOC(ocId.toUpperCase())||DELL.com.Utils.getUidFromOptId(ocId.toUpperCase());obj=$(this).parents(".warrantyModal");var modId=$(obj).attr("id").replace(ocUid+"_mod_","");obj=$(this).parents(".catContent");var option=$(obj).find(".content").attr("id");var checked=$(this).attr("checked")=="checked";var inputType=$(this).attr("type");var multiSelect=false;if(inputType&&inputType!="radio")
multiSelect=true;var ccMod=null;if($("#ccModule").length>0)
{ccMod=$("#ccModule").attr("value");}
var snpId=ocId;if($(".candyAislePageContainer").length>0){snpId=$("input.ccId[value="+ocId+"]").siblings(".snpId").attr("value");}
DELL.com.ProductHubModuleUpsell.UpdateOverrides(snpId,modId,option,multiSelect,checked);if($(".candyAislePageContainer").length>0)
{var prodStacks=$("#SKU"+ocId.toUpperCase());if(DELL.com.ProductHubModuleUpsell.GetOverrides().indexOf(snpId.toUpperCase()+"^")<0)
{$("#SKU"+snpId+" .mod[value='"+ccMod+"']").parent().find(".snpCompositeConfig a span").html($("#eaCCAddOption").attr("value"));}
else
{$("#SKU"+snpId+" .mod[value='"+ccMod+"']").parent().find(".snpCompositeConfig a span").html($("#eaCCEditOption").attr("value"));}}
UpdateWarrantyModalPrice(ocId,modId);DELL.com.ProductHubModuleUpsell.SwitchImage(obj);var isDefault=false;var defaultOptions=$("#"+ocUid+"DefaultOptions").attr("value");if(defaultOptions!=null&&defaultOptions!="")
isDefault=defaultOptions.indexOf(modId+"~"+option)>=0;DELL.com.Utils.Metrics.logSSBMod(option,modId,isDefault,true);});},changeModuleUpsellModalState=function(state)
{if(state)
{$(".moduleUpsellContainer input").removeAttr("disabled");$(".modelUpsellPrice .candyAisleLink").removeClass("disabled");$(".modelUpsellPrice .moduleUpsellContinueBtn").removeClass("disabled");$("#trailimageid").css("z-index","");}
else
{$(".moduleUpsellContainer input").attr("disabled","disabled");$(".modelUpsellPrice .candyAisleLink").addClass("disabled");$(".modelUpsellPrice .moduleUpsellContinueBtn").addClass("disabled");$("#trailimageid").css("z-index","10000010");}},UpdateWarrantyModalPrice=function(ocId,modId)
{var isPlris=($('.plris').length>0);changeModuleUpsellModalState(false);$j(document).bind('mousemove',followmouse);var ps=DELL.com.Delphi.PageSettings;var lwpc=ps.lwp.Country;var lwpl=ps.lwp.Language;var lwps=ps.lwp.Segment;var lwpcs=ps.lwp.CustomerSet;var uId=DELL.com.Utils.getUidFromOC(ocId)||DELL.com.Utils.getUidFromOC(ocId.toUpperCase())||DELL.com.Utils.getUidFromOptId(ocId.toUpperCase());var sysOC=$("#currentOC").attr("value");var sysUid=DELL.com.Utils.getUidFromOC(sysOC);var ccOC=(ocId!=sysOC)?ocId:"";var ccUid=DELL.com.Utils.getUidFromOptId(ccOC.toUpperCase());var productCode=$("#productCode").attr("value");var isEditMode=$("#cartItemId").length>0&&$("#cartItemId").val().length>0;var params="c="+lwpc;params+="&l="+lwpl;params+="&s="+lwps;params+="&cs="+lwpcs;params+="&oc="+sysOC;params+="&modId="+modId;params+="&productCode="+productCode;params+="&priceTemplate=products/module_upsell_price";if($("#magCompareTray, .plris #compareGrid").length>0){params+="&zombiePriceTemplate=products/productdetails/mag/compare_zombie_bar_item_mag";}
else if($("#sliding_tabs").length>0){if(isPlris){params+=($prcBr.length==0)?"&zombiePriceTemplate=products/productStack/stack_pol_simple":"&zombiePriceTemplate=products/productdetails/mag/price_bar";}else{params+=($prcBr.length==0)?"&zombiePriceTemplate=products/productdetails/mag/pd_zombie_bar_item_mag":"&zombiePriceTemplate=products/productdetails/mag/price_bar";}}
else
{params+=($prcBr.length==0)?"&zombiePriceTemplate=products/productdetails/product_hub/hub_zombie_bar_price":"&zombiePriceTemplate=products/productdetails/mag/price_bar";}
params+="&moduleTemplate=products/module_upsell_modules";params+="&modErrorTemplate=products/module_option_validation";params+="&resultType=AllUpsellModules";if($(".candyAislePageContainer").length>0)
{params+="&stackPriceTemplate=products/module_upsell_price";}
else if(isEditMode&&ps.PageSubType!="hub")
{params+="&stackPriceTemplate=products/pd_hero_price";}
else if($(".mag").length>0)
{if($("#magCompareTray").length>0){params+="&stackPriceTemplate=products/compare/comparison_table_item_mag";}
else if($(".plris #compareGrid").length>0){params+="&stackPriceTemplate=products/compare/comparison_table_item_pol";}
else
{params+="&stackPriceTemplate=products/productStack/"+(isPlris?"stack_pol":"stack_mag");}}
else
{params+="&stackPriceTemplate=products/productdetails/product_hub/productdetails_config_3x_price";}
if(!$(".moduleUpsellContainer").hasClass("compositeConfigModContainer"))
{if($(".mag #notification-anchor").length>0)
params+="&uiParameters="+encodeURIComponent("IsCompositeModuleUpsell=false&_showAddToCartPrimary=true&_switchCTA=true");else
params+="&uiParameters="+encodeURIComponent("IsCompositeModuleUpsell=false");}
else if($(".candyAislePageContainer").length>0){DELL.com.CandyAisle.SetOptionSelectionsChanged(true);params+="&uiParameters="+encodeURIComponent("IsCandyAisle=true&IsCompositeModuleUpsell=false&OptionSelectionsChanged="+true);}else{if($(".mag #notification-anchor").length>0)
params+="&uiParameters="+encodeURIComponent("_showAddToCartPrimary=true&_switchCTA=true");}
if(ccOC!=null&&ccOC!="")
params+="&cc="+ccOC;var overrides=DELL.com.ProductHubModuleUpsell.GetOrderCodeOverrides(sysOC);if($("#magCompareTray, .plris #compareGrid").length>0){var stack=$("#compareGrid th:nth-child("+(configCompareSlot+1)+")");if(stack.find(".overrides").length>0){stack.find(".overrides").val(overrides);}
else
{stack.append("<input type='hidden' value='"+overrides+"' class='overrides'>");}}
if(overrides!=null&&overrides!="")
params+="&overrides="+encodeURIComponent(overrides);var url=ps.APIRoot+"configService.svc/postmoduleoverrides/json";$.ajax({type:'POST',dataType:"json",url:url,data:params,error:function(req){$j(document).unbind('mousemove',followmouse);hidetrail();changeModuleUpsellModalState(true);},success:function(req){$j(document).unbind('mousemove',followmouse);hidetrail();changeModuleUpsellModalState(true);$("#topPriceContainer").html(req.PriceHtml);$("#bottomPriceContainer").html(req.PriceHtml);$("#moduleContainer_"+uId).html(req.ModulesHtml);var instrContainerId="#"+uId+"Mod"+modId+"Container";if(req.ModOptionErrorHtml!=null&&req.ModOptionErrorHtml!="")
{var $icr=$(instrContainerId);$(".modelUpsellPrice .candyAisleLink").addClass("disabled");$(".moduleUpsellContainer .mod-upsell-compat-instr").remove();$icr.prepend(req.ModOptionErrorHtml);$(".moduleUpsellContainer .mod-upsell-compat-instr").html($(".moduleUpsellContainer .mod-upsell-compat-instr").html().replace(/modlink/gi,"span class=\"modlink\" "));var modLinks=$(".moduleUpsellContainer .mod-upsell-compat-instr").find(".modlink");if(modLinks!=null&&modLinks.length>0)
{modLinks.each(function(index,data){var linkId=$(data).attr("id");var linkText=$(data).html();$(data).attr("id",uId+"Mod"+linkId);});}
$(".moduleUpsellContainer .mod-upsell-compat-instr .modlink").unbind("click").bind("click",function(){scrollToModule($(this));});$(".modelUpsellPrice .candyAisleLink").addClass("disabled");var $modErrCtr=$icr.find('.mod-upsell-compat-instr .yellowContainer .il');var oh=$modErrCtr.height();$modErrCtr.height('auto');if($modErrCtr.height()>294)
$icr.find('.leftCol').height($modErrCtr.height()-20);else
$modErrCtr.height(oh);}
else
{$(".modelUpsellPrice .candyAisleLink").removeClass("disabled");$(".moduleUpsellContainer .mod-upsell-compat-instr").remove();}
DELL.com.ProductHubModuleUpsell.BindOptionHover(uId);BindModuleUpsellInputs(uId);if($(".mag").length>0){DELL.com.ProductHubModuleUpsell.UpdateMagCTAAndModules(sysUid,req);}
else if($(".compareContainer").length>0||$(".hubConfigStack").length>0)
{DELL.com.ProductHubModuleUpsell.UpdateCTAAndModules(sysUid,req);}
else if(isEditMode)
{if($(".prodHeroPrimaryBtn").length>0)
{$(".prodHeroPrimaryBtn").html(req.CTAHtml);$(".productLink").html(req.CTAHtml);}
if($(".offerPrice").length>0)
{$(".offerPrice").html(req.StackPriceHtml);}}
if($(".candyAislePageContainer").length>0)
{$(".candyAislePriceSummaryContainer").html(req.StackPriceHtml);}
if($prcBr.length>0&&DELL.com.Mag.ConfigTab){var $r=$(req.ZombiePriceHtml);$prcBr.find('a.purchase').replaceWith($r.find('a.purchase').first());$prcBr.find('.switchCTA').replaceWith($r.find('.switchCTA'));$prcBr.css('height','auto');}}});},scrollToModule=function(obj)
{var objId=($(obj).attr("id"))+"Container";var compatInstrDiv=$(obj).closest(".mod-upsell-compat-instr");var compatInstrDivHtml=$(compatInstrDiv).html();$(".moduleUpsellContainer .mod-upsell-compat-instr").remove();$("#"+objId).prepend("<div class=\"mod-upsell-compat-instr\" >"+compatInstrDivHtml+"</div>");$(".moduleUpsellContainer .mod-upsell-compat-instr .modlink").click(function(){scrollToModule($(this));});var element=document.getElementById(objId);var docViewTop=$(window).scrollTop();var docViewBottom=docViewTop+$(window).height();var elemTop=$("#"+objId).offset().top;var elemBottom=elemTop+$("#"+objId).height();if((elemBottom>docViewBottom)||(elemTop<docViewTop))
{if(element!=null)
{element.scrollIntoView(true);}}
return false;}}).call(DELL.com.ModuleUpsell);})(jQuery);
if (window.console){console.log('ex time: module_upsell.js', new Date().getTime() - startTScript);}


