/*
 Copyright &copy; 2000-2014 by <a href=\"http:\/\/www.webcollage.com\/\">Webcollage Inc.<\/a> All rights reserved.
 Protected by US Patent 6,865,593 and pending patent applications
*/
"undefined"==typeof window.Webcollage&&(window.Webcollage={});
(function(k){function p(a,c,b){if("undefined"!=typeof a)for(var f=0;f<b.length;++f)"undefined"!=typeof a[b[f]]&&(c[b[f]]=a[b[f]])}function q(a,c){var b=document.createElement("script");b.id=c;b.src=a;b.async=!0;document.getElementsByTagName("head").item(0).appendChild(b)}function s(){var a=window.Webcollage.utils.findSectionsOnPage();return a&&a.length?(a=window.Webcollage.utils.getAttr(a[0],"data-compiler-v"))&&"?ver="+encodeURIComponent(a)||"":""}window.Webcollage.minOrMaxJs=function(a){return 0<
document.location.search.indexOf("webcollage-scripts=max")?a:"true"===k.hasMinJs?a.replace(/\.js$/,".min.js"):window._wccontent&&!0===window._wccontent.hasMinJs?a.replace(/\.js$/,".min.js"):window._wcsite&&window._wcsite.wccontentoverride&&!0===window._wcsite.wccontentoverride.hasMinJs?a.replace(/\.js$/,".min.js"):a};window.Webcollage.minOrMaxCss=function(a){return 0<document.location.search.indexOf("webcollage-scripts=max")?a:window._wccontent&&!0===window._wccontent.hasMinCss?a.replace(/\.css$/,
".min.css"):window._wcsite&&window._wcsite.wccontentoverride&&!0===window._wcsite.wccontentoverride.hasMinCss?a.replace(/\.css$/,".min.css"):a};window.Webcollage.utils={getElementsByClassName:getElementsByClassName=function(a,c,b){getElementsByClassName=document.getElementsByClassName?function(a,b,d){d=d||document;a=d.getElementsByClassName(a);b=b?new RegExp("\\b"+b+"\\b","i"):null;d=[];for(var c,e=0,h=a.length;e<h;e+=1)c=a[e],b&&!b.test(c.nodeName)||d.push(c);return d}:document.evaluate?function(a,
b,d){b=b||"*";d=d||document;var c=a.split(" "),e="",h="http://www.w3.org/1999/xhtml"===document.documentElement.namespaceURI?"http://www.w3.org/1999/xhtml":null;a=[];for(var m,g=0,l=c.length;g<l;g+=1)e+="[contains(concat(' ', @class, ' '), ' "+c[g]+" ')]";try{m=document.evaluate(".//"+b+e,d,h,0,null)}catch(k){m=document.evaluate(".//"+b+e,d,null,0,null)}for(;b=m.iterateNext();)a.push(b);return a}:function(a,b,d){b=b||"*";d=d||document;var c=a.split(" ");a=[];b="*"===b&&d.all?d.all:d.getElementsByTagName(b);
d=[];var e;e=0;for(var h=c.length;e<h;e+=1)a.push(new RegExp("(^|\\s)"+c[e]+"(\\s|$)"));for(var h=0,m=b.length;h<m;h+=1){c=b[h];e=!1;for(var g=0,l=a.length;g<l&&(e=a[g].test(c.className),e);g+=1);e&&d.push(c)}return d};return getElementsByClassName(a,c,b)},getAttr:function(a,c){var b=a.getAttribute&&a.getAttribute(c)||null;if(!b)for(var f=a.attributes,k=f.length,d=0;d<k;d++)f[d].nodeName===c&&(b=f[d].nodeValue);return b},getModularFeedPieces:function(){return getElementsByClassName("wc-aplus-modular")},
findSectionsOnPage:function(){return getElementsByClassName("wc-fragment","div")}};window.Webcollage.loadContent=function(a,c,b,f){window.Webcollage.siteCode==a&&window.Webcollage.cpi==c||"function"!=typeof window.Webcollage.terminatePowerPage||window.Webcollage.terminatePowerPage();window.Webcollage.siteCode=a;window.Webcollage.cpi=c;window.Webcollage.loadContentParams={options:{},callbacks:{}};p(b,window.Webcollage.loadContentParams,["containerSelector","reload"]);p(b,window.Webcollage.loadContentParams.options,
["autoPlayAndStop","site","layout"]);p(b,window.Webcollage.loadContentParams.callbacks,["hasPowerPageContentCallback","noPowerPageContentCallback","resizeCallback"]);f&&"function"==typeof f&&(window.Webcollage.loadContentParams.callbacks.onContentLoad=f,window.Webcollage.loadContentOnLoadCallbackProvided=!0);try{a=a&&"string"==typeof a?encodeURIComponent(a):"";c=c&&"string"==typeof c?encodeURIComponent(c):"";var r=b&&b.testMode&&!0===b.testMode,d=b&&b.source&&"page"===b.source;""!=a&&""!=c&&window.setTimeout(function(){d&&
null==document.getElementById("wc-loaded-acssite")?q(window.Webcollage.minOrMaxJs(k.cgRoot+"/"+a+"/resources/connections/aplus/js/"+("true"===k.isSecured?"acssite@s.js":"acssite.js"))+s(),"wc-loaded-acssite"):null!=document.getElementById("wcpp-load-content")||q(k.serverRoot+"/"+a+"/api/js/method/load-content/type/ppp?environment=live&cpi="+c+(r?"&site-mode=test":""),"wcpp-load-content");r||(window.Webcollage.reportPageView=function(b,d){var f=b||{};f["content-package"]=
"ppp";document.domain.length&&(f["page-domain"]=document.domain);document.referrer.length&&(f["referrer-domain"]=document.referrer.split("/")[2]);var g=k.dsplyRoot+"&e=product-detail-page-view&site="+a+"&cpi="+c;if(d)for(var l=0;l<d.length;l++){var n=d[l];n.vendorName&&(g+="&mpn="+encodeURIComponent(n.vendorName));n.prodCategory&&(g+="&prod-category="+encodeURIComponent(n.prodCategory))}window.setTimeout(function(){var a=g,b=f||{};b.localtimestamp=(new Date).valueOf()+"";for(var c in b)a+="&"+encodeURIComponent(c)+
"="+encodeURIComponent(b[c]);"undefined"==typeof document.wcImgs&&(document.wcImgs=[]);b=new Image;b.src=a+"&_sof";document.wcImgs.push(b)},0)})},0)}catch(t){}}})({isSecured:"false",relRoot:"http:\/\/rel.webcollage.net\/apps\/el",dsplyRoot:"https:\/\/www.dsply.com\/index.php?pid=rv4a0pklnx",serverRoot:"http:\/\/content.webcollage.net",cgRoot:"http:\/\/content.webcollage.net",hasMinJs:"true"});
