var commerceItemId;
var fullyLoaded=false;
var emailPattern=new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);
$(document).ready(function(){fullyLoaded=true;
$("div .navContainer .nav .nav-Cat a").click(function(event){var href=setUpNavigationTrackingCookie("top",this);
window.location.href=href;
return false;
});
$.get("/global/gadgets/minicartHeader.jsp?r="+Math.random(),function(html){var cartIcon=$(html).find("#cartIcon").attr("class");
var totalCommerceItemCount=$(html).find(".item-amount").html();
var merchandiseSubtotal=$(html).find(".price").html();
$("#cartIcon").attr("class",cartIcon);
$("#minicartHeader .header .item-amount").html(totalCommerceItemCount);
$("#minicartHeader .header .price").html(merchandiseSubtotal);
});
$(".ajaxButton").live("click",function(e){e.preventDefault();
buttonId=$(this).attr("id");
if(typeof buttonId==="undefined"){buttonId=$(this).attr("rel");
}buttonHref=$(this).attr("href");
openAjaxModal(buttonHref,buttonId);
});
$(".text-button").click(function(e){e.preventDefault();
if($(this).hasClass("fogotpassword")){$("#modalWindow").load("/account/modals/modal-passwordforgot.jsp");
$("#modalWindow").modal({minWidth:400,minHeight:150});
$("#simplemodal-overlay").css("cursor","default");
}if($(this).hasClass("cvv")){$("#modalWindow").load("/checkout/modals/modal-cvv.jsp");
$("#modalWindow").modal({minWidth:600,minHeight:350});
$("#simplemodal-overlay").css("cursor","default");
}if($(this).hasClass("closeIt")){$.modal.close();
$("#modalWindow").empty();
}if($(this).hasClass("pdp-modal-detail")){window.location.href=this;
}if($(this).hasClass("gcinfo")){$("#modalWindow").load("/global/gadgets/modal/modal-gcinfo.jsp");
$("#modalWindow").modal({minWidth:404,minHeight:307});
$("#simplemodal-overlay").css("cursor","default");
}});
$(".vdollars").click(function(e){$("#modalWindow").load("/checkout/modals/modal-dollars.jsp");
$("#modalWindow").modal({minWidth:404,minHeight:180});
$("#simplemodal-overlay").css("cursor","default");
});
$(".close-window, .closs-button").click(function(e){e.preventDefault();
if($(this).hasClass("qv")){var prodId=$(".close-window, .closs-button").attr("href");
if(prodId!=""&&prodId!=undefined){quickViewModal(prodId);
}else{$.modal.close();
$("#modalWindow").empty();
}}else{$.modal.close();
$("#modalWindow").empty();
}});
$(".ordertracking-link").click(function(e){e.preventDefault();
$("#modalWindow").load("/global/modals/modal-trackorder.jsp");
$("#modalWindow").modal({minWidth:340,minHeight:210});
$("#simplemodal-overlay").css("cursor","default");
});
$(".button").click(function(e){if($(this).hasClass("close")){e.preventDefault();
$.modal.close();
$("#modalWindow").empty();
}});
$("#sara_searchInput").val("search keyword or item #");
$("#sara_searchInput").blur(function(e){if($(this).val()==""){$(this).val("search keyword or item #");
}else{$(this).val($(this).val().toLowerCase());
}});
$("#sara_searchInput").focus(function(e){$(this).removeClass("qempty");
if($(this).val()=="Oops! Let's try again, enter search here."||$(this).val()=="search keyword or item #"){$(this).val("");
}});
$("#sara_searchform").submit(function(e){if($("#sara_searchInput").val()==""||$("#sara_searchInput").val()=="Oops! Let's try again, enter search here."||$("#sara_searchInput").val()=="search keyword or item #"){$("#sara_searchInput").val("Oops! Let's try again, enter search here.");
$("#sara_searchInput").addClass("qempty");
e.preventDefault();
}$(this).val($(this).val().toLowerCase());
});
$(".carouselOverlay").click(function(e){$("#modalWindow").load("/carousels/index.html");
$("#modalWindow").modal({minWidth:675,minHeight:400});
$("#simplemodal-overlay").css("cursor","default");
});
$(".sendFriendTextArea").keypress(function(e){var lengthF=$(this).val();
if(lengthF.length>=500){e.preventDefault();
}});
if($("#modalWindow").attr("id")!=undefined&&$("#modalWindow").attr("id")!=""){var modalWinHeight=$("#modalWindow").css("height").replace(/[^-\d\.]/g,"");
if(modalWinHeight!=0){$("#simplemodal-container").css("height","auto");
}}window.addEventListener("scroll",function(e){if($("#modalContent").length>0){$("body").css("overflow","hidden");
e.preventDefault();
}else{$("body").css("overflow","auto");
}});
$(".linkLightboxSignUp").off("click");
$(".linkLightboxSignUp").on("click",function(event){event.preventDefault();
removeHrefToAvoidUnexpectedBehaviorOnAnalytics($(this));
if($.cookie(jus.configs.lightbox.lightboxAgeGateCookieName)!=null){fireAgeGateLightbox();
}else{showSignUpLightboxOverlay("User");
jus.omniture.executeEvent(jus.omniture.lightboxUserOpenSignUp());
}});
});
function setUpNavigationTrackingCookie(side,link){var randomNumber=getRandomNumber();
var href=$(link).attr("href");
href=addParamToQueryString(href,"navSide",randomNumber);
$.cookie(randomNumber,side,{path:"/",expires:getExpirationTime()});
return href;
}function getRandomNumber(){var nowInMilliseconds=new Date().getTime();
return nowInMilliseconds;
}function addParamToQueryString(href,paramKey,paramValue){var queryVars=[{name:paramKey,value:paramValue}];
var queryString=$.param(queryVars);
return href+getQueryStringSeparator(href)+queryString;
}function getQueryStringSeparator(href){return href.indexOf("?")==-1?"?":"&";
}function getExpirationTime(){var expirationTime=15;
if(navExpirationTimeInSeconds){expirationTime=navExpirationTimeInSeconds;
}var date=new Date();
date.setTime(date.getTime()+(expirationTime*1000));
return date;
}function openAjaxModal(buttonHref,buttonId){$(".ui-dialog-content").dialog("destroy");
$("#dialog-message").remove();
if($("#"+buttonId+"Modal").length==0){$("body").append('<div id="'+buttonId+'Modal"></div>');
}$("#"+buttonId+"Modal").load(buttonHref);
var wWidth=$(window).width();
var wHeight=$(window).height();
var popWidth=eval(buttonId).width;
var popHeight=eval(buttonId).height;
var yposition=(wHeight/2)-((popWidth*0.7)/2);
var xposition=(wWidth/2)-(popWidth/2);
$("#"+buttonId+"Modal").dialog({height:"auto",minWidth:eval(buttonId).width,minHeight:eval(buttonId).height,modal:true,bgiframe:true,draggable:true,resizable:false,autoOpen:true,closeOnEscape:true,hide:"fade",show:"fade",position:[xposition,yposition]});
}function showEpressCheckoutInfo(productId){if(productId!=""){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/checkout/modals/modal-expressco-info.jsp?productId="+productId);
}else{$("#modalWindow").load("/checkout/modals/modal-expressco-info.jsp");
}$("#modalWindow").modal({minWidth:635,minHeight:280});
$("#simplemodal-overlay").css("cursor","default");
}function validateState(country){$("#state").html("");
$("#state").load("/global/statePicker.jsp?countryCode="+escape(country));
}function validateStateModal(country){$("#state-modal").html("");
$("#state-modal").load("/global/statePicker.jsp?idOverride=state-modal&countryCode="+escape(country));
}function validateAndSetState(countryCode,stateCode){$("#state").html("");
$("#countryPicker").load("/global/statePicker.jsp?countryCode="+escape(countryCode),function(){jQuery(document).ready(function(){setSelectedState(countryCode,stateCode);
changeSelectColor();
});
});
}function submitProfileRegistration(){var prov=$("#province_val").val();
var state=$("#state").find(":selected").val();
if(state==""&&prov!=""){if($("#province").is(":visible")){$("#state").append('<option value="'+prov+'" selected="true">'+prov+"</option>");
}}$("#register").submit();
}function submitProfileRegistrationStepFive(){var month=document.getElementById("birthMonth").value;
var day=document.getElementById("birthDay").value;
var year=document.getElementById("birthYear").value;
var isValidDate=true;
var isLeap=false;
if(month&&day&&year){var today=new Date;
today=new Date(today.getFullYear(),today.getMonth(),today.getDay());
isValidDate=isAValidDate(day,month,year);
var Bdate=new Date(year,month-1,day);
var age=Math.floor(((today-Bdate)/1000/(60*60*24))/365.2425);
var context=window.location.pathname;
if(!isValidDate){$(".oc_checkout-errors").show();
displayRegistrationErrorStepFive("registrationInvalidDate");
}else{if(age<13){setAgeGateCookies();
$("#oc_create_box").hide();
$("#oc_resume_box").prepend("<div class='oc_checkout-errors'></div>");
displayRegistrationErrorStepFive("registrationInvalidAge");
}else{$("#registerCheckout2").submit();
}}}else{$(".oc_checkout-errors").show();
displayRegistrationErrorStepFive("registrationInvalidDate");
}}function displayRegistrationErrorStepFive(messageCode){$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId="+messageCode,dataType:"json",success:function(obj){if(obj.message){$(".oc_birthday_select").css("border","3px solid #FF0000");
$(".oc_checkout-errors").html(obj.message);
}}});
}function daysInMonth(m,y){switch(m){case 2:return(y%4==0&&y%100)||y%400==0?29:28;
case 9:case 4:case 6:case 11:return 30;
default:return 31;
}}function isAValidDate(d,m,y){return m>0&&m<13&&d>0&&d<=daysInMonth(parseInt(m),y);
}function submitAddEditAddress(){prov=$("#province_val").val();
state=$("#state").find(":selected").val();
if(state==""&&prov!=""){if($("#province").is(":visible")){$("#state").append('<option value="'+prov+'" selected="true">'+prov+"</option>");
}}$(this).submit();
}function validateAndSetStateWithOverrideStates(countryCode,stateCode,overrideStates){$("#state").html("");
$("#state").append('<option value="">Select</option>');
$("#countryPicker").load("/includes/statePicker.jsp?countryCode="+escape(countryCode)+"&overrideStates="+escape(overrideStates),function(){jQuery(document).ready(function(){setSelectedState(countryCode,stateCode);
});
});
}function stateProvinceSync(){prov=$("#province_val").val();
state=$("#state").find(":selected").val();
if(state==""&&prov!=""){if($("#province").is(":visible")){$("#state").append('<option value="'+prov+'" selected="true">'+prov+"</option>");
}}}function setSelectedState(countryVal,stateVal){var slId="";
if(countryVal!=""&&stateVal!=""){slId="state";
}if(slId!=""){$("#"+slId+" option:selected").removeAttr("selected");
$("#"+slId+" option[value="+stateVal+"]").attr("selected","selected");
}}function showPasswordForgot(){$("#modalWindow").load("/account/modals/modal-passwordforgot.jsp");
$("#modalWindow").modal({minWidth:450,minHeight:190});
$("#simplemodal-overlay").css("cursor","default");
}function accountConf(productId){$("#modalWindow").load("/catalog/modals/modal-completelook.jsp?productId="+productId);
$("#modalWindow").modal({minWidth:650,minHeight:600});
$("#simplemodal-overlay").css("cursor","default");
}function completeLook(productId){$("#modalWindow").load("/global/modals/modal-accountcreation.jsp");
$("#modalWindow").modal({minWidth:350,minHeight:20});
$("#simplemodal-overlay").css("cursor","default");
}function editeGiftItem(productId){$("#modalWindow").load("/checkout/modals/modal-editgc-egc.jsp?productId="+productId);
$("#modalWindow").modal({minWidth:640,minHeight:330});
$("#simplemodal-overlay").css("cursor","default");
}function editGiftItem(productId){$("#modalWindow").load("/checkout/modals/modal-editgc-gcc.jsp?productId="+productId);
$("#modalWindow").modal({minWidth:630,minHeight:200});
$("#simplemodal-overlay").css("cursor","default");
}function quickView(productId,colorCode,name,brand,productGridPlacement){if(fullyLoaded){if(typeof productGridPlacement==="undefined"){$("#modalWindow").load("/catalog/modals/modal-quickview.jsp?productId="+productId+"&colorCode="+encodeURI(colorCode));
}else{$("#modalWindow").load("/catalog/modals/modal-quickview.jsp?productId="+productId+"&colorCode="+encodeURI(colorCode)+"&productGridPlacement="+productGridPlacement);
}$("#modalWindow").modal({minWidth:630,minHeight:460,fixed:false});
$("#simplemodal-overlay").css("cursor","default");
callCustomEvent("quickLook",productId,name,brand);
}}function editItem(productId,skuId,size,colorCode,qty,commeceItemId,name,brand){$("#modalWindow").load("/cart/modals/modal-edit-product.jsp?productId="+productId+"&skuId="+skuId+"&size="+encodeURI(size)+"&colorCode="+encodeURI(colorCode)+"&qty="+qty+"&commeceItemId="+commeceItemId+"&isedit=true");
$("#modalWindow").modal({minWidth:700,minHeight:605,fixed:false});
if($("LINK[href*='/css/shopModalUpsell.css']").length>0){$("LINK[href*='/css/shopModalUpsell.css']").attr("disabled","disabled");
}$("#simplemodal-overlay").css("cursor","default");
callCustomEvent("editCart",productId,name,brand);
}function sendToFriend(productId,ismodal,defaultColorCode){var color=$("#selectedColor"+productId).val();
var colorCode=$("#selectedColorCode"+productId).val();
if(colorCode=="false"){colorCode=defaultColorCode;
}$("#modalWindow").load("/pdp/modals/modal-tellafriend.jsp?productId="+productId+"&color="+encodeURI(color)+"&colorCode="+colorCode+"&ismodal="+ismodal);
$("#modalWindow").modal({minWidth:870,minHeight:485,fixed:false});
$("#simplemodal-overlay").css("cursor","default");
}function openCompleteLooks(productId,size,type){var colorToDisplay=$("#hiddenColor").html();
$("#modalWindow").load("/catalog/modals/modal-completelook.jsp?productId="+productId+"&size="+encodeURI(size)+"&colorToDisplayOutfit="+encodeURI(colorToDisplay),function(){var currentHeight=$("#modalWindow").height();
$("#modalWindow").modal({minWidth:645,minHeight:currentHeight,position:[10],escClose:false});
$("#simplemodal-overlay").css("cursor","default");
if(typeof type=="undefined"){$(".simplemodal-container").css({"position":"absolute"});
}});
}function addQuickshopToWishlist(){var validatedQty=true;
var validatedSize=true;
var missingQty=false;
var missingSize=false;
var productId="";
var productid_length="productId";
var prodIdLabel="";
var skuId="";
var my_form=$("#addToCartOptionsQuickshop");
$.each($("input, select",my_form),function(i,v){var theElement=$(v);
var theValue=theElement.val();
var inputType=theElement.attr("type");
var vclass=theElement.attr("class");
var inputId=theElement.attr("id");
if(!(typeof inputId==="undefined")&&inputId.substring(0,productid_length.length)=="productId"){missingSize=false;
missingQty=false;
productId=theValue;
prodIdLabel=inputId.substring(productid_length.length,inputId.length);
}if(!(typeof inputId==="undefined")&&inputId=="catalogRefIds"+prodIdLabel){missingSize=false;
missingQty=false;
skuId=theValue;
}if(!(typeof inputId==="undefined")&&inputId=="sizeOptions"+prodIdLabel&&theValue==""){missingSize=true;
validatedSize=false;
}if(!(typeof inputId==="undefined")&&inputId=="prodQtySelection"+prodIdLabel){if(theValue==""){missingQty=true;
validatedQty=false;
}else{$("#giftListCatalogRefIds"+prodIdLabel).val(skuId);
$("#giftListQuantity"+prodIdLabel).val(theValue);
}}});
if(validatedQty&&validatedSize){dataString=$("#addProductToGiftListQuickshop").serialize();
$.ajax({type:"POST",url:"/wishlist/gadgets/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="false"){document.location.href="/wishlist/";
}else{document.location.href="/wishlist/";
}}});
}else{document.location.href="/wishlist/";
}}function preAddQuickshopToCart(callbackOnComplete){$.ajax({type:"GET",url:"/omniture/productsInCart.jsp",data:{printJson:"true"},dataType:"json",success:function(productsInCart){callbackOnComplete(productsInCart);
}});
}function addQuickshopToCart(){var validatedQty=true;
var validatedSize=true;
var missingQty=false;
var missingSize=false;
var productId="";
var productid_length="productId";
var prodIdLabel="";
var my_form=$("#addToCartOptionsQuickshop");
var skuIds=new Array();
var brands=new Array();
var productIds=new Array();
$.each($("input, select",my_form),function(i,v){var theElement=$(v);
var theValue=theElement.val();
var inputType=theElement.attr("type");
var vclass=theElement.attr("class");
var inputId=theElement.attr("id");
if(!(typeof inputId==="undefined")&&inputId.substring(0,productid_length.length)=="productId"){missingSize=false;
missingQty=false;
productId=theValue;
prodIdLabel=inputId.substring(productid_length.length,inputId.length);
var skuId=$("#catalogRefIds"+prodIdLabel).val();
var brand=$("#brand"+productId).val();
if(brand=="JST"){brand="justice";
}else{brand="brothers";
}skuIds.push($("#catalogRefIds"+prodIdLabel).val());
brands.push(brand);
productIds.push(productId);
}if(!(typeof inputId==="undefined")&&inputId=="sizeOptions"+prodIdLabel&&theValue==""){missingSize=true;
validatedSize=false;
}if(!(typeof inputId==="undefined")&&inputId=="prodQtySelection"+prodIdLabel){if(theValue==""){missingQty=true;
validatedQty=false;
}else{$("#qty"+prodIdLabel).val(theValue);
}}});
if(validatedQty&&validatedSize){preAddQuickshopToCart(function(productsInCart){var $productOriginInput=$("#addToCartOptionsQuickshop input[name='productOrigin']");
if($productOriginInput.length==0){$("#addToCartOptionsQuickshop").append('<input type="hidden" name="productOrigin" />');
$productOriginInput=$("#addToCartOptionsQuickshop input[name='productOrigin']");
}$productOriginInput.val("quickshop");
dataString=$("#addToCartOptionsQuickshop").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="false"||obj.error=="gcard"){obj.omnitureDataLayerEvent.productsInCart=productsInCart;
jus.omniture.executeEvent(obj.omnitureDataLayerEvent);
for(var i=0;
i<productIds.length;
i++){callCustomEvent("cartAdd",productIds[i],skuIds[i],brands[i]);
}var callBack=function(){document.location.href="/cart/";
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}else{document.location.href="/cart/";
}}});
});
}else{document.location.href="/cart/";
}}function addcompleteLook(){dataString=$("#addToCartOptionsCmplLook").serialize();
$("#clookAddItemTocartError").html("");
$("#clookAddItemTocartError").hide();
var validatedQty=true;
var validatedSize=true;
var missingQty=false;
var missingSize=false;
var my_form=$("#addToCartOptionsCmplLook");
var qty=parseInt(0);
$.each($("input, select",my_form),function(i,v){var theElement=$(v);
var theValue=theElement.val();
var inputType=theElement.attr("type");
var vclass=theElement.attr("class");
var inputId=theElement.attr("id");
if(inputId.substring(0,18)=="clookCatalogRefIds"){missingSize=false;
missingQty=false;
}if(inputType=="select-one"&&theValue==""){missingSize=true;
validatedSize=false;
}if(vclass=="qty"&&theValue==0){missingQty=true;
validatedQty=false;
}else{if(vclass=="qty"&&theValue!=0){qty+=parseInt(theValue);
}}});
if(validatedQty&&validatedSize){$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to add item(s) to cart";
$("#clookAddItemTocartError").show();
$("#clookAddItemTocartError").html(message);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){$.modal.close();
$("#modalWindow").empty();
cartExpand(function(){$.get("/global/gadgets/minicartHeader.jsp?r="+Math.random(),function(html){var cartIcon=$(html).find("#cartIcon").attr("class");
var totalCommerceItemCount=$(html).find(".item-amount").html();
var merchandiseSubtotal=$(html).find(".price").html();
$("#cartIcon").attr("class",cartIcon);
$("#minicartHeader .header .item-amount").html(totalCommerceItemCount);
$("#minicartHeader .header .price").html(merchandiseSubtotal);
});
});
autoCloseMinicart();
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
}else{$("#clookAddItemTocartError").show();
if(!validatedQty&&!validatedSize){$("#clookAddItemTocartError").html("Please specify quantity and size");
}else{if(!validatedQty){$("#clookAddItemTocartError").html("Please enter quantity");
}else{$("#clookAddItemTocartError").html("Please select size");
}}$("#simplemodal-container").css({"width":645,"height":"auto"});
}}function submitEmailFriendSubscriptions(productId,color,colorCode,ismodal){subject=$("#friendSubject").val();
sender=$("#friendNameFrom").val();
newSubject=subject.replace("senderName",sender);
$("#friendSubject").val(newSubject);
dataString=$("#emailForm").serialize();
$.ajax({type:"POST",cache:false,url:"/global/gadgets/validateSendMail.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="true"){$.ajax({type:"GET",cache:false,url:"/pdp/gadgets/tellaFriendErrors.jsp",dataType:"html",async:false,success:function(data2){$("#friendEmail").removeClass("error");
$("#friendNameFrom").removeClass("error");
$("#simplemodal-container").css("height","550px");
$("#divForErrors").html(data2);
if(data2.indexOf("email")!==-1){$("#friendEmail").addClass("error");
}if(data2.indexOf("name")!==-1){$("#friendNameFrom").addClass("error");
}}});
}else{if(data.error=="false"){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/pdp/modals/modal-email-friend-thanks.jsp?productId="+productId+"&color="+encodeURI(color)+"&colorCode="+colorCode+"&ismodal="+ismodal);
$("#modalWindow").modal({minWidth:400,maxWidth:410,maxHeight:250,minHeight:110});
callCustomEvent("emailFriend","","","");
}}}});
}function giftCardExpireOverlay(callBack){$.modal.close();
$("#modalWindow").load("/giftcards/modals/modal-gcexpired.jsp",function(){$("#closeGCA,#closeGCB").click(function(event){event.preventDefault();
callBack();
});
});
$("#modalWindow").modal({minWidth:400,maxWidth:410,maxHeight:250,minHeight:110});
}function sendWishlist(wishlist){$("#modalWindow").load("/wishlist/modals/modal-wishlistEmail.jsp");
$("#modalWindow").modal({minWidth:370,minHeight:300});
$("#simplemodal-overlay").css("cursor","default");
}function submitWishlistSubscriptions(wishlist){dataString=$("#emailForm").serialize();
$.ajax({type:"POST",url:"/global/gadgets/validateSendMail.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="true"){$("#modalWindow").load("/wishlist/modals/modal-wishlistEmail.jsp");
$(".simplemodal-container").css({"position":"absolute","overflow":"scroll","overflow-x":"hidden"});
}else{if(data.error=="false"){$.modal.close();
$("#modalWindow").load("/pdp/modals/modal-email-friend-thanks.jsp");
$("#modalWindow").modal({maxWidth:320,maxHeight:100,minHeight:100});
}}}});
}function expressCheckoutLogin(productId,modal){$("#addItemAndExpressCheckout").val("true");
var validateSelection=validateProductSelection(productId);
if(!validateSelection){setError("Selection Required",false,productId);
}else{var errorQuantity=checkSKUQuality(productId);
if(""!=errorQuantity){setError(errorQuantity,false,productId);
}else{var skuId=$("#catalogRefIds"+productId).val();
var quantity=$("#prodQtySelection").val();
if(typeof modal!="undefined"&&modal){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/checkout/modals/modal-expressco-signup.jsp",{productId:productId,skuId:skuId,quantity:quantity,modal:modal});
$("#modalWindow").modal({minWidth:635,minHeight:260});
$("#simplemodal-overlay").css("cursor","default");
}else{$("#modalWindow").load("/checkout/modals/modal-expressco-signup.jsp",{productId:productId,skuId:skuId,quantity:quantity});
$("#modalWindow").modal({minWidth:635,minHeight:260});
$("#simplemodal-overlay").css("cursor","default");
}}}}function addGiftOptions(shippingGroupId){$.ajax({type:"POST",url:"/checkout/gadgets/setgiftwrap.jsp?shipGrpId="+shippingGroupId,data:"",dataType:"text",success:function(obj){$("#modalWindow").load("/checkout/modals/modal-giftwrap.jsp?shippingGroupId="+shippingGroupId);
$("#modalWindow").modal({minWidth:390,minHeight:180});
$("#simplemodal-overlay").css("cursor","default");
}});
}function viewModalShoeSize(productId,type,catId){if(productId!=""){$.modal.close();
}$("#modalWindow").load("/global/modals/modal-shoesize.jsp?productId="+productId+"&type="+type+"&catId="+catId);
$("#modalWindow").modal({minWidth:710,minHeight:484});
$("#simplemodal-overlay").css("cursor","default");
}function viewModalShoeSizeEx(productId,type,catId,skuSize,selectedColor,qty,ci){if(productId!=""){$.modal.close();
}$("#modalWindow").load("/global/modals/modal-shoesize.jsp?productId="+productId+"&type="+type+"&catId="+catId+"&skuSize="+encodeURI(skuSize)+"&selectedColor="+encodeURI(selectedColor)+"&qty="+qty+"&ci="+ci);
$("#modalWindow").modal({minWidth:710,minHeight:484});
$("#simplemodal-overlay").css("cursor","default");
}function displayOrderDetails(orderId){var height=$("#"+orderId+"").height();
if(height==0){$("#"+orderId+"").load("/account/gadgets/accountOrderItemDetails.jsp?orderId="+orderId);
$("#"+orderId+"").css("height","100%");
$("#"+orderId+"").animate({"height":"100%"},100);
$("#"+orderId+"").fadeIn("fast");
$("#btn_"+orderId).attr("class","orderHideDetails");
$("#btn_"+orderId).attr("title","Hide Order Details");
}else{$("#"+orderId+"").animate({"height":0},100);
$("#"+orderId+"").fadeOut("fast");
$("#"+orderId+"").html("");
$("#btn_"+orderId).attr("class","orderViewDetails");
}}function quickViewModal(productId){$.modal.close();
$("#modalWindow").empty();
quickView(productId);
}function quickViewModal(productId,color){$.modal.close();
$("#modalWindow").empty();
quickView(productId,color);
}function sizeModal(){$.modal.close();
$("#modalWindow").empty();
}function loadShippingRatesModal(){$("#modalWindow").load("/checkout/modals/modal-shippingRates.jsp");
$("#modalWindow").modal({minWidth:630,minHeight:630,position:[10+f_scrollTop()]});
$(".simplemodal-container").css({"position":"absolute","overflow":"scroll","overflow-x":"hidden"});
$("#simplemodal-overlay").css("cursor","default");
}function displayCreditCardBillingAddress(billAddrSelectedId){$("#selectedBillingAddress").load("/checkout/gadgets/billingAddressInfo.jsp?billAddrSelectedId="+billAddrSelectedId);
}function displayBillingAddress(selectedKey){$("#selectedBillingAddress").load("/checkout/gadgets/billingAddressInfo.jsp?nickname="+escape(selectedKey));
}function displayCreditCardAddress(selectedKey){$("#selectedCreditCardAddress").load("/checkout/gadgets/creditCardInfo.jsp?nickname="+escape(selectedKey));
}function editItemModal(productId,skuId,size,color,qty,commeceItemId){$.modal.close();
$("#modalWindow").empty();
editItem(productId,skuId,size,color,qty,commeceItemId);
}function seeMyItems(itemCount){$("#modalWindow").load("/catalog/modals/modal-rv.jsp",function(){var elmHeight=$(".recent").height()+20;
var elemWidth=$(".recent").width()+20;
$("#modalWindow").modal({minWidth:elemWidth,minHeight:elmHeight});
$("#simplemodal-overlay").css("cursor","default");
});
}function removeGiftwrap(removeItemid){$("#rmGiftId").val(removeItemid);
dataString=$("#updateGiftWrap").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateGiftItem.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="false"){$("#fullCart").load("/checkout/gadgets/cartFull.jsp");
$("#shippingInfo").load("/checkout/gadgets/selectedShippingInfo.jsp");
}}});
}function addGiftWrap(){var shippingGroupId=$("#shipGrpId").val();
dataString=$("#giftWrapMsg").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$("#modalWindow").load("/checkout/modals/modal-giftwrap.jsp?shippingGroupId="+shippingGroupId);
$("#modalWindow").modal({minWidth:390,minHeight:200});
$(".simplemodal-container").css({"height":"200px"});
$("#simplemodal-overlay").css("cursor","default");
}else{if(obj.error=="false"){$.modal.close();
$("#fullCart").load("/checkout/gadgets/cartFull.jsp");
}}}});
}function shippingAddress(nickNname,itemId){$.ajaxSettings.cache=false;
if(nickNname!=""){if(nickNname=="new"){$("#modalWindow").load("/checkout/modals/modal-address.jsp?commerceItemId="+itemId);
$("#modalWindow").modal({minWidth:430,minHeight:410});
$("#simplemodal-overlay").css("cursor","default");
}else{$("#addressNickname").val(nickNname);
$("#commerceItemId").val(itemId);
dataString=$("#changeShippingInfo").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){$.get("/checkout/gadgets/selectedShippingInfo.jsp",function(data){var availableShippingMethods=$(data).find("#availableShippingMethods");
$("#availableShippingMethods").html(availableShippingMethods);
var addressInfo=$(data).find("#addressInfo");
$("#addressInfo").html(addressInfo);
$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp");
});
}});
}}}function changeShippingAddress(nickNname){$.blockUI({message:null,overlayCSS:{opacity:0}});
$.ajaxSettings.cache=false;
if(nickNname!=""){$("#shippingAddressNickname").val(nickNname);
dataString=$("#changeShippingAddress").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){$.get("/checkout/gadgets/selectedShippingInfo.jsp",function(data){var availableShippingMethods=$(data).find("#availableShippingMethods");
$("#availableShippingMethods").html(availableShippingMethods);
var addressInfo=$(data).find("#addressInfo");
var shippingMethodSg=$("#shippingMethodSg").val();
var shippingSelected=false;
$("#availableShippingMethods input[type='radio']").each(function(){var shippingMethodOption=$(this).val();
if(shippingMethodSg===shippingMethodOption){shippingSelected=true;
}});
if(shippingSelected==false){var newShippingMethod=$("#availableShippingMethods input[type='radio']:not(.stsMethod)").eq(0).attr("id");
$("#"+newShippingMethod).attr("checked","checked");
changeShippingMethod("#"+newShippingMethod,nickNname,"");
}else{changeShippingMethod("#shipping"+shippingMethodSg,nickNname,"");
}$.unblockUI();
}).error(function(){$.unblockUI();
});
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}}function addNewShippingAddress(){dataString=$("#addnewShippAddres").serialize();
var commerceItemId=$("#commItemId").val();
var addressNickname=$("#nickName").val();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$.ajax({type:"POST",url:"/global/gadgets/modal/modal-address.jsp?commerceItemId="+commerceItemId+"&shipToAddressName="+addressNickname,data:dataString,dataType:"html",success:function(data){$("#modalWindow").html(data);
}});
$("#modalWindow").modal({minWidth:430,minHeight:410});
$("#simplemodal-overlay").css("cursor","default");
}else{if(obj.error=="false"){$("#shippingInfo").load("/checkout/gadgets/selectedShippingInfo.jsp",function(){$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp");
});
$.modal.close();
$("#modalWindow").empty();
}}}});
}function facetSelection(categoryId,facetTrail,ques,showPrd,hideCatFacets,refinId,facetId,sourceCategoryId,type){var selection=$("#selectionSort").val();
if(null==type||""==type){$.ajax({type:"GET",url:"/search/gadgets/searchPagination.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques,showProductNavigation:showPrd},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques,showProductNavigation:showPrd,hideCategoryFacets:hideCatFacets},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"text"});
$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategorySearchItemBody.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/sortBy.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques,showProductNavigation:showPrd,selectedOption:selection},success:function(data){$("dl#sortingHeader").html(data);
},async:false,dataType:"html"});
removeRepeatedDivs();
$("#selectionSort").trigger("onchange");
}else{$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:sourceCategoryId,categoryId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/sortByAttr.jsp",data:{categoryId:categoryId,catId:sourceCategoryId,facetId:facetId,refinId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("dl#sortingHeader").html(data);
},async:false,dataType:"html"});
}return false;
}function removeRepeatedDivs(){$("div#ajaxCategoryDisplay").each(function(index){if(index!=0){$(this).remove();
}});
}function nextPage(categoryId,facetTrail,startIndex,pageNum,howMany,ques,sortOrder,showProductNavigation){$.ajax({type:"GET",url:"/search/gadgets/searchPagination.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,showProductNavigation:showProductNavigation},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,showProductNavigation:showProductNavigation},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategorySearchItemBody.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,startIndex:startIndex,pageNum:pageNum,howMany:howMany,ques:ques,sortOrder:sortOrder,showProductNavigation:showProductNavigation},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
return false;
}function nextPageBrands(categoryId,facetTrail,startIndex,pageNum,howMany,ques,sortOrder,refId,facetId,type){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:categoryId,q_facetTrail:facetTrail,startIndex:startIndex,pageNum:pageNum,howMany:howMany,ques:ques,sortOrder:sortOrder,refinementId:refId,facetId:facetId,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
return false;
}function sortResult(categoryId,facetTrail,sortOrder,ques){if(sortOrder!="reset"){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategorySearchItemBody.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,sortOrder:sortOrder,ques:ques},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
removeRepeatedDivs();
}else{if(categoryId==undefined){window.location.href="/catalog/categoryPage.jsp?categoryId="+categoryId;
}else{location.reload();
}}}function addToGiftList(listId,prodId,modal,giftSku,itemsQty){var sku=giftSku;
var qty=itemsQty;
if(sku==""||sku==null){sku=$("#catalogRefIds"+prodId).val();
}if(qty==""){qty=parseInt($("#prodQtySelection").val());
}$("#giftListId").val(listId);
$("#giftListQuantity").val(qty);
$("#giftListSkuId").val(sku);
$("#giftListProdId").val(prodId);
var validateSelection=validateProductSelection(prodId);
if(!validateSelection&&sku==null){setError("Selection Required",false,prodId);
}else{if(validateProductSelection()&&qty>0){$("#giftListId").val(listId);
if(itemsQty==""||itemsQty==null||itemsQty==0){$("#giftListQuantity").val($("#prodQtySelection").val());
}else{$("#giftListQuantity").val(itemsQty);
}$("#giftListSkuId").val(sku);
dataString=$("#addPorductToGiftList"+prodId).serialize();
$.ajax({type:"POST",url:"/giftregistry/modals/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(obj){if(modal="true"){$.modal.close();
$("#modalWindow").empty();
}window.location.href="/giftregistry/viewGiftlist.jsp?giftlistId="+listId+"&productId="+prodId;
}});
}else{setError("Selection Required",false);
}}}function openGiftList(prodId,skuId,ismodal){var sku=skuId;
if(sku==""){sku=$("#catalogRefIds"+prodId).val();
}var qty=parseInt($("#prodQtySelection").val());
var validateSelection=validateProductSelection(prodId);
if(!validateSelection){setError("Selection Required",false,prodId);
}else{$("#modalWindow").load("/giftregistry/modals/modal-chosegiftlist.jsp?productId="+prodId+"&skuID="+sku+"&ismodal="+ismodal+"&qty="+qty,function(){var currentHeight=$("#modalWindow").height();
$("#modalWindow").modal({minWidth:630,minHeight:currentHeight});
$("#simplemodal-overlay").css("cursor","default");
});
}}function createNewGiftListAddItem(productId,giftSku){var qty=parseInt($("#prodQtySelection").val());
if(validateProductSelection()&&qty>0){if(productId==""||productId==undefined){var prodId=$("#catalogRefProdId").val();
}else{var prodId=productId;
}if(giftSku==""||giftSku==undefined){var skuId=$("#catalogRefIds"+prodId).val();
}else{var skuId=giftSku;
}window.location.href="/account/giftlist?qty="+qty+"&sku="+skuId+"&productId="+prodId;
}else{setError("Selection Required ",false);
}}function openGiftCardNumber(){$("#modalWindow").load("/giftcards/modals/modal-giftCardNum.jsp");
$("#modalWindow").modal({minWidth:665,minHeight:540});
$("#simplemodal-overlay").css("cursor","default");
}function openCVV(){$("#modalWindow").load("/checkout/modals/modal-cvv.jsp");
$("#modalWindow").modal({minWidth:665,minHeight:410});
$("#simplemodal-overlay").css("cursor","default");
}function openEmailList(){$("#modalWindow").load("/checkout/modals/modal-email-list.jsp");
$("#modalWindow").modal({minWidth:425,minHeight:220});
$("#simplemodal-overlay").css("cursor","default");
}function addItemToWishList(wishlist_id,product_id,sku_id,itemsQty){var qty=itemsQty;
if(qty==""||qty==undefined){qty=parseInt($("#prodQtySelection"+product_id).val());
}var sku=sku_id;
if(sku==""||sku==null){sku=$("#catalogRefIds"+product_id).val();
}$("#giftListId").val(wishlist_id);
$("#giftListSkuId").val(sku);
$("#giftListProdId").val(product_id);
var validateSelection=validateProductSelection(product_id);
if(!validateSelection){setError("Please select size",false,product_id);
}else{if(validateProductSelection()&&qty>0){$("#addPorductToGiftList"+product_id+" #giftListId").val(wishlist_id);
$("#addPorductToGiftList"+product_id+" #giftListQuantity").val(qty);
$("#addPorductToGiftList"+product_id+" #giftListSkuId").val(sku);
dataString=$("#addPorductToGiftList"+product_id).serialize();
$.ajax({type:"POST",url:"/wishlist/gadgets/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(obj){$.getJSON("/wishlist/gadgets/wishlistItemsCount.jsp?r="+Math.random(),function(json){var count=json.wishlistcount;
$("#wishlistCount").html(count);
addToWishlist(product_id,$("#selectedColorCode"+product_id).val());
});
colorCodeProduct=$("#selectedColorCode"+product_id).val();
updateCertonaTags(product_id,colorCodeProduct,"wishlist");
}});
}else{setError("Selection Required",false);
}}}function validateWishlistSelection(prodId){var qty=parseInt($("#prodQtySelection"+prodId).val());
var size=$("#sizeOptions"+prodId).val();
var validateSelection=validateProductSelection(prodId);
if(!validateSelection||qty<0){setError("Please select size",false,prodId);
}else{var skuId=$("#catalogRefIds"+prodId).val();
window.location.href="/account/?giftItemQty="+qty+"&skuIdWishlist="+skuId+"&productIdWishlist="+prodId+"&wishListSize="+size;
}}function validateGiftlistSelection(prodId){var qty=parseInt($("#prodQtySelection").val());
var validateSelection=validateProductSelection(prodId);
if(!validateSelection||qty<0){setError("Selection Required ",false,prodId);
}else{var skuId=$("#catalogRefIds"+prodId).val();
window.location.href="/account/signin.jsp?productIdGiftlist="+prodId+"&skuIdGiftlist="+skuId+"&giftItemQty="+qty;
}}function addItemToWishListCart(wishlist_id,product_id,isModal,sku_Id,qty){$("#giftListId").val(wishlist_id);
$("#giftListQuantity").val(qty);
$("#giftListSkuId").val(sku_Id);
$("#giftListProdId").val(product_id);
dataString=$("#addProductToGiftListCart").serialize();
$.ajax({type:"POST",url:"/giftregistry/modals/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(data){wlExpand();
setTimeout(function(){wlContract();
},5000);
$.ajax({type:"POST",url:"/cart",data:null,dataType:"html",success:function(data2){$("#wishlistCount").html($("#wishlistCount",data2).html());
}});
}});
}function addToWishlist(productId,colorCode){$.modal.close();
$("#modalWindow").load("/wishlist/modals/modal-wishlistadd.jsp?productId="+productId+"&colorCode="+colorCode);
$("#modalWindow").modal({minWidth:850,minHeight:436});
$("#simplemodal-overlay").css("cursor","default");
}function linkToWishlist(){window.location.href="/account/wishlist";
}function checkAgeVerified(){var ageVerified=document.getElementById("regAgeVerified");
var submitButton=document.getElementById("regSubmitButton");
if(ageVerified.checked){submitButton.disabled=false;
}else{submitButton.disabled=true;
}}function checkBalance(flag){$("#modalWindow").load("/giftcards/modals/modal-gcbalance.jsp?flag="+flag);
$("#modalWindow").modal({minWidth:320,minHeight:120});
$("#simplemodal-overlay").css("cursor","default");
}function checkAgain(){$("#modalWindow").load("/giftcards/modals/modal-gcbalance.jsp");
$("#modalWindow").modal({minWidth:320,minHeight:120});
$("#simplemodal-overlay").css("cursor","default");
}function checkBalanceSubmit(flag){dataString=$("#gc_balance_check").serialize();
$.ajax({type:"POST",url:"/giftcards/gadgets/validateGiftBalance.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$.modal.close();
$("#modalWindow").load("/giftcards/modals/modal-gcbalance.jsp?flag="+flag);
$("#modalWindow").modal({minWidth:320,minHeight:170});
$("#simplemodal-overlay").css("cursor","default");
}else{if(obj.error=="false"){if(flag=="ecard"){window.location.href="/giftcards/egiftcard/balance";
}else{window.location.href="/giftcards/giftcard/balance";
}}}}});
}function showErrorMessage(elementId){if($("#error_field")[0].innerHTML!="Complete Required Fields"){$("#error_field")[0].innerHTML="Complete Required Fields";
$("#error_field").css({"display":"block"});
}$(elementId).addClass("error");
}function showSpecialErrorMessage(message,elementId){if($("#error_field")[0].innerHTML!=message){$("#error_field")[0].innerHTML=message;
$("#error_field").css({"display":"block"});
}$(elementId).addClass("error");
}function purchaseWithPurchaseView(productId,skuId,closeModal){if(typeof closeModal!="undefined"&&closeModal){$.modal.close();
}$("#modalWindow").load("/checkout/modals/modal-pwp.jsp?productId="+productId+"&skuId="+skuId);
$("#modalWindow").modal({minWidth:530,minHeight:250,overlayClose:true});
$("#simplemodal-overlay").css("cursor","default");
}function addSKUToCard(productId){var validateSelection=validateProductSelection(productId);
if(!validateSelection){setError("Selection Required",false,productId);
}else{var errorQuantity=checkSKUQuality(productId);
if(""!=errorQuantity){setError(errorQuantity,false,productId);
if($("#modalWindow:visible").length>0){$("#simplemodal-container").height(310);
}}else{dataString=$("#addToCartOptions"+productId+"").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to add item to cart";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){window.location.href="/global/gadgets/closePWP.jsp";
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
}}}function removeItemFromCart(currentItem,brand,productId,skuId){$("#removeItemId").val(currentItem);
try{for(var i=0;
i<dataLayer.productsInCart.length;
i++){if(dataLayer.productsInCart[i].sku.standard==skuId){$("#removeItemFromCartPage input[name='productRemoved']").val($.toJSON(dataLayer.productsInCart[i]));
break;
}}}catch(err){console.log(err);
}dataString=$("#removeItemFromCartPage").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to remove item from cart";
$(".boxTitle").append(setError(message,false,currentItem,clook));
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){window.location="/cart";
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}callCustomEvent("cartRemove",productId,skuId,brand);
}}}});
}function removeItemFromMiniCart(currentItem,skuId,prodId,brand,dataLayerRemoveItem){var expand=false;
var displayName=$("#displayName").val();
$("#removeItemId").val(currentItem);
dataString=$("#removeItemFromCartPage").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to remove item from cart";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){cartExpand(function(){$.get("/global/gadgets/minicartHeader.jsp?r="+Math.random(),function(html){var cartIcon=$(html).find("#cartIcon").attr("class");
var totalCommerceItemCount=$(html).find(".item-amount").html();
var merchandiseSubtotal=$(html).find(".price").html();
$("#cartIcon").attr("class",cartIcon);
$("#minicartHeader .header .item-amount").html(totalCommerceItemCount);
$("#minicartHeader .header .price").html(merchandiseSubtotal);
if(parseInt(totalCommerceItemCount.match(/\d+/))==0){$("#minicart").css("display","none");
}if(window.location.pathname.indexOf("/cart")!=-1){window.location.reload();
}});
});
autoCloseMinicart();
if(($(".donations-combobox-container").length>0)&&($(".mc-raw-block").length>0)&&getItemCount()<3){$(".donations-combobox-container").css("visibility","");
removeItem=true;
}};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}callCustomEvent("cartRemove",prodId,skuId,brand);
}}}});
var dataLayerRemovedItemEvent=dataLayerRemoveItem;
jus.omniture.executeEvent(dataLayerRemovedItemEvent);
}function removeSleeveFromMiniCart(commerceItemId,sleeveQuantity,holderProductId,dataLayerRemoveItem){var commerceItemQuantity=parseInt($("#updateGiftCardQuantity input[name="+commerceItemId+"]").val());
var updatedCommerceItemQuantity=commerceItemQuantity-sleeveQuantity;
$("#updateGiftCardQuantity input[name="+commerceItemId+"]").val(updatedCommerceItemQuantity);
$("#updateGiftCardQuantity input[name=holderProductId]").val(holderProductId);
$("#updateGiftCardQuantity input[name=giftCardCommerceItemId]").val(commerceItemId);
dataString=$("#updateGiftCardQuantity").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to remove item from cart";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){cartExpand(function(){$.get("/global/gadgets/minicartHeader.jsp?r="+Math.random(),function(html){var cartIcon=$(html).find("#cartIcon").attr("class");
var totalCommerceItemCount=$(html).find(".item-amount").html();
var merchandiseSubtotal=$(html).find(".price").html();
$("#cartIcon").attr("class",cartIcon);
$("#minicartHeader .header .item-amount").html(totalCommerceItemCount);
$("#minicartHeader .header .price").html(merchandiseSubtotal);
if(parseInt(totalCommerceItemCount.match(/\d+/))==0){$("#minicart").css("display","none");
}});
if(window.location.pathname.indexOf("/cart")!=-1){window.location=window.location;
}});
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
var dataLayerRemovedItemEvent=dataLayerRemoveItem;
jus.omniture.executeEvent(dataLayerRemovedItemEvent);
}function closePWP(){window.location.href="/global/gadgets/closePWP.jsp";
}function addViewGiftWrap(messageId,checkId,sgid,closeModal){var txt_val=$("#"+messageId).val();
var chk_val=$("#"+checkId).attr("checked");
var sgid_val=$("#"+sgid).val();
if(typeof closeModal!="undefined"&&closeModal){$.modal.close();
}$("#modalWindow").load("/checkout/modals/modal-viewgiftwarp.jsp",{txt:txt_val,chk:chk_val,shippingGroupId:sgid_val});
$("#modalWindow").modal({minWidth:350,minHeight:380});
$("#simplemodal-overlay").css("cursor","default");
}function showGiftOptions(messageId,checkId,sgid,closeModal){var txt_val=$("#"+messageId).val();
var chk_val=$("#"+checkId).val();
var sgid_val=$("#"+sgid).val();
if(typeof closeModal!="undefined"&&closeModal){$.modal.close();
}$("#modalWindow").load("/checkout/modals/modal-giftwrap.jsp",{txt:txt_val,chk:chk_val,shippingGroupId:sgid_val});
$("#modalWindow").modal({minWidth:390,minHeight:180});
$("#simplemodal-overlay").css("cursor","default");
}function facetAttrSelection(categoryId,refinId,facetId,sourceCategoryId,facetTrail,type,showPrd,hideCatFacets){if(null==type||""==type){$.ajax({type:"GET",url:"/pdp/gadgets/productNavAttr.jsp",data:{categoryId:categoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategoryAttrItemBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail},success:function(data){$("div#ajaxCategoryDisplay").html(data);
$("ul.cat-list li:nth-child(4n)").addClass("fourth");
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
}else{$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:sourceCategoryId,categoryId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/sortByAttr.jsp",data:{categoryId:categoryId,catId:sourceCategoryId,facetId:facetId,refinId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("dl#sortingHeader").html(data);
},async:false,dataType:"html"});
}return false;
}function facetTopLooksSelection(categoryId,refinId,facetId,sourceCategoryId,facetTrail){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategoryTopLooksBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:"topLooks"},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
}function sortResultAttr(categoryId,facetTrail,sortOrder,facetId,refinId,sourceCategoryId){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategoryAttrItemBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,sortOrder:sortOrder},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
}function sortResultBrands(categoryId,facetTrail,sortOrder,facetId,refinId,sourceCategoryId,type){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,sortOrder:sortOrder,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
}function removePromotionCoupon(couponCode){$("#removeCouponCode").val(couponCode);
$("#removePromotion").submit();
}function checkSelection(){if($("#bill_shipforbill").attr("checked")){$("#bill_address").hide();
if($("#bill_shipforbill")[0]){$("#bill_shipforbill")[0].value="true";
}}else{displayBillingAddress($("#addressId").val());
$("#bill_address").show();
if($("#bill_shipforbill")[0]){$("#bill_shipforbill")[0].value="false";
}}}function optionSelection(r){if($("#savedCC").attr("checked")){$("#ccForm_savedCC").show();
$("#ccForm_newCC").hide();
}else{$("#ccForm_savedCC").hide();
$("#ccForm_newCC").show();
}}function addSelectionAndStartCheckout(productId,modal){$("#addItemAndExpressCheckout").val("false");
var validateSelection=validateProductSelection(productId);
if(!validateSelection){setError("Selection Required",false,productId);
}else{dataString=$("#addToCartOptions"+productId+"").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to add item to bag";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){window.location.href="/cart";
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
}}function shippingAddressEdit(nickname,action,ciId){commerceItemId=ciId;
$("#addressEditNickname").val(nickname);
$("#actionEdit").val(action);
dataString=$("#setdefaultEditShipping").serialize();
$.ajax({type:"POST",url:"/account/modals/modal-edit-address.jsp",data:dataString,dataType:"html",success:function(data){$("#modalWindow").html(data);
$("#modalWindow").modal({minWidth:460,minHeight:524,fixed:false});
$("#simplemodal-container").css("width","460");
$("#simplemodal-container").css("height","524");
$("#simplemodal-overlay").css("cursor","default");
},async:false,dataType:"html"});
}function checkoutAddressEdit(nickname,action,ciId,step){var nickId=nickname.replace(/\s/g,"");
commerceItemId=ciId;
$("#addressEditNickname").val(nickname);
$("#actionEdit").val(action);
dataString=$("#setdefaultEditShipping").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/editCheckoutAddress.jsp?currentStep="+step,data:dataString,dataType:"html",success:function(data){$("#"+nickId.toLowerCase()+"_edt_addr_fields").html(data);
$("#"+nickId.toLowerCase()+"_edt_addr_fields").show();
$("#"+nickId.toLowerCase()+"_shippingAddressInfo").hide();
},async:false,dataType:"html"});
}function saveShippingAddressEdit(nickname,action,ciId){var newNick=$("#addr-nickname").val();
dataString=$("#atg_store_editAddress").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingEditAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$("#errorMessage").load("/checkout/gadgets/profileErrorMessage.jsp");
}else{if(obj.error=="false"){updateShippingForm(nickname,newNick);
}}}});
}function retrictNicknameInputs(){$(".nickNameValidation").keypress(function(e){if(e.which!=8&&e.which!=0&&e.which!=32&&(e.which<48||e.which>57)&&(e.which<97||e.which>122)&&(e.which<65||e.which>90)){e.preventDefault();
}});
}function checkoutSaveAddress(referrer){var newNick=$("#addr-nickname").val();
var dataString=$("#atg_store_editAddress").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/profileErrorMessage.jsp",data:dataString,dataType:"html",success:function(data){var hasErrors=data.indexOf("error-message")!==-1;
if(hasErrors){$("#errorMessage").html(data);
}else{window.location=referrer;
}},error:function(data){console.log("Error Saving the address");
}});
}function updateEditedAddress(addressName,newNick){if(newNick!=null&&newNick!=""){$("#addressRefreshNickname").val(newNick);
dataString=$("#refreshAddressForm").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){}else{if(obj.error=="false"){$.ajax({type:"POST",url:"/checkout/gadgets/displayRefreshedAddress.jsp",data:{refreshAddressName:newNick},dataType:"html",success:function(data){var idDisplay="#address-section";
var element=$(idDisplay);
$(element).html(data);
changeSelectName($("select").get(),newNick,addressName);
loadShippingInfo();
}});
}}}});
}else{$("#addressRefreshNickname").val(addressName);
dataString=$("#refreshAddressForm").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){}else{if(obj.error=="false"){$.ajax({type:"POST",url:"/checkout/gadgets/displayRefreshedAddress.jsp",data:{refreshAddressName:addressName},dataType:"html",success:function(data){$("#address-section").html(data);
loadShippingInfo();
}});
}}}});
}}function updateShippingForm(nickname,newNick){if(newNick!=nickname){updateEditedAddress(nickname,newNick);
}else{updateEditedAddress(nickname,null);
}}function loadShippingInfo(){$.ajax({type:"POST",url:"/checkout/gadgets/selectedShippingInfo.jsp",data:null,dataType:"html",success:function(data){$("#shippingInfo").html(data);
$.modal.close();
$("#modalWindow").empty();
}});
}function getModalSearchForm(){$("#modalWindow").load("/search/modals/modal-searchFormMessage.jsp");
$("#modalWindow").modal({minWidth:320,minHeight:70});
}function changeSelectName(selects,newName,oldName){for(var i=0;
i<selects.length;
i++){var selectValue=selects[i];
if($(selectValue).val()==oldName){var select="#"+$(selects[i]).attr("id")+" option:selected";
$(select).val(newName);
$(select).html(newName);
}}}function sendFormOnPage(formId,page){var dataString=$("#"+formId).serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"jason",async:false});
window.location.href=page;
}function estimateCartShipping(formId){sendFormOnPage(formId,"/cart");
}function closeModal(){$.modal.close();
$("#modalWindow").empty();
}function closeSignUpLightboxModal(){closeModalWhenClickOutsideCallback(closeSignUpLightboxModalOmniture);
}function closeSignUpLightboxModalOmniture(){closeModal();
executeSignUpLightboxOmniture();
}function executeSignUpLightboxOmniture(){jus.omniture.executeEvent(jus.omniture.lightboxUserClosedSignUp());
}function closeModalWhenClickOutside(){closeModalWhenClickOutsideCallback(closeModal);
}function closeModalWhenClickOutsideCallback(callBackFunction){$("#simplemodal-overlay").on("click",callBackFunction);
}function f_scrollTop(){return f_filterResults(window.pageYOffset?window.pageYOffset:0,document.documentElement?document.documentElement.scrollTop:0,document.body?document.body.scrollTop:0);
}function f_filterResults(n_win,n_docel,n_body){var n_result=n_win?n_win:0;
if(n_docel&&(!n_result||(n_result>n_docel))){n_result=n_docel;
}return n_body&&(!n_result||(n_result>n_body))?n_body:n_result;
}function checkShippingAddresses(){var selects=document.getElementsByName("selectTheShippingAddress");
var result=true;
for(var i=0;
i<selects.length;
i++){if(0==selects[i].selectedIndex){result=false;
break;
}}if(!result){$("#shippingErrors").html("Please enter shipping address information for items in my bag.");
}return result;
}function imposeMaxLength(txt,MaxLen){if(txt.value.length>MaxLen){txt.value=txt.value.substring(0,MaxLen);
}}function changeShippingMethod(el,sgName,ci){$.blockUI({message:null,overlayCSS:{opacity:0}});
$("#checkout-newShippingMethod").val($(el).val());
$("#checkout-newShippingMethodItem").val(ci);
$("#checkout-newShippingMethodGroup").val(sgName);
var dataString=$("#checkout-setShippingAddress").serialize();
$.ajaxSettings.cache=false;
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",success:function(data){$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp",function(){if(typeof dataLayer!="undefined"){if($("#dlShippingAmount").length>0){dataLayer.shippingCost=parseFloat($("#dlShippingAmount").text().replace(/[^\d\.]/g,""));
}if($("#dlTaxAmount").length>0){dataLayer.taxAmount=parseFloat($("#dlTaxAmount").text().replace(/[^\d\.]/g,""));
}}}).error(function(){$.unblockUI();
});
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
var selectedShipMethod=$("input[name='/atg/commerce/order/purchase/ShippingGroupFormHandler.shippingMethods']:checked").val();
if(selectedShipMethod!=shipToStoreMethod){$("#selectedMethodBeforeSTS").val(selectedShipMethod+"-"+sgName+"-"+ci);
}if($("#shippingSTS").is(":checked")){$("#chooseShipToStore").prop("checked",true);
}}function checkPOBoxAddressCountry(){$.blockUI({message:null,overlayCSS:{opacity:0}});
$("#checkout-poBoxAddress").val($("#poBox").is(":checked"));
$("#checkout-country").val($("#country").val());
var dataString=$("#checkout-setPOBoxAddress").serialize();
$.ajaxSettings.cache=false;
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",success:function(data){$("#availableShippingMethods").load("/checkout/gadgets/selectedShippingInfo.jsp #availableShippingMethods").error(function(){$.unblockUI();
});
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}function checkShippingMethods(){$.blockUI({message:null,overlayCSS:{opacity:0}});
if(typeof $("[id^='checkoutSavedAddress']:checked").attr("nick")==="undefined"){$("#checkout-poBoxAddress").val($("#poBox").is(":checked"));
$("#checkout-country").val($("#country").val());
}else{var nick=$("[id^='checkoutSavedAddress']:checked").attr("nick");
var nickId=nick.toLowerCase().replace(/\s/g,"");
var isPoBox=$("#newAddressSubtitle_"+nickId+" #addrInfoDiv").attr("isPoBox")==="true";
var ctry=$("#newAddressSubtitle_"+nickId+" #addrInfoDiv").attr("country");
$("#checkout-poBoxAddress").val(isPoBox);
$("#checkout-country").val(ctry);
}var dataString=$("#checkout-setPOBoxAddress").serialize();
$.ajaxSettings.cache=false;
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",success:function(data){ajaxLoad("GET","/checkout/gadgets/selectedShippingInfo.jsp",dataString,"availableShippingMethods");
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}function ajaxLoad(method,url,dataString,divName){$.ajaxSettings.cache=false;
$.ajax({type:method,url:url,data:dataString,success:function(data){$(divName).html($(divName,data).html());
},async:true,dataType:"html"});
}function setCountry(){if($("#country").val()!=""){$.blockUI({message:null,overlayCSS:{opacity:0}});
$("#checkout-setcountry").val($("#country").val());
$("#checkout-setstate").val($("#state").val());
var dataString=$("#checkout-setCountry").serialize();
$.ajaxSettings.cache=false;
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",success:function(data){$("#availableShippingMethods").load("/checkout/gadgets/selectedShippingInfo.jsp #availableShippingMethods").error(function(){$.unblockUI();
});
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}}function setupGiftCertificatePaymentGroupsForOrder(){var giftCardNumbers=$("#htmlGiftCertificateNumbers").val();
$("#giftCertificateNumbers").val(giftCardNumbers);
var giftCardPins=$("#htmlGiftCertificatePins").val();
$("#giftCertificatePins").val(giftCardPins);
var dataString=$("#giftCertificatePayment").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",async:false,success:function(data){$("#checkout").load("/checkout/gadgets/stepThree.jsp");
}});
}function retrictGiftCardInputs(){$("#giftCertificateNumbers").keypress(function(e){if(e.which!=8&&e.which!=0&&(e.which<48||e.which>57)){e.preventDefault();
}});
$("#giftCertificatePins").keypress(function(e){if(e.which!=8&&e.which!=0&&(e.which<48||e.which>57)){e.preventDefault();
}});
}function removeGC(gcId){$("#giftCertificateToRemove").val(gcId);
$("#removeGiftCardForm").submit();
}function checkSKUQuality(productId){var result="";
var skuId=$("#catalogRefIds"+productId).val();
var quantity=parseInt($("#prodQtySelection").val());
if(isNaN(quantity)||1>quantity){result="Quantity you've selected is incorrect.";
}else{$.ajax({url:"/search/gadgets/skuCheckQuantity.jsp?skuId="+skuId,dataType:"json",async:false,success:function(json){var qty=parseInt(json.qty);
if(qty<quantity){result="The quantity you've selected exceeds the available inventory of "+qty+".";
}}});
}return result;
}function allNewArrivals(formId){$("#"+formId).submit();
}function submitFormById(formId){$("#"+formId).submit();
}function nothanks(){$.modal.close();
$("#modalWindow").empty();
}function openDelayedDialog(div_id){setTimeout(function(){$("#"+div_id).dialog("open");
},1000);
}function getContactPhone(){$("body").append('<div id="modalWindow_Phone"></div>');
$("#modalWindow_Phone").load("/metro/myaccount/includes/modal_phone.jsp").dialog({height:"auto",minWidth:340,minHeight:90,resizable:false,autoOpen:true,modal:true});
openDelayedDialog("modalWindow_PhoneEmail");
$(".ui-widget-overlay").click(function(){closeModalGeneric("modalWindow_Phone",false);
});
}function getContactEmail(){$("body").append('<div id="modalWindow_Email"></div>');
$("#modalWindow_Email").load("/metro/myaccount/includes/modal_email.jsp").dialog({height:"auto",minWidth:340,minHeight:90,resizable:false,autoOpen:true,modal:true});
openDelayedDialog("modalWindow_PhoneEmail");
$(".ui-widget-overlay").click(function(){closeModalGeneric("modalWindow_Email",false);
});
}function getMetroConnect(){$("body").append('<div id="metroConnectWindow"></div>');
$("#metroConnectWindow").load("/metro/includes/modal_metro-connect.jsp").dialog({height:"auto",minWidth:365,minHeight:355,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("metroConnectWindow");
}function getMyMetro(){$("body").append('<div id="myMetroWindow"></div>');
$("#myMetroWindow").load("/metro/includes/modal_mymetro.jsp").dialog({height:"auto",minWidth:310,minHeight:307,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("myMetroWindow");
}function getEWallet(){$("body").append('<div id="ewalletWindow"></div>');
$("#ewalletWindow").load("/metro/includes/modal_ewallet_benefits.jsp").dialog({height:"auto",minWidth:350,minHeight:485,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("ewalletWindow");
}function getOtherPaymentMethods(){$("body").append('<div id="otherPaymentsWindow"></div>');
$("#otherPaymentsWindow").load("/metro/includes/modal_other_payments.jsp").dialog({height:"auto",minWidth:660,minHeight:307,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("otherPaymentsWindow");
}function signupEmailOverlay(referer){var email=$("#guest-email").val();
$("#modalWindow").load("/global/modals/modal-emailSignUp.jsp?isModal=true&email="+email);
$("#modalWindow").modal({minWidth:381,onShow:function(dialog){dialog.container.css({"height":"auto"});
}});
$("#simplemodal-overlay").css("cursor","default");
}function submitEmailSignup(){var isModal=$("#signUpIsModal").val();
var age=$("#regAgeVerified").attr("checked");
var email=$("#regEmail").val();
var confEmail=$("#regConfirmEmail").val();
var errorObj={error:"false",invalidEmail:null,invalidConfirmEmail:null,duplicatedEmailSub:null,verifyAge:null};
if(!age){errorObj.error=true;
errorObj.invalidEmail="Please verify you are over 13";
}if(email==""||email==undefined){errorObj.error=true;
errorObj.invalidConfirmEmail="Please enter a valid email address";
}if(confEmail==""||confEmail==undefined){errorObj.error=true;
errorObj.verifyAge="Please enter a valid confirmation email address";
}if(errorObj.error=="false"){if(!isModal){$("#emailSignUp").submit();
}else{dataString=$("#emailSignUp").serialize();
$.ajax({type:"POST",url:"/staticpages/gadgets/validateEmailSignup.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="true"){displayEmailSignupErrors(data);
}else{if(data.error=="false"){$.modal.close();
$("#modalWindow").load("/global/modals/modal-emailSignUp.jsp?success=true&isModal=true");
$("#modalWindow").modal({minWidth:381,minHeight:181});
}}},error:function(jqXHR,textStatus,error){}});
}}else{displayEmailSignupErrors(errorObj);
}}function displayEmailSignupErrors(data){var errMsg="<div class='error-message' id='error-message'>";
if(data.invalidEmail!=null){errMsg+=data.invalidEmail+"<br/>";
}if(data.invalidConfirmEmail!=null){errMsg+=data.invalidConfirmEmail+"<br/>";
}if(data.duplicatedEmailSub!=null){errMsg+=data.duplicatedEmailSub+"<br/>";
}if(data.verifyAge!=null){errMsg+=data.verifyAge+"<br/>";
}errMsg+="</div>";
$("#errorMessages").html(errMsg);
}function closeOrderStatusModal(){$("#modalWindow").empty();
$.modal.close();
}function orderTrack(formId){var submit=false;
if(formId!="orderStatusModal"){$("#"+formId).submit();
return false;
}else{if($("#emailAddressModal").val()==""){$("#emailAddressModal").attr("class","error");
$("#emptyOrderEmailDivModal").show();
submit=true;
}if($("#orderIdModal").val()==""){$("#orderIdModal").attr("class","error");
$("#emptyOrderIdDivModal").show();
submit=true;
}if(!submit){$("#"+formId).submit();
return false;
}else{$("#error-messageModal").show();
}}}function checkCardType(){if($("#ccType").val()=="AmericanExpress"){$("#verificationNewNumberInput").attr({maxLength:4});
$("#verificationNewNumberInput").val("");
}else{$("#verificationNewNumberInput").attr({maxLength:3});
$("#verificationNewNumberInput").val("");
}}function checkCardType(value){if(value=="AmericanExpress"){$("#verificationNumberInput").attr({maxLength:4});
$("#verificationNumberInput").val("");
}else{$("#verificationNumberInput").attr({maxLength:3});
$("#verificationNumberInput").val("");
}if(value=="JusticeCreditCard"){$(".checkout-cart-code").hide();
}else{$(".checkout-cart-code").show();
}}function changeUcOrderId(){$("#orderId").bind("keyup",function(){$("#orderId").val(($("#orderId").val()).toUpperCase());
});
$("#orderId").bind("change",function(){$("#orderId").val(($("#orderId").val()).toUpperCase());
});
}function submitPasswordForgot(){dataString=$("#passwordForgot").serialize();
$.ajax({type:"POST",url:"/account/gadgets/validatePasswordForgot.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="false"){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/account/modals/modal-passwordforgotsuccess.jsp");
$("#modalWindow").modal({minWidth:420,minHeight:170});
}else{if(data.error=="true"){document.getElementById("simplemodal-container").style.height="272px";
$("#forgotPwdErrors").html(data.messages);
$("#forgotPwdErrors").show();
}}}});
}function getMessageFromRepository(messageCode){var message="";
$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId="+messageCode,dataType:"json",success:function(obj){if(obj.message){message=obj.message;
}}});
return message;
}function ImgLoad(myobj,oriSrc,naSrc){var oImg=new Image;
$(oImg).bind("load",function(){$(myobj).attr("width","180");
$(myobj).src=oImg.src;
});
$(oImg).error(function(){$(myobj).attr("width","180");
$(myobj).attr("src",naSrc);
});
oImg.src=oriSrc;
}function ImgLoadWidth(myobj,oriSrc,naSrc,width,clook,productId){var selectedColorCode="selectedColorCode";
clook=clook||"false";
if(clook=="true"){selectedColorCode="clookSelectedColorCode";
}var oImg=new Image;
$(oImg).bind("load",function(){$(myobj).attr("width",width);
$(myobj).src=oImg.src;
});
$(oImg).error(function(){color=$("#"+selectedColorCode+productId).val();
if(color!="false"&&color!=undefined){$(myobj).attr("width",width);
$(myobj).attr("src",naSrc);
}else{$(myobj).attr("src","");
}});
oImg.src=oriSrc;
}function imgError(image,src){image.src=src;
return true;
}function removeSleeve(commerceItemId,sleeveQuantity,holderProductId){var commerceItemQuantity=parseInt($("#updateGiftCardQuantity input[name="+commerceItemId+"]").val());
var updatedCommerceItemQuantity=commerceItemQuantity-sleeveQuantity;
$("#updateGiftCardQuantity input[name="+commerceItemId+"]").val(updatedCommerceItemQuantity);
$("#updateGiftCardQuantity input[name=holderProductId]").val(holderProductId);
$("#updateGiftCardQuantity input[name=giftCardCommerceItemId]").val(commerceItemId);
$("#updateGiftCardQuantity").submit();
}function submitAddLoyaltyCard(controlIndex){$("#loyaltyCardNumber").val($("#loyaltyCardNumber_"+controlIndex).val());
$("#addLoyaltyCardForm").submit();
}function submitRemoveLoyaltyCard(cardNumber){$("#removeloyaltyCardNumber").val(cardNumber);
$("#removeLoyaltyCard").submit();
}function submitCurrentRedemptionType(redemptionType){$("#newRedemptionType").val(redemptionType);
$("#updateCurrentRedemptionType").submit();
}function showCouponCodeOverlay(){$("#modalWindow").load("/cart/modals/couponCodeOverlay.jsp");
$("#modalWindow").modal({minWidth:700,minHeight:550});
$("#simplemodal-overlay").css("cursor","default");
}function showGiftWrapOverlay(){$("#modalWindow").load("/cart/modals/giftWrapOverlay.jsp");
$("#modalWindow").modal({minWidth:550,minHeight:425});
$("#simplemodal-overlay").css("cursor","default");
}function showJBucksFunCardsOverlay(){$("#modalWindow").load("/cart/modals/jBucksFunCardsOvelay.jsp");
$("#modalWindow").modal({minWidth:700,minHeight:425});
$("#simplemodal-overlay").css("cursor","default");
}function showFreeReturnsOverlay(){$("#modalWindow").load("/global/modals/modal-freeReturns.jsp");
$("#modalWindow").modal({minWidth:450,minHeight:565});
$("#simplemodal-overlay").css("cursor","default");
}function showShipToStoreLocationOverlay(){$("#modalWindow").load("/checkout/modals/modal-shiptostore-location.jsp");
$("#modalWindow").modal({minWidth:665,minHeight:290});
$("#simplemodal-overlay").css("cursor","default");
}function showShipToStorePickupOverlay(){$("#modalWindow").load("/checkout/modals/modal-shiptostore-pickup.jsp");
$("#modalWindow").modal({minWidth:665,minHeight:166});
$("#simplemodal-overlay").css("cursor","default");
}function beginCheckout(){var addGiftWrap=$("#addGiftWrapCheckBox").attr("checked");
if(addGiftWrap=="checked"){$.blockUI({message:null,overlayCSS:{opacity:0}});
dataString=$("#giftWrapMsg").serialize();
$.ajax({type:"POST",async:false,url:$("#giftWrapMsg").attr("action"),data:dataString,dataType:"text",success:function(data){$("#checkoutForm").submit();
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}else{$("#checkoutForm").submit();
}}function submitShippingForm(){if($("#checkoutSavedAddress").val()=="true"){var addressNickname=$('input[type="radio"][id^="checkoutSavedAddress"]:checked');
if(addressNickname.val()==null||addressNickname.val()==""){$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId=invalidShippingAddress",dataType:"json",success:function(obj){if(obj.message){addErrorMessage(obj.message);
$("#addressSelected").addClass("error");
return;
}}});
}else{var checkoutMultiShippingAddress=document.getElementById("checkoutMultiShippingAddress");
checkoutMultiShippingAddress.action=checkoutMultiShippingAddress.action+"&addressNickname="+addressNickname.val();
$("#continueButton").click();
}}else{if($("#checkoutNewAddress").attr("checked")=="checked"||$("#checkoutNewAddress").attr("checked")==true){var checkoutMultiShippingAddress=document.getElementById("checkoutMultiShippingAddress");
checkoutMultiShippingAddress.action=checkoutMultiShippingAddress.action+"&name="+$("#nickName").val();
$("#continueButton").click();
}else{$("#continueButton").click();
}}}function submitShippingAddressForm(){if($("#checkoutNewAddress").attr("checked")=="checked"||$("#checkoutNewAddress").attr("checked")==true){var checkoutMultiShippingAddress=document.getElementById("checkoutMultiShippingAddress");
alert(checkoutMultiShippingAddress.action);
$("#continueButton2").click();
}}function addErrorMessage(msg){if($("#shippingErrors").html().trim()==""){$("#shippingErrors").append("<div id='error-message' class='error-message'></div>");
}var errors=$("#error-message").html().trim();
if(errors.indexOf(msg)==-1){$("#error-message").append(msg+"<br>");
}}function isVisible(){setCountry();
}$("#newAddressForm").bind("isVisible",isVisible);
$("#newAddressForm").show("slow",function(){$(this).trigger("isVisible");
});
function setCorrectFormDisplay(){$(".oc_resume_box").show();
$("#new_address_fields").hide();
}function toggleNewBillingAddress(){if($("#new_address").length==0||$("#new_address").is(":checked")){$("#new_address_fields").show();
if($("#billingErrors #error-message #billingErrorLines").html().trim().length!=0){$("#billingErrors #error-message").show();
}}else{$("#new_address_fields").hide();
$("#billingErrors #error-message").hide();
}}function clearBillingForm(){var shouldClearNickName=null;
if(arguments.length>0){shouldClearNickName=arguments[0];
}if($("#billingErrors #error-message #billingErrorLines").html().trim().length==0){if(shouldClearNickName!==null){$("#billAddr-nickname").val("");
}$("#billAddr-fName").val("");
$("#billAddr-lName").val("");
$("#billAddr-address").val("");
$("#billAddr-address2").val("");
$("#billAddr-pobox").prop("checked",false);
$("#billAddr-city").val("");
$("#state").val("");
$("#billAddr-postal").val("");
$("#homePhone1").val("");
$("#homePhone2").val("");
$("#homePhone3").val("");
$("#shipping_for_billing").prop("checked",true);
}else{if(shouldClearNickName!==null){clearErrorField("#billAddr-nickname");
}clearErrorField("#billAddr-fName");
clearErrorField("#billAddr-lName");
clearErrorField("#billAddr-address");
clearErrorField("#billAddr-address2");
clearErrorField("#billAddr-city");
clearErrorField("#state");
clearErrorField("#billAddr-postal");
clearErrorField("#homePhone1");
clearErrorField("#homePhone2");
clearErrorField("#homePhone3");
}}function clearErrorField(selector){if($(selector).hasClass("error")){$(selector).val("");
}}function clearShippingForm(shouldClearNickName){if($("#error-message").html().trim().length!=0){$("#shippingErrors #error-message").show();
if(shouldClearNickName){clearErrorField("#nickName[type='text']");
}clearErrorField("#firstName");
clearErrorField("#lastName");
clearErrorField("#address1");
clearErrorField("#address2");
clearErrorField("#city");
clearErrorField("#state");
clearErrorField("#zipCode");
clearErrorField("#phone1");
clearErrorField("#phone2");
clearErrorField("#phone3");
}else{if(shouldClearNickName){$("#nickName[type='text']").val("");
}$("#firstName").val("");
$("#lastName").val("");
$("#address1").val("");
$("#address2").val("");
$("#poBox").prop("checked",false);
$("#city").val("");
$("#state").val("");
$("#zipCode").val("");
$("#phone1").val("");
$("#phone2").val("");
$("#phone3").val("");
}}function setBillingNickname(nick){$("#billAddr-nickname").val(nick);
}function enableEditButton(nick){var nick=nick||"false";
var nickId=nick.replace(/\s/g,"");
$(".addrEdtBtn").attr("disabled","disabled");
$(".addrEdtBtn").attr("class","addrEdtBtn checkout-edit-btn disabled");
$("#"+nickId.toLowerCase()+"_edt_btn").removeAttr("disabled");
$("#"+nickId.toLowerCase()+"_edt_btn").attr("class","change checkout-edit addrEdtBtn");
$("div[id*='_edt_addr_fields']").hide();
$("div[id*='_shippingAddressInfo']").show();
}function showCarousel(categoryId){closeModal();
$("#modalWindow").load("/catalog/modals/modal-carousel.jsp?categoryId="+categoryId);
$("#modalWindow").modal({minWidth:675,minHeight:400});
$("#simplemodal-overlay").css("cursor","default");
}function shipToStoreBinding(){$("#sts_zipcode").keypress(function(event){if(event.which==13){event.preventDefault();
showFoundStoresOverlay();
}});
}function showFoundStoresOverlay(){var state=$.trim($("#sts_state option:selected").val());
var zipCode=$.trim($("#sts_zipcode").val());
var usedValue=$.trim($("#stsFormStoreSearchedValue").val());
$("#sts-error-message").html("");
$("#sts_state").removeClass("error");
$("#sts_zipcode").removeClass("error");
if(state.length==0){var re=/^\d+$/;
var isValid=re.exec(zipCode);
if(zipCode!=""){if(!isValid){$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId=invalidPostal",dataType:"json",success:function(obj){if(obj.message){$("#stsFormStoreSearchedValue").val("zipCode"+zipCode);
$("#sts-error-message").show();
$("#sts_zipcode").addClass("error");
if($.trim($("#sts-error-message").val()).length>0){$("#sts-error-message").append("<br>");
}$("#sts-error-message").append(obj.message);
}}});
}else{$("#sts-error-message").hide("");
$("#stsFormStoreSearchedValue").val("zipCode"+zipCode);
$("#modalWindow").load("/checkout/modals/modal-select-store.jsp?zipcode="+zipCode+"&radius=25&state=&searchMap=false&stateName=&titleCaseStateName=");
$("#modalWindow").modal({minWidth:380,minHeight:600});
$("#simplemodal-overlay").css("cursor","default");
}}else{$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId=invalidZipcodeState",dataType:"json",success:function(obj){if(obj.message){$("#stsFormStoreSearchedValue").val("zipCode"+zipCode);
$("#sts-error-message").show();
$("#sts_zipcode").addClass("error");
$("#sts_state").addClass("error");
if($.trim($("#sts-error-message").val()).length>0){$("#sts-error-message").append("<br>");
}$("#sts-error-message").append(obj.message);
}}});
}}else{$("#sts-error-message").hide("");
$("#stsFormStoreSearchedValue").val(state);
$("#modalWindow").load("/checkout/modals/modal-select-store.jsp?zipcode=&radius=25&state="+state+"&searchMap=false&stateName=&titleCaseStateName=");
$("#modalWindow").modal({minWidth:380,minHeight:600});
$("#simplemodal-overlay").css("cursor","default");
}}function showStepTwoSections(type){if(type=="normal"){$("#addressInfo").show();
$("#availableShippingMethods").show();
$(".continueToPayment").show();
$("#stsSelectStore").hide();
$("#stsPickupInfo").hide();
$("#stsSelectedStore").hide();
if(!$("#addressDisplay").is(":visible")){$(".oc_resume_box").show();
}if($.trim($("#selectedMethodBeforeSTS").val()).length>0){var selectedMethod=$("#selectedMethodBeforeSTS").val().split("-");
$("#shipping"+selectedMethod[0]).prop("checked",true);
changeShippingMethod($("#shipping"+selectedMethod[0]),selectedMethod[1],selectedMethod[2]);
}else{$("#shippingSMRT").prop("checked",true);
changeShippingMethod($("#shippingSMRT"),$("#shippingAddressNickname").val(),"");
}if($.trim($("#error-message").text()).length>0){$("#error-message").show();
}}else{var selectedMethod=$("#selectedMethodBeforeSTS").val().split("-");
changeShippingMethod($("#shippingSMRR"),selectedMethod[1],selectedMethod[2]);
$("#addressInfo").hide();
$("#availableShippingMethods").hide();
$(".continueToPayment").hide();
$(".oc_resume_box").hide();
$("#stsSelectStore").show();
$("#stsPickupInfo").show();
$("#error-message").hide();
showSelectedStore();
}}function showGuestStepTwoSections(type){if(type=="normal"){$("#addressInfo").show();
if($("#addressDisplay").length>0){$("#addressDisplay").show();
}else{$(".oc_resume_box").show();
}if($.trim($("#error-message").text()).length>0){$("#error-message").show();
}$("#availableShippingMethods").show();
$("#stsSelectStore").hide();
$("#stsPickupInfo").hide();
$("#stsSelectedStore").hide();
if($.trim($("#selectedMethodBeforeSTS").val()).length>0){var selectedMethod=$("#selectedMethodBeforeSTS").val().split("-");
$("#shipping"+selectedMethod[0]).prop("checked",true);
changeShippingMethod($("#shipping"+selectedMethod[0]),selectedMethod[1],selectedMethod[2]);
}else{$("#shippingSMRT").prop("checked",true);
changeShippingMethod($("#shippingSMRT"),$("#shippingAddressNickname").val(),"");
}}else{if($.trim($("#selectedMethodBeforeSTS").val()).length>0){var selectedMethod=$("#selectedMethodBeforeSTS").val().split("-");
changeShippingMethod($("#shippingSMRR"),selectedMethod[1],selectedMethod[2]);
}else{changeShippingMethod($("#shippingSMRR"),$("#shippingAddressNickname").val(),"");
}$("#addressInfo").hide();
$("#availableShippingMethods").hide();
$("#addressDisplay").hide();
$(".oc_resume_box").hide();
$("#stsSelectStore").show();
$("#stsPickupInfo").show();
$("#error-message").hide();
showSelectedStore();
}}function selectStore(storeId){$("#stsFormStore").val(storeId);
$(".shipToStoreHours").html("");
$("#shipToStoreName").html("<b>"+$(".storeResultNameContainer."+storeId).text()+"</b>");
$(".storeSelectedAddress1").html($(".storeResultStreetContainer."+storeId).text());
$(".storeSelectedCityCountryZipcode").html($("#storeResultStateContainer_"+storeId).text());
$(".storeSelectedCountry").html($("#storeSelectedCountry_"+storeId).text());
$(".storeSelectedPhone").html($(".storeResultPhoneContainer."+storeId).text());
$.each($(".storeResultHourContainer."+storeId),function(index,value){if($.trim($(".shipToStoreHours").text()).length>0){$(".shipToStoreHours").append("<br>");
}$(".shipToStoreHours").append("<span>"+$(value).text()+"</span>");
});
$(".storeSelectedDistance").html($(".storeResultDistanceContainer."+storeId).text());
$("#stsSelectedStore").show();
$("#stsSelectStore").hide();
closeModal();
$("body").css("overflow","scroll");
}function backToSelectStore(){var usedValue=$.trim($("#stsFormStoreSearchedValue").val());
$("#stsFormStore").val("");
$("#shipToStoreName").text("");
$("#stsSelectStore").show();
$("#stsSelectedStore").hide();
if(usedValue.length>0){if(usedValue.indexOf("zipCode")!=-1){usedValue=usedValue.replace("zipCode","");
$("#sts_zipcode").val(usedValue);
}else{$("#sts_state option:selected").attr("selected",null);
$("select#sts_state option[value='"+usedValue+"']").attr("selected","selected");
}}}function showSelectedStore(){if($.trim($("#shipToStoreName").text()).length>0){$("#stsSelectedStore").show();
$("#stsSelectStore").hide();
}else{$("#stsSelectStore").show();
$("#stsSelectedStore").hide();
}}function showChooseShippingOverlay(){$("#modalWindow").load("/cart/modals/giftWrapOverlay.jsp");
$("#modalWindow").modal({minWidth:550,minHeight:425});
$("#simplemodal-overlay").css("cursor","default");
}function showPickupInfoOverlay(){$("#modalWindow").load("/cart/modals/giftWrapOverlay.jsp");
$("#modalWindow").modal({minWidth:550,minHeight:425});
$("#simplemodal-overlay").css("cursor","default");
}function showRegisterForm(){if($("#registerCheckbox").is(":checked")){$("#oc_create_detail").show();
$("#oc_buttons").hide();
}else{$("#oc_create_detail").hide();
$("#oc_buttons").show();
}}function getCreateCreditCardForm(){if($("#createCreditCard").is(":checked")){$.ajax({type:"POST",url:"/checkout/gadgets/stepFiveCreditCardForm.jsp",data:"",dataType:"html",success:function(data){$("#createCreditCardForm").html(data);
}});
}else{$("#createCreditCardForm").html("");
}}function addOmnitureElem(qty,price){sjData.products[0].quantity=qty;
sjData.products[0].price=price;
}function BVcheckLoadState(bv_url){if(!BVisLoaded){var bVFrame=document.getElementById("BVFrame"),vVReviewsContainer=document.getElementById("BVReviewsContainer"),page;
if(bVFrame&&vVReviewsContainer){page=bVFrame.src;
bVFrame.src=bv_url+"logging?page="+escape(page);
vVReviewsContainer.innerHTML="<!-- Review retrieval timed out -->";
}}}function bvLoadRR(bv_url,bv_site_code,productId){var bvPage=bv_url+bv_site_code+productId+"/reviews.htm?format=embedded";
var bvReviewIDName="featurereview";
var bvReviewIDRegex=new RegExp("[?&]"+bvReviewIDName+"=([^&#]+)");
var bvReviewIDMatch=bvReviewIDRegex.exec(window.location.search);
var bvReviewID=bvReviewIDMatch?decodeURIComponent(bvReviewIDMatch[1]):null;
document.getElementById("BVFrame").src=/^[0-9]+$/.test(bvReviewID)?bvPage+"&reviewid="+bvReviewID:bvPage;
setTimeout("BVcheckLoadState('"+bv_url+"')",15000);
}function updateCertonaTags(item_id,color_id,event){if(typeof(event)=="undefined"){event="product";
}if(typeof(resx)!="undefined"&&resx!=null){resx.event=event;
resx.itemid=item_id+"_"+color_id;
if(event!="shopping+bag"){resx.rrqs="ColorCode="+color_id;
}certonaResx.run();
}}function addOmnitureElem(qty,price){sjData.products[0].quantity=qty;
sjData.products[0].price=price;
}function callCustomEvent(eventName,data1,data2,data3){if(typeof sj!=="undefined"){if(typeof sj.customEvent!=="undefined"){if(eventName=="emailFriend"){sj.customEvent(eventName);
}else{sj.customEvent(eventName,data1,data2,data3);
}}}}function getURLParameter(sParam){var sPageURL=window.location.search.substring(1);
var sURLVariables=sPageURL.split("&");
for(var i=0;
i<sURLVariables.length;
i++){var sParameterName=sURLVariables[i].split("=");
if(sParameterName[0]==sParam){return sParameterName[1];
}}return null;
}(function(){window.jus=window.jus||{};
window.jus.lightbox=window.jus.lightbox||{};
window.jus.lightbox.loadAgeGateContents=function loadAgeGateContents(){$("#modalLightbox").load("/lightbox/modals/modal-ageGateLightbox.jsp").modal({minWidth:jus.configs.lightbox.ageGateLightboxOverlayWidth,minHeight:jus.configs.lightbox.ageGateLightboxOverlayHeight,onShow:function(dialog){dialog.container.css({"height":"auto"});
dialog.container.css({"width":"auto"});
}});
$("#simplemodal-overlay").css("cursor","default");
};
window.jus.lightbox.copyValuesToHiddenFormComponents=function copyValuesToHiddenFormComponents(){var month=jus.lightbox.getSelectedInputValue("monthLightboxSignUp");
jus.lightbox.setSelectedInputValue("birthMonthLightbox",month);
var year=jus.lightbox.getSelectedInputValue("yearLightboxSignUp");
jus.lightbox.setSelectedInputValue("birthYearLightbox",year);
var email=jus.lightbox.getInputValue("emailLightboxSignUp");
jus.lightbox.setInputValue("emailLightboxInput",email);
};
window.jus.lightbox.lightboxGeneralBinding=function lightboxGeneralBinding(){$(".closeLightboxOverlays").click(function(event){event.preventDefault();
closeModal();
});
};
window.jus.lightbox.validateAge=function validateAge(month,year){if(month==""||year==""){$("#emailLightboxSignUp").prop("disabled",true);
return;
}else{$("#emailLightboxSignUp").prop("disabled",false);
}var age=13;
var userBirthDay=new Date();
userBirthDay.setFullYear(year,month,0);
userBirthDay.setHours(0,0,0,0);
var limitAge=new Date();
limitAge.setHours(0,0,0,0);
limitAge.setFullYear(limitAge.getFullYear()-age);
if(userBirthDay>limitAge){closeModal();
fireAgeGateLightbox();
}};
window.jus.lightbox.matchLightBoxSignUpHTMLElementsToBCC=function matchLightBoxSignUpHTMLElementsToBCC(){$("#monthLightboxSignUp").empty();
$("#birthMonthLightbox > option").each(function(){$("#monthLightboxSignUp").append($("<option></option>").attr("value",this.value).text(this.text));
});
$("#yearLightboxSignUp").empty();
$("#birthYearLightbox > option").each(function(){$("#yearLightboxSignUp").append($("<option></option>").attr("value",this.value).text(this.text));
});
jus.lightbox.setFirstOptionGhosted("monthLightboxSignUp");
jus.lightbox.setFirstOptionGhosted("yearLightboxSignUp");
var emailObject=$("#emailLightboxSignUp");
emailObject.prop("disabled",true);
emailObject.addClass("inputText-disabled");
emailObject.attr("maxlength","254");
$("#errorMessagesLightBox").appendTo("#errorBoxLightboxSignUp");
$("#signUpLightboxPlaceHolder").show();
};
window.jus.lightbox.lightboxSignUpBinding=function lightboxSignUpBinding(){console.log("lightbox: binding UI...");
$(document).one("keydown.simplemodal",function(event){if(event.keyCode==27){executeSignUpLightboxOmniture();
}});
$("#submitLightboxSignUp").click(function(event){event.preventDefault();
jus.lightbox.copyValuesToHiddenFormComponents();
$("#lightboxForm").submit();
});
$("#lightboxForm").submit(function(event){event.preventDefault();
if(!lightboxValidateInput()){return;
}var postData=$(this).serialize();
var formURL=$(this).attr("action");
$.ajax({url:formURL,type:"POST",data:postData,dataType:"json",cache:false,success:function(data,textStatus,jqXHR){var result=data.result;
var repeated=data.repeated;
var invalidAge=data.invalidAge;
var formErrors=data["form-errors"];
var internalError=data.internalError;
if(result==="OK"){closeModal();
showThankYouLightboxOverlay();
}else{if(formErrors){var errorsMap=lightboxMakeDisplayErrorsMap();
for(var index in formErrors){var errorFunction=errorsMap[formErrors[index]];
if(isFunction(errorFunction)){errorFunction();
}}if(formErrors.length){lightboxFormErrorsOmniture();
lightboxShowErrorMessage();
}}else{if(invalidAge===true){closeModal();
fireAgeGateLightbox();
}else{if(internalError===true){console.log("internalError: ","jqXHR: ",jqXHR,"textStatus: ",textStatus,"jqXHR: ",jqXHR);
closeModal();
showThankYouLightboxOverlay();
}else{console.log("[LIGHTBOX] ELSE: UNEXPECTED BEHAVIOR","jqXHR: ",jqXHR,"textStatus: ",textStatus,"jqXHR: ",jqXHR);
closeModal();
showThankYouLightboxOverlay();
}}}}},error:function(jqXHR,textStatus,errorThrown){console.log("data: ",data,"textStatus: ",textStatus,"errorThrown: ",errorThrown);
closeModal();
}});
function lightboxMakeDisplayErrorsMap(){return{invalidEmailAddressLightBox:lightboxDisplayEmailError,missingMonthLightBox:lightboxDisplayMonthError,missingYearLightBox:lightboxDisplayYearError};
}});
$("#monthLightboxSignUp").on("change",function(e){var monthValue=this.value;
changeColorSelectedOption(this);
var yearValue=jus.lightbox.getSelectedInputValue("yearLightboxSignUp");
jus.lightbox.validateAge(monthValue,yearValue);
});
$("#yearLightboxSignUp").on("change",function(e){var yearValue=this.value;
changeColorSelectedOption(this);
var monthValue=jus.lightbox.getSelectedInputValue("monthLightboxSignUp");
jus.lightbox.validateAge(monthValue,yearValue);
});
$("#closeLightboxSignUp").click(function(event){event.preventDefault();
removeHrefToAvoidUnexpectedBehaviorOnAnalytics($(this));
executeSignUpLightboxOmniture();
});
jus.lightbox.matchLightBoxSignUpHTMLElementsToBCC();
};
window.jus.lightbox.getSelectedInputValue=function getSelectedInputValue(selectInput){return $("#"+selectInput+" option:selected").val();
};
window.jus.lightbox.setSelectedInputValue=function setSelectedInputValue(selectInput,value){$("#"+selectInput).find('option[value="'+value+'"]').attr("selected",true);
};
window.jus.lightbox.isValidEmailAddress=function isValidEmailAddress(emailAddress){return emailPattern.test(emailAddress);
};
window.jus.lightbox.getInputValue=function getInputValue(input){return $("#"+input).val();
};
window.jus.lightbox.setInputValue=function setInputValue(input,value){$("#"+input).val(value);
};
window.jus.lightbox.setFirstOptionGhosted=function setFirstOptionGhosted(selectInput){$("#"+selectInput+" option:first-child").css("color","#666");
};
})();
function setAgeGateCookies(){$.get("/lightbox/onAgeGate.jsp");
}function showSignUpLightboxOverlay(acquisitionSource){$("#modalLightbox").load("/lightbox/modals/modal-signUpLightbox.jsp?acquisitionSource="+acquisitionSource).modal({minWidth:jus.configs.lightbox.signUpLightboxOverlayWidth,minHeight:jus.configs.lightbox.signUpLightboxOverlayHeight,onShow:function(dialog){dialog.container.css({"height":"auto"});
dialog.container.css({"width":"auto"});
}});
$("#simplemodal-overlay").css("cursor","default");
}function fireAgeGateLightbox(){var errors=["age gate block"];
jus.omniture.executeEvent(jus.omniture.lightboxFormErrors(errors));
jus.lightbox.loadAgeGateContents();
}function showThankYouLightboxOverlay(){jus.omniture.executeEvent(jus.omniture.lightboxThankYou());
$("#modalLightbox").load("/lightbox/modals/modal-thankYouLightbox.jsp").modal({minWidth:jus.configs.lightbox.thankYouLightboxOverlayWidth,minHeight:jus.configs.lightbox.thankYouLightboxOverlayHeight,onShow:function(dialog){dialog.container.css({"height":"auto"});
dialog.container.css({"width":"auto"});
}});
$("#simplemodal-overlay").css("cursor","default");
}function lightboxValidateInput(){clearSignUpLightBoxState();
var showErrorMessage=false;
var emailValue=$.trim($("#emailLightboxInput").val());
if(emailValue==""||!jus.lightbox.isValidEmailAddress(emailValue)){lightboxDisplayEmailError();
showErrorMessage=true;
}var monthValue=$("#birthMonthLightbox").val();
if(monthValue==""){lightboxDisplayMonthError();
showErrorMessage=true;
}var yearValue=$("#birthYearLightbox").val();
if(yearValue==""){lightboxDisplayYearError();
showErrorMessage=true;
}if(showErrorMessage){lightboxFormErrorsOmniture();
lightboxShowErrorMessage();
return false;
}return true;
}function lightboxDisplayEmailError(){$("#emailLightboxInput").addClass("error");
$("#emailLightboxError").show();
}function lightboxDisplayYearError(){$("#birthYearLightbox").addClass("error");
$("#birthYearLightboxError").show();
}function lightboxDisplayMonthError(){$("#birthMonthLightbox").addClass("error");
$("#birthMonthLightboxError").show();
}function lightboxShowErrorMessage(){$("#errorMessagesLightBox").show();
}function isFunction(obj){return"function"===typeof obj;
}function changeColorSelectedOption(selectInput){if(selectInput.value==""){$(selectInput).css("color","#666");
}else{$(selectInput).css("color","#333");
}}function clearSignUpLightBoxState(){$("#errorMessagesLightBox").hide();
$("#emailLightboxError").hide();
$("#emailLightboxInput").removeClass("error");
$("#birthYearLightboxError").hide();
$("#birthYearLightbox").removeClass("error");
$("#birthMonthLightboxError").hide();
$("#birthMonthLightbox").removeClass("error");
}function removeHrefToAvoidUnexpectedBehaviorOnAnalytics(linkObject){linkObject.removeAttr("href");
}function lightboxFormErrorsOmniture(){var formErrorsIds=["birthMonthLightboxError","birthYearLightboxError","emailLightboxError"];
var errors=getLightboxFormErrors(formErrorsIds);
if(errors.length>0){jus.omniture.executeEvent(jus.omniture.lightboxFormErrors(errors));
}}function getLightboxFormErrors(idErrorsDiv){var formErrors=[];
for(var i=0;
i<idErrorsDiv.length;
i++){var idDiv=idErrorsDiv[i];
if($("#"+idDiv).css("display")!="none"){formErrors.push($.trim($("#"+idDiv).text()));
}}return formErrors;
}$(document).ready(function(){$("#CUSubjectSelect").change(function(){$("#enquiryInput").val($("#CUSubjectSelect").val());
});
$("#submitContactForm").click(function(){$("#ContactUsForm").submit();
});
var selectedValue=$("#enquiryInput").val();
if(selectedValue!=""){$("#CUSubjectSelect").val(selectedValue);
}});
