





var basePolicyJSON = '{\"guide\":{\"fmt\":\"results-products\",\"ok\":true},\"baynoteObserver\":{\"dt\":20,\"so\":true,\"uhd\":false,\"cds\":true,\"eec\":true,\"cdt\":true,\"ioi\":true,\"hn\":\"handler2.js\",\"ec\":true,\"uca\":\"315360000000\",\"alt\":true,\"om\":2,\"ep\":50,\"ub\":false,\"sv\":true,\"sdl\":false,\"ok\":true,\"st\":true},\"search\":{\"ok\":true},\"customScript\":{\"hn\":\"custom-script.js\"},\"trail\":{\"tl\":5,\"so\":false,\"ok\":false},\"GuideSet\":{\"eids\":[\"BN_prodDetail\",\"BN_prodDetail_1\",\"BN_CartDiversityIssue\",\"BN_ScopeTest\",\"BN_PD_Wtest\",\"BN_prodDetail_boysB\",\"BN_women2\",\"BN_prodDetail_girlsB\",\"BN_prodDetail_MensB\",\"BN_prodDetail_shoesB\",\"BN_prodDetail_wedB\",\"BN_prodDetail_swimB\",\"BN_prodDetail_womensB\",\"BN_HomeSearch\",\"BN_prodDetail_boys_A_sweaters\",\"BN_prodDetail_girls_A_Sweaters\",\"BN_prodDetail_girls_sweaters2\",\"BN_prodDetail_girls_sweaters_B\",\"BN_prodDetail_boys_sweaters2\",\"BN_prodDetail_boys_sweaters_B\",\"BN_prodDetail_girls_export\",\"BN_prodDetail_boys_test\",\"BN_prodDetail_boys_export\",\"BN_prodDetail_Mens_export\",\"BN_prodDetail_shoes_export\",\"BN_prodDetail_swim_export\",\"BN_prodDetail_tmp_export\",\"BN_prodDetail_wed_export\",\"BN_prodDetail_womens_export\",\"BN_prodDetail_womens_shirtsTops_A\",\"BN_prodDetail_womens_shirtsTops_export\",\"BN_Womens_ShirtsandTops\",\"BN_Womens_ShirtsandTops_B\",\"BN_Womens_Shoes\",\"BN_Womens_Shoes_B\",\"BN_prodDetail_boys_A_sweaters_export\",\"BN_prodDetail_girls_A_Sweaters_export\",\"BN_prodDetail_shoes_A\",\"BN_prodDetail_W_shoes_A\",\"BN_prodDetail_W_shoes_A_export\",\"BN_Womens_Sweaters_B\",\"BN_prodDetail_girls\",\"BN_prodDetail_girls_A\",\"BN_prodDetail_boys\",\"BN_prodDetail_boys_A\",\"BN_prodDetail_Mens\",\"BN_prodDetail_Mens_A\",\"BN_prodDetail_shoes\",\"BN_prodDetail_swim\",\"BN_prodDetail_swim_A\",\"BN_prodDetail_tmp\",\"BN_prodDetail_tmp_A\",\"BN_prodDetail_wed\",\"BN_prodDetail_wed_A\",\"BN_prodDetail_womens\",\"BN_prodDetail_womens_A\",\"BN_Cart_Export\",\"BN_Cart_B\",\"BN_Cart\",\"BN_Cart_A\",\"new2013\",\"old2012\",\"BN_ProdD_baby_A\",\"BN_ProdD_baby_B\",\"BN_ProdD_baby_export\",\"BN_Search\",\"BN_TEST_TEMPLATE\",\"BN_prodDetail_pinned_A\",\"BN_prodDetail_pinned_B\",\"BN_pdp_Mens_Shirt_A\",\"BN_pd_Mens_Shirt_B\",\"BN_pdp_Mens_Shirt_B\",\"BN_pd_Womens_Dresses_A\",\"BN_pdp_Womens_Dresses_A\",\"BN_pd_Womens_Dresses_B\",\"BN_pdp_Womens_Dresses_B\",\"BN_CartRecsTEST\",\"BN_CartRecsTEST2\",\"BN_Cart_2013\",\"BN_CartTEST\",\"BN_prodDetail_tmpB\",\"BN_HandBags\",\"BN_Cart_2013_exp\",\"BN_Cart_2013u75\",\"BN_Cart2013export\",\"BN_pdp_three\",\"BN_prodDetail_W_shoes_2recs\",\"BN_NewArrivals\"]},\"inf\":{\"dt\":\"Tue Dec 02 19:15:53 PST 2014\",\"exp\":86400,\"u\":\"ANONYMOUS\",\"cn\":\"jcrew\",\"ve\":\"V1\",\"cc\":\"www\",\"cd\":\"d&g&s\"},\"baynoteGuide\":{\"ok\":true},\"guidePro\":{\"ok\":true}}';
var userPolicyJSON = '{\"dir\":{\"au\":true},\"inf\":{\"dt\":\"Tue Dec 02 21:55:12 PST 2014\",\"u\":\"6925429440673989554\",\"ve\":\"V1\",\"cd\":\"d&g&s\"}}';
bnPolicy.registerPolicy(basePolicyJSON, userPolicyJSON);

